### ISSUE TITLE
Monitor deprecation of RestTemplate

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1087]
Monitor the eventual deprecation of `RestTemplate` from the Spring framework (see description in https://docs.spring.io/spring/docs/current/javadoc-api/index.html?org/springframework/web/client/RestTemplate.html) -- no specific release or timeline seems to be defined (yet), but the intent is there...

While we're keen to retain synchronous behaviour in the main clients to ease integration, it may be worth considering alternative clients that would also expose asynchronous capabilities (eg. to integrate with high-concurrency UIs or the like).

**Comment by mandy-chessell** [comment]
The Egeria code has a client connector that includes RestTemplate() - this is a place where the replacement calls and extended APIs can be added

**Comment by cmgrote** [comment]
Haven't seen any urgency that this is truly marked as deprecated, so suggest we push out beyond 1.4.

**Comment by grahamwallis** [comment]
The RestTemplate doesn't appear to have been deprecated and the comment in the javadoc that @cmgrote linked to talks about 'maintenance mode' rather than deprecation (with a view to future removal). I would suggest we let this close and (re-)open it if and when there we need to move from RestTemplate.

**Comment by planetf1** [comment]
Given that all of our use should be captured in the spring rest connector (other than a few anomalies found in #3056 ) a change is likely fairly simple.

There's a noticeable difference though in the design (sync vs async at the detail level) and different dependencies.

Lots of interesting articles such as https://dzone.com/articles/resttemplate-vs-webclient

I wonder if it might be better to tackle this up-front in any case since we know it will go away
