### ISSUE TITLE
Tracking open type changes

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1122]
Recently came across two changes to the open types archive that had knock-on impacts (ie. to connectors that define mappings):

- `Confidentiality`'s `level` property changing from an enumeration to an integer
- `SemanticAssignment`'s `status` property changing from a `TermRelationshipStatus` to a `TermAssignmentStatus`

It's not obvious from git history when these changes were made, nor very track-able given the ClassificationDef/RelationshipDef themselves do not have any version information in the open metadata type archive...

What can / should we do to be more explicit about changes going forward?

**Comment by mandy-chessell** [comment]
This is an important item.

All of the types have a version number.  There is also a patch mechanism (mostly) implemented to allow us to patch types.   I have not been using this mechanism up to this point, and just correcting errors in the types as we find them.  This is because there are small enough number of people using the types to keep the code in sync.  

At some point we need to decide that the types are fixed and if the types are wrong then either a new type needs to be created, or a typeDef patch needs to be added.  This will change the existing type and update its version number.   Maybe we are at this moment in time (discussion point :).

Once we do this then the type consistency checking will detect members of the cohort that are using different versions of the types and raise alerts on the audit log so we can see whether a connector is getting behind.  However, this does not help the OMAS developer.

The patching mechanism is only meaningful to changes to existing types.  We are agreeing new types in every design meeting.  As they go into git, the change should also include an update to the open metadata types description.  (But does not always).

Even with all of this in place we need a place where Egeria maintainers and consumers can monitor changes in the type system.  This could be a blog thread or slack channel.

**Comment by cmgrote** [comment]
Sounds good — agreed we may not quite be there yet in terms of needing to putting all the steps in place: but might be an idea to already start testing some of the steps (for discussion).

**Comment by cmgrote** [comment]
Closing -- proposal and discussion continuing on #1367
