### ISSUE TITLE
Egeria on the Cloud write-up

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1203]

**Comment by planetf1** [comment]
Happy to look at this at least for IBMCloud since it's my usual target & working with a couple of others doing same.
ICP is another option (as we used for think!) though it's more backlevel 
We may want to followup on GCP/Azure/AWS etc at some point.

**Comment by planetf1** [comment]
I am proposing a writeup for Redhat Openshift on developer.ibm.com since this product is commercial, proprietary & licensed offering.

Any specific notes needed to get things working will be added to the egeria docs as needed, but not a blog entry per-se

See #2538 for potential odpi content around using microk8s - a lightweight, open source kubernetes distribution which has show to work very well for our tutorial scenarios.
