### ISSUE TITLE
Add hands-on lab notebooks to GitHub

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#1297]
We have been experimenting with using Juptyer Notebooks as a way of providing hands on labs for Egeria.

This feature creates the slot in the git repository, along with some initial notebooks for evaluation.

#1273 provides the runtime environment that these notebooks could call.  Alternatively, they could be used with a local host environment to aid testing of new features and fixes.

**Comment by planetf1** [comment]
Note that the required hostnames will differ between #1273 and localhost. In future I am hoping it will also be possible to run against our k8s deployment though that is more for teams already on their way to getting setup with egeria.

**Comment by mandy-chessell** [comment]
The basic notebooks are in master now but they are not complete - will continue to improve them.

**Comment by cmgrote** [comment]
To Nigel's point above, I've taken the liberty of starting to put together a Helm chart that builds an entirely self-contained lab infrastructure (including the various separate Egeria instances, Kafka, and Jupyter)...  Assuming it's handy, we'll need to think about the `localhost` conundrum: eg. how to use hostnames that would work within the Helm charts, or in some way allow these to be parameterized within the Notebooks. (Parameters that could somehow be automatically populated as part of the Helm chart deployment, but would default to `localhost` for anyone running the labs and starting up their own infrastructure to run through them.)

**Comment by planetf1** [comment]
Thanks Chris. My thought had been to augment the existing chart -- however I think you may be right that a seperate chart dedicated to the tutorials will be easier to manage.

We potentially have 3 ways users could then run the tutorials
 * Installing the helm chart which will set *everything* up -- but requires access to a k8s infrastructure/ In theory this could include k8s provided by docker installed on mac, windows -- but it has higher footprint and more steps on linux (see docker-compose below). The benefit is we can at least predict the endpoints (names/port) within the cluster easily - the question only being whether we can preload this into a notebook (needs investigating)
 * Running notebooks directly against a user-installed egeria environment - tbh I think this is rather a bit of work for most people
 * using docker-compose - which of course has limitations, but is simpler than k8s.  Here again we can add an 'alias' to provide a well known name within the cluster.

So.. I think we could indeed default to something like egeria-tutorial:18080 in both the compose and k8s case - though needs a little investigation?

This also brings another question - where do we get the actual notebooks from? One way is direct from github. 

Finally we should cater for deploying such a helm chart (variation of vdc, or a new one) without the notebook component and ensuring it's easy for an external notebook service to access the required ports (and no getting away from the fact this is non-trivial due to ingress, nodeports & the like... )

What I suggest is if we make changes to either dopcker-compose or the k8s chart we try to also at least raise an issue against the other, to keep them as close as makes sense  (or maybe we get to provide k8s is good for all!)

**Comment by cmgrote** [comment]
I went with a separate chart as some folks might just want to try out basic Egeria stuff, and that way the chart is quite small (~1.5GB memory footprint); and we don't need to make the VDC chart even further complicated with various conditional statements to achieve the same...

I agree with you on docker-compose -- seems like a good middle ground between k8s and basic Docker, yet still allows us to run multiple components all together.

> This also brings another question - where do we get the actual notebooks from? One way is direct from github.

That's one advantage of Helm / k8s, with their `initContainers`: I'm able to pull the latest notebooks directly from GitHub and mount them into the container at startup. Basically there's a directory on the Jupyter container into which you can mount the notebook files, and then they automatically show up within the Jupyter UI. (Presumably there's similarly a way to mount files / directories in docker-compose (bind mounts?), even if it first requires the repo to be cloned locally, as it probably would be to run the docker compose in the first place?)

**Comment by mandy-chessell** [comment]
The initial set of notebooks are in github - still lots to do but additional notebooks should come as new function is delivered.

The initial versions of docker-compose and k8 environments are in place and are being handled through other issues so I am going to close this one.
