### ISSUE TITLE
Add long description property to glossary assets.

### ISSUE THREAD

**Issue by Shrinivas-Kane** [odpi/egeria#1301]
As per discussion with @mandy-chessell  opening issue to add long description property to term and glossary related assets 
PR : https://github.com/odpi/egeria/pull/1303

**Comment by mandy-chessell** [comment]
The discussion we had was to add an optional short description to the GlossaryTerm type.  There is already a long description.  Are you also planning on changing GlossaryCategory and Glossary in a similar way?

What changes are you planning for Asset?  I am not comforatable with adding a short description to it.

**Comment by mandy-chessell** [comment]
The changes to add the short description property need to be made to this file
https://github.com/odpi/egeria/blob/master/open-metadata-implementation/repository-services/repository-services-implementation/src/main/java/org/odpi/openmetadata/repositoryservices/archivemanager/opentypes/OpenMetadataTypesArchive.java

Along with the updates to the UML doccumentation found here:
https://github.com/odpi/egeria/tree/master/open-metadata-publication/website/open-metadata-types

**Comment by mlottesen** [comment]
@mandy-chessell I think the issue is consistency.  For the vast majority of types there is only a "description" documented generally as "Description of the (whatever it is)".  For GlossaryTerm and a few other types, there is a "summary" documented as a "Short description of the glossary term." and "description" as "Full description of the glossary term.", but that is the exception.  GovernanceDefinition has the same two attributes, but the documentation for those attributes is slightly different than it is for GovernanceTerm.  And then there's Annotation, which has a "summary" but no "description" as far as I can tell.

We are currently mapping short description to description across the board.  We're happy to change that to be long description instead - ING currently seems to be expecting it to be in short description, but we can give them a heads up that we're changing it - but regardless of which one (long or short) we put into description, we're looking for a slot into which we can put the other one that we'd like to be consistent across the type system.

**Comment by mandy-chessell** [comment]
@mlottesen Please would you specific exactly what you are proposing to change.  I am now confused :)

**Comment by mlottesen** [comment]
@mandy-chessell what we're looking for is a standard way to send both short and long description for everything, not just GlossaryTerm.

**Comment by mandy-chessell** [comment]
@mlottesen For glossary term, the mapping of short description to summary and long description to description makes sense to me.

I am not in favour of updating all types.  Since IGC does not support relationships and classifications explicitly then updating these does not seem necessary - irrespective of whether these fileds are useful.

There are many entity types that are automatically created.  I do not see where a short and long description would never be filled out.  For example, schema elements, data fields and annotations.  Descriptions of these element's meanings should be stored in attached glossary terms and tags.   Even for elements created by individuals such as feedback (comments, ratings, ...) it is hard enough getting any text out of people - but expecting them to create a short and a long description is asking too much :)

If these fields are really needed on EVERY entity then I would suggest adding a new Classification called AdditionalDescription that includes the long and short description.  Wherever needed, a classification can be added to the entity.

My preferred approach is that the types are updated on a case by case basis to ensure the types remain meaningful. This should focus on elements that are descriptive.

As an initial list I would suggest glossary terms, glossaries, glossary categories, governance definitions and assets.

- As described above, glossary term is ok.
- glossary and glossary category have a display name and description, we could add an abstract property to these entities.
- All governance definitions have a summary and a description already.
- Asset currently has a description attribute and the assetSummary is located on the relationship between Connection and Asset.  If we move assetSummary to the Asset entity then only one summary is possible per asset.  This will need corresponding changes to the OCF to extract the summary from the Asset entity.  This also impacts the OCF Handlers.

What other entity types would need to be changed if we were doing this on a case by case basis?

**Comment by cmgrote** [comment]
What about using the `additionalProperties` map that is part of every `Referenceable` as an alternative?  I've been thinking of this as a way to send properties that one or more repositories may use -- without needing to extend the open types themselves (though naturally if it makes sense to do so, by all means).  It feels to me like `short_description` and `long_description` fit this scenario...  (And they aren't actually on _every_ entity in IGC, either.)

The sample connector we've built treats them this way:

- for GlossaryTerm, `short_description` is indeed mapped to `summary` and `long_description` to `description`
- for other asset types, any unmapped IGC properties (like `long_description`) are automatically put into `additionalProperties` of the open metadata entity -- using a map key that matches their property name in IGC (eg. `long_description` as the map key)

This way no information from IGC is lost, and anything that expects to pickup IGC-specific properties can still do so (from the `additionalProperties` map), but the open types themselves do not necessarily need to change (ie. if we expect the property in question to remain repository-specific rather than a more general need).

**Comment by mandy-chessell** [comment]
Where are we with this change ?

**Comment by mandy-chessell** [comment]
Is this resolved?

**Comment by Shrinivas-Kane** [comment]
we don't need this for IGC <-> OMRS perspective; so closing it; @cmgrote Please re-open if we need it for egeria in general
