### ISSUE TITLE
How to delete just created TypeDef ??

### ISSUE THREAD

**Issue by immmus** [odpi/egeria#1304]
Hi!

I can't delete the type I just created. I get an error:
{
    "class": "VoidResponse",
    "relatedHTTPCode": 400,
    "exceptionClassName": "org.odpi.openmetadata.repositoryservices.ffdc.exception.TypeDefInUseException",
    "exceptionErrorMessage": "OMRS-REPOSITORY-400-001 Unable to delete the TypeDef Db (guid = 305812a3-4f74-4613-bfef-87be14846293) since it is still in use in the open metadata repository myservera",
    "exceptionSystemAction": "The system is unable to delete the TypeDef because there are still instances in the metadata repository that are using it.",
    "exceptionUserAction": "Remove the existing instances from the open metadata repositories and try the delete again."
}

I created it without associating with any entities and then I want to delete it, but it does not work for me, please tell me what needs to be done to remove it.

**Comment by mandy-chessell** [comment]
How did you create the type and which repository are you using?
This will help to know how to remove the type.

**Comment by immmus** [comment]
> How did you create the type and which repository are you using?
> This will help to know how to remove the type.

I created a type using the SpringRESTClientConnector by sending a request to "org.odpi.openmetadata.repositoryservices.rest.server.spring.RepositoryServicesResource" using the "addTypeDef" method (URN: / servers / {serverName} / open-metadata / repository- services / users / {userId} / types / typedef), trying to delete through the method "deleteTypeDef" (URN: / servers / {serverName} / open-metadata / repository-services / users / {userId} / types / typedef / {guid } / delete). These actions were carried out both in "in-memory-repository" and "local-graph-repository". In both cases, I received this error.

**Comment by mandy-chessell** [comment]
If you restart the server, the type will no longer be recognized since neither of these repositories store TypeDefs.

Typically new types are hardened into an open metadata archive that is defined in the server configuration and they are loaded at each server start up.

We probably should put out warning messages when the addTypeDef() is called.

**Comment by immmus** [comment]
> If you restart the server, the type will no longer be recognized since neither of these repositories store TypeDefs.
> 
> Typically new types are hardened into an open metadata archive that is defined in the server configuration and they are loaded at each server start up.
> 
> We probably should put out warning messages when the addTypeDef() is called.


How then can I add and delete new types while the server is running, without reloading it (as is done in apache atlas) and which repository to use? 
Thx.

**Comment by mandy-chessell** [comment]
You can add an archive to a running server - however also needs to added to configuration document so it is loaded at the next start of the server.

The reason for going down the archive route is to make it easier to ensure the same type definition is loaded into all of the servers in the cohort.

**Comment by mandy-chessell** [comment]
When a server connects to a cohort, it sends out details of the types it supports to ensure there are no conflicts that could cause integrity problems when the metadata is exchanged.

Even if the server is standalone, having the type definitions governed and controlled through the archive process makes it easier to recreate the server after a failure, or moved between dev, test, prod as it is possible to ensure consistent types in all environments.

**Comment by immmus** [comment]
> When a server connects to a cohort, it sends out details of the types it supports to ensure there are no conflicts that could cause integrity problems when the metadata is exchanged.
> 
> Even if the server is standalone, having the type definitions governed and controlled through the archive process makes it easier to recreate the server after a failure, or moved between dev, test, prod as it is possible to ensure consistent types in all environments.

Actually we are trying to understand how could we use Egeria instead Apache Atlas. We expect, that Egeria has more functionality then Atlas, we are trying resolve next case:
There are a lot of different systems, like: Oracle DB, Kafka, HDFS, Fuse ESB, IBM DB2, which has some data assets and processes for data transformation. We want to build central metadata system with all data assets (tables, views, processes, term and business descriptions - any additional information), like Apache Atlas. For this purpose we are researching Egeria. 
1. Could you explain the main purpose of Egeria?
2. Could send some business cases for Egeria?
3. Regarding your answer - when we add new typedef we should reboot system, but how we could build high availability system?
4. Is it possible upload data from Atlas to Egeria on regular basis (without additional programming)?

**Comment by mandy-chessell** [comment]
Good questions :)

1) Egeria has 3 purposes:
- Provide basic metadata and governance APIs and metadata repositories.
- Enable the sharing of metadata between different tools and metadata repositories.
- Enable new use cases from the enterprise federated view created by the sharing of metadata.

2) Egeria's business case is built from:
- Savings in cost of maintaining metadata in multiple tools
- Savings in cost of maintaining data through automation of data management processes

3) You do not need to reboot server to add a typeDef since an archive can be added to a running system.  TypeDefs are only held in memory so if they are not encoded in an archive that is loaded either as part of server start up or a later admin call then the type is lost.   I added an issue to allow the delete of a typeDef that has no instances from a running server.  However we would only see the dynamic creation of types in a development environment. This is because of our focus on metadata exchange which means the types need to be stable to allow different technologies to map.

There are over 400 open types defined in Egeria and we are open to extend them as needed.  Much of want you want to represent may well fit into existing types.  For example, the system types that you mention are all types of IT Infrastructure assets that host other types of assets, such as data stores, data feeds, APIs and datasets.

The big item we are missing at the moment that you will probably need is the UI for business users to support catalog searching etc.  This is work in progress and is probably a couple of months away.

4) Egeria has full support for a set of services for metadata synchronization.  It is necessry to create 2 connectors to add a new type of metadata repository to the ecosystem.  The Atlas connectors are 
There is a repository proxy in development that will provide the connector implementations hosted in an egeria server that will automatically syncronize metadata from Atlas to Egeria.  It is located in this repository and should be available soon:  https://github.com/odpi/egeria-connector-apache-atlas

I can find someone from the team to take you through the open types to work out what can be mapped and what needs additional types if that is helpful.

**Comment by immmus** [comment]
> Good questions :)
> 
> 1. Egeria has 3 purposes:
> 
> * Provide basic metadata and governance APIs and metadata repositories.
> * Enable the sharing of metadata between different tools and metadata repositories.
> * Enable new use cases from the enterprise federated view created by the sharing of metadata.
> 
> 1. Egeria's business case is built from:
> 
> * Savings in cost of maintaining metadata in multiple tools
> * Savings in cost of maintaining data through automation of data management processes
> 
> 1. You do not need to reboot server to add a typeDef since an archive can be added to a running system.  TypeDefs are only held in memory so if they are not encoded in an archive that is loaded either as part of server start up or a later admin call then the type is lost.   I added an issue to allow the delete of a typeDef that has no instances from a running server.  However we would only see the dynamic creation of types in a development environment. This is because of our focus on metadata exchange which means the types need to be stable to allow different technologies to map.
> 
> There are over 400 open types defined in Egeria and we are open to extend them as needed. Much of want you want to represent may well fit into existing types. For example, the system types that you mention are all types of IT Infrastructure assets that host other types of assets, such as data stores, data feeds, APIs and datasets.
> 
> The big item we are missing at the moment that you will probably need is the UI for business users to support catalog searching etc. This is work in progress and is probably a couple of months away.
> 
> 1. Egeria has full support for a set of services for metadata synchronization.  It is necessry to create 2 connectors to add a new type of metadata repository to the ecosystem.  The Atlas connectors are
>    There is a repository proxy in development that will provide the connector implementations hosted in an egeria server that will automatically syncronize metadata from Atlas to Egeria.  It is located in this repository and should be available soon:  https://github.com/odpi/egeria-connector-apache-atlas
> 
> I can find someone from the team to take you through the open types to work out what can be mapped and what needs additional types if that is helpful.

Thank you. I will prepare more concrete questions and sent them.I look forward to hearing from you in the nearest future.
