### ISSUE TITLE
Consistency of regex support across repository connectors

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#1316]
We need to ensure that repository connectors behave consistently with regard to regex support, in the specification of string search expressions used in the 'find...' methods.

It is not practical to expect all repositories (or their connectors) to support regex searches.  However it is also not preferred to adopt a lowest-common-denominator approach and inhibit the use of regex for those repostiories/connectors that do support it.

A single find... call delivers either a result or an exception - whether at the local level or at the enterprise level. There is no concept of a partial result and no desire for one - e.g. that would return some data with an exception or result code that suggests that more data might have been returned had the connector been able to support the regex used. We also should avoid the (possible?) generation of false positives by a connector that does not handle regex syntax. Especially at the enterprise level, the call to find needs to return one (aggregated) result. 

For this reason, a connector for a repository that does not support regex syntax should detect that a regex expression has been issued and should return an empty or minimal result. This is consistent with the 'best-efforts' nature of the find... methods and avoids the lowest-common-denominator approach in which no connectors could support regex. 

The in-memory and graph repository connectors support regex.
The graph repository combines regex support with substring support (see issue #1315) such that the regex is matched to any substring of the property value (in the find..ByPropertyValue methods).

A user that has a non-regex repository that replicates to an Egeria built-in repository (i.e. at least the in-memory or graph repositories) would still benefit from the ability to use find with regex against the replicated metadata in the Egeria repository. This is without the non-regex repository needing to support regex or perform any sophisticated logic.

@cmgrote, @CDaRip2U, @mandy-chessell - for comments please

**Comment by cmgrote** [comment]
> The graph repository combines regex support with substring support (see issue #1315) such that the regex is matched to any substring of the property value (in the find..ByPropertyValue methods).

Per my comments on #1315 I find this confusing...  If a caller wants to do a substring, and they can already specify regexes, why not specify the regex for such a substring?  Then if the caller does *not* want a substring (but an exact match) they can simply specify the regex accordingly?  It's confusing to me that some methods implicitly do a substring + regex and others only do a regex without the implicit substring...

**Comment by grahamwallis** [comment]
One problem (maybe) with assuming that all connectors can support regex is what happens if there is a property that contains meta-characters - i.e. characters that are part of the regex syntax.

Consider a qualifiedName that has value "first(second)" or "first.second". We have seen examples of this with the names composed from various parts in IGC.

With the proposal as it stands, a connector to a repository that does not have regex support would return null in response to a query (e.g. findEntitiesByProperty() that specified the exact value. I am assuming this would be the case because the connector could not know whether the meta-characters are literal or indicative of a regex.

@cmgrote @mandy-chessell @CDaRip2U

**Comment by cmgrote** [comment]
I would expect the caller (whether OMAS or direct) to escape values as-needed -- as they should all be "regex-aware" in as much as they're invoking a method which (by our proposal) always expects a regex...  Repository connectors that cannot handle regexes would ideally first validate the search string received to see if it is a regex expression that it can handle (or not).

**Comment by cmgrote** [comment]
Extending comment above, based on today's functionality call discussion: a couple of us are wondering how often regex will likely be used for searching -- we're assuming this will be relatively rare compared to either exact matches or simple substring matching.  If so, and it's putting significant complexity on the callers (OMASes, etc) to handle regex-escaping and on the repository connectors to do regex-handling / detection (and / or always forcing a regex-aware cohort member to which all metadata is replicated in order to handle the searches), we're wondering if it might be better to have a separate set of find methods that work explicitly against regular expressions and a separate set of find methods that do not use regexes (ie. always do an exact match or substring match).

(I'm personally trying to identify the key use cases where an OMAS or other caller would need to use regexes?  It seems that in 80%+ of cases the OMAS will be trying to do an exact match or passing along a user-provided string, which is probably only a regex in fairly rare / special circumstances?)

The concern is that we build in a lot of complexity for handling regexes in general when they're more of a special case (?)

**Comment by cmgrote** [comment]
After today's functionality call, moving ahead with at least consistency and regex usage for the existing `find...` methods (other options to be further cogitated and discussed at a later time).

To assist, helper methods are introduced to escape (qualify) strings that might otherwise be interpreted as regexes but that should not be so interpreted -- see #1339

**Comment by cmgrote** [comment]
Just for further clarity, as we seem to point back to Java's own support for regexes, should we be assuming that for `find...` methods that take an `InstanceProperties` object as their set of criteria:

1. that regexes will only be supported on the primitive types (ie. not maps, structs, arrays, etc themselves, but potentially the primitive values nested within these)
1. that regexes will only be permitted on those properties whose type is `String` (the only type that Java supports regexes against)?  (ie. no regexes for char, byte, boolean, int, double, float, long, short, date, or other values?)

What about enums, do we allow regexes within their symbolic name, assume we only search based on the ordinal, or ... ?

**Comment by grahamwallis** [comment]
I think that the regex processing should be applied to Strings and collections of Strings. 
A single (primitive) String can be String-encoded for search indexing - whereas a collection of Strings (e.g. List<String>) can be Text-encoded - providing a 'contains' semantics - i.e. an entity would be returned if it has.a list property that contains the specified String.
An example is zone names. If there are use cases that need something more than this we should address them as they arise.

Enums are currently exact matched.As discussed, for now we are leaving that as-is but could enhance if needed.

**Comment by mandy-chessell** [comment]
I think we have completed the initial implementation of this feature thanks to @grahamwallis and @cmgrote.   I propose to close it - and raise new issues as we see them - the OMAS owners seem to be picking up the new function ok.
