### ISSUE TITLE
TEX feedback / suggestions

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1487]
After quickly playing around with TEX (Type Explorer) UI, a few usability comments / suggestions (most hopefully minor):

- [ ] Is the "Load types from" config necessary via the UI?  I was assuming this (or at least a default) could be picked up from a properties or somewhere similar, presumably that's what the asset search is doing (?)  Fine to have an override, but would be nice to have one load-up-able by default -- in either case, the override would ideally be a panel that can be hidden to save screen real estate (+ what's there being vertically narrowed: lots of empty space around it at the moment)
- [ ] For clarity, I'd suggest renaming the diagram types to "Entity Inheritance" and "Entity Neighborhood" as both are entity-centric perspectives.  (Also note the American rather than British spelling, as I believe our overall style guidelines are to stick to American spellings? 🤷‍♂ )
- [ ] Would be great to be able to have an (ideally type-ahead) search capability to find the type I'm interested in, rather than needing to navigate via the drop-down boxes; at a minimum (also related to screen real-estate), would be good to have the drop-downs for the type selection stash-able / hide-able, as once you're into navigating the diagram itself they're hardly used but always taking up space on the screen
- [ ] I'd love to see more stylistics applied to the property pane on the left to distinguish various pieces without needing descriptive wording: for example, use a larger font size and **bold** to show just the entity type name, without needing to preface it with "Type selected is ..."  The description could then simply be printed immediately below it, without prefixing with "Description:"
- [ ] Also related to screen real-estate, would be great to be able to collapse (show / hide) this properties pane, to allow maximal focus and navigation on the diagram when navigating around it
- [ ] Probably more of a question for the overall UI framework, but the multiple scrollbars that are embedded in various parts of the page quickly become a minor nuisance to navigation when everything doesn't fit without needing to scroll

**Comment by grahamwallis** [comment]
Thanks @cmgrote - initial responses as follows:
1. default - I think it is worth looking at this in the wider context - could be that we want to integrate with other UI components or drive from a common properties file - but on the other hand, if a user wants to see the 'whole' type system then they probably want to configure for a server that has an in-memory or graph repository, in which case it may need to be very clear (to the user) that type explorer is connecting to their currently configured default. The type explorer should also allow a user to examine what types a particular repository understands; so specifying the server explicitly may be a desirable 'step' that the user should consciously make. Independently of any of the above, I will look at real estate too - a scarce resource!
2. I agree - will rename them - the current names were adopted in our storyboards before we went more heavily entity-centric. Additionally I am considering doing a refactor/rename of some of the code as well - with a view to possible integration (maybe) with REX - it needs to be clearer that TEX is dealing with Types. Will adopt US-English as that is general across the rest of Egeria.
3. I will look at collapsing the type selectors.
4. I will try to stylise the details pane - in fact I have done something similar already for REX.
5. Less sure about collapsing the whole details pane - but will see what I can do
6. Scrolling is a major bane at the moment - particularly as I have not found a way of auto-scrolling a diagram - e.g. the "Entity Inheritance" diagram. The prototype always scrolled to center the selected type but I cannot find a way of achieving that from inside a web cpt. I would still like to get auto-scroll working because it minimises the number of times the user needs to scroll the diagram - which at least partially improves/avoids the multi-scrollbar problem you noted. I also dislike the multiple scrollbar effect, as we have at the moment with both overall (window) scroll bars and scroll bars on the individual diagrams. This isn't easy to solve (imho) due to the real estate issue. I can try (again) to save some real estate in the Entity Neighborhood diagram, but the Entity Inheritance diagram will  likely never fit completely in the browser window, so will always need scrolling.

Many thanks for the thoughtful feedback. I am currently engaged on other things, but will try to refresh TEX as soon as I can in line with the above.

**Comment by grahamwallis** [comment]
One other thing that I want to record here is that I want to add the TypeDefGUID to the details panel for a type. I find it very useful - e.g. when posting an instance create to Postman - and always have to dig into the types archive. It would be a helpful addition to TEX.

**Comment by grahamwallis** [comment]
First PR for this issue is PR 1548
More to come!

**Comment by grahamwallis** [comment]
Diagrams names updated in PR #2006

**Comment by grahamwallis** [comment]
Keep open

**Comment by grahamwallis** [comment]
Keep open...

**Comment by grahamwallis** [comment]
Keep open - getting to it eventually!

**Comment by grahamwallis** [comment]
I think these are all fixed in the p-s UI apart from the collapse of the whole details section which I'm not in favour of due to the need for an additional icon/button and user step to expand it (or re-expand it). Going to close this and we can open fresh issues if we want to make further changes.
