### ISSUE TITLE
Ui tenancy introduce UI config file and admin call for UI  

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#1568]
initial content to only contain the mappings to the back end. this initial piece of code will not effect current operations. The file config will be made active in a later issue

**Comment by davidradl** [comment]
This includes adding the config store connector

**Comment by mandy-chessell** [comment]
It would be better to use the term "configuration document".   This is partly to be consistent with the same concept in the OMAG Server Platform and partly because the storage destination of the configuration document is determined by the configuration store connector.  Using a file is merely the behaviour of the default connector.  Other connectors may use a database or another type of data platform.
