### ISSUE TITLE
Public Docker Hub images versioning

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1595]
At the moment our various Egeria-owned Docker images publicly available via Docker Hub are using a `1.1` tag, despite Egeria itself not having a 1.1 release...  I think this is confusing / problematic from a consumption perspective?

Each of these also has a `1.1-SNAPSHOT` tag: not clear why we're not updating this version alongside `:latest` for consistency across our unreleased artifacts' versions?

- https://hub.docker.com/r/odpi/egeria-configure/tags
- https://hub.docker.com/r/odpi/egeria/tags

(Note that the images for other projects, like Apache Ranger and Apache Atlas use `:latest` and the version number for those projects' releases on which the images are built.)

**Comment by planetf1** [comment]
I agree - we should align the versioning along with the code

Note I am currently fixing an egeria image build break - should be sorted in next day.

**Comment by planetf1** [comment]
Adding some notes as we prep for 1.1 release

The docker image builds typically have lines like
```
# Default to latest snapshot from official odpi repository
ENV version ${version:-"1.1"}
ENV repo ${repo:-"https://odpi.jfrog.io/odpi/egeria-snapshot/"}
```
to retrieve artifacts. This is fine during development - but here we've moved on from snapshot just before release. Arguably part of our final stage prior to release is to update this repo first to snapshot, then to staging. This could be done here, or in the pom.

Then in the pom itself we tag 'latest' which we only want to do with master, not all releases.

I will patch up manually for the 1.1 release, whilst we consider automating this for the next release.

**Comment by planetf1** [comment]
Additionally, we may want to seperate out where the docker images go - technically my quick patch will push a 1.1 release to dockerhub early (whilst being 'staged')

**Comment by planetf1** [comment]
I think we'll need to revise the naming scheme along the lines of

* Only tag master builds as 'latest'
* Use tags of the form ${project-release}_${component.version}
* For build images use ${project-release}_${component.version}-build
* Do the same for gaian, ranger, atlas 
* Use egeria-${component-name} for the repository name

Do this in 1.1 & master
We then update the Dockerfile (where build images used), docker compose & helm charts accordingly
For now stopping 'latest' will be a manual removal in the branch

What I think we end up with is the 1.1 build resulting in 
egeria-apache-atlas:1.1_2.0.0
egeria-apache-atlas:1.1_2.0.0-build
egeria-apache-ranger_1.2
egeria-apache-ranger_1.2_build
egeria:1.1
egeria-configure:1.1
egeria-omrsmonitor:1.1
egeria-gaian:1.1_2.1.8

whilst the master build produces
egeria-apache-atlas:1.2-SNAPSHOT_2.0.0
egeria-apache-atlas:1.2-SNAPSHOT_2.0.0-build
egeria-apache-ranger:1.2-SNAPSHOT_1.2
egeria-apache-ranger:1.2_SNAPSHOT_1.2_build
egeria:1.2-SNAPSHOT
egeria-configure:1.2-SNAPSHOT
egeria-omrsmonitor:1.2-SNAPSHOT
egeria-gaian:1.2-SNAPSHOT_2.1.8
.. and also tags all of these with 'latest'

Does this make sense @cmgrote ? Other ideas welcome! I will need to make a change next Monday since we're going to get into build clashes, and I need to set the pattern for releases going forward

**Comment by planetf1** [comment]
Once the versions are sorted a later iteration can figure out adding a staging area in artifactory ...

**Comment by cmgrote** [comment]
I wouldn't tie the non-Egeria components to an Egeria release, unless we need to for some reason?  The Docker images for those are just built as default released code for those components -- they should not have anything from Egeria inside them (so should be entirely independent of an Egeria release)...  Keeping to this should help ensure that we don't embed things and keep our separation appropriate for running in pre-existing environments of these components 😁 

As such I'd leave them to eg.:

- apache-atlas:2.0.0
- apache-atlas:2.0.0-build

etc

For the Egeria-specific ones, by all means go with the version number.  I would even suggest doing away with the `1.x-SNAPSHOT` as a version, and just use `latest` -- so we'd end up with the following complete list:

- `apache-atlas:2.0.0`
- `apache-atlas:2.0.0-build`
- `apache-atlas:build` (this would be the build-equivalent of "latest")
- `apache-atlas:latest`
- `apache-ranger:1.2.0-build`
- `apache-ranger:build`
- `apache-ranger-admin:1.2.0`
- `apache-ranger-admin:latest`
- `egeria:1.1` (this would be the mostly static release-based image)
- `egeria:latest` (this would always be the latest snapshot-based image)
- `egeria-configure:1.1`
- `egeria-configure:latest`
- `egeria-omrsmonitor:1.1`
- `egeria-omrsmonitor:latest`

And for gaian I'm not sure...  Seems like we should do some work to ensure that image is vanilla gaian, and then follow the convention for the non-Egeria images?

**Comment by planetf1** [comment]
1. Since we potentially share the odpi docker account, we probably need to scope our names with egeria (since we're renaming anyway). 

2. Given that the base builds for atlas, ranger are part of the source base, I'm keen to ensure the builds are version specific and repeatable, and there's no chance of accidental overwriting,  and giving us the flexiblity to move forward. I I agree with you that they should be just the core code - but then if we really want the best approach we should be working on PRs for ranger & atlas & getting them to publish the base builds we can then just use? I see the point about the 'build' label which seems useful. It maybe that moving the build of atlas, gaian, ranger to another repo makes sense too

2b. I see the point about the 'build' label which seems useful. 

3. Keeping the -SNAPSHOT keeps the versions of the images aligned with that of the source code. It also clarifies this is not release level code. 

4. Gaian is a big topic in its own right....

**Comment by cmgrote** [comment]
Thinking about this a bit more, maybe it makes sense _not_ to push the snapshot-based builds into Docker hub?  Since these will likely change daily or even more frequently, they might be a bit "too volatile" for the general public of users to try to keep up with (?)

We could use our Artifactory setup as an alternative Docker repo for the per-PR-merge latest snapshots of images, and only push the release-based images to Docker hub?  Then `:latest` would just be a tag to the latest release that's available on Docker hub itself, rather than being a separate image from the released images...

**Comment by planetf1** [comment]
#2579 has made the build versioned (hopefully).
I propose no change to the repo used for now, we will just work with consistent naming
I will raise a new issue to publish release-specific builds from the release pipeline

**Comment by planetf1** [comment]
See #2583
