### ISSUE TITLE
Code vulnerability of log (CRLF) injection with SLF4J

### ISSUE THREAD

**Issue by cong78** [odpi/egeria#1670]
Currently we are having a lot of code vulnerability issues pointing to our logging usage and configuration. One Example can be:  
`This use of org/slf4j/Logger.error(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V might be used to include CRLF characters into log messages`
[https://sonarcloud.io/project/issues?id=odpi_egeria&open=AW1I4Bhzy_DBw5tIvGpg&resolved=false&types=VULNERABILITY](url)

And you can view the vulnerability details through this link: 
[https://find-sec-bugs.github.io/bugs.htm#CRLF_INJECTION_LOGS](url)

To solve this issue, there are two things we need to do: 
- Set up a best/common practice of how to use logging to prevent further similar issues in the community
- Resolve existing issues by applying some solutions, such as sanitize each parameter or change the logger implementation that replace new line by spaces.

**Comment by grahamwallis** [comment]
When we discussed this in AMS I thought there were two possible actions:
1. Someone suggested this could be resolved by configuring the logger (I'm don't know the details).
2. Otherwise we could wrap the logger in an Egeria logging interface that parses and removes/escapes the offending characters (\r \n).

If anyone can post details of how to configure this that would be great, otherwise I think we should do option 2.

**Comment by planetf1** [comment]
Using https://github.com/javabeanz/owasp-security-logging/wiki looks attractive as it encompasses a number of best practices and also adds the ability to do things like declare a log entry may contain confidential data (it then gets masked by default). It goes further into more audit related entries, but for egeria we should focus that on our audit logs. (not experimented yet)

**Comment by planetf1** [comment]
We mostly use slf4j in our code. For clients we include logback with a default config, but the libraries will pick up whatever slf4j config the including component specifies.

* Need to look through the poms in more detail to figure out whether we can just pull in the owasp dependency (or include own config files)
* Need to rerun a full spotbugs scan (mvn clean install -DfindBugs) [1 hour] to see if issues are cleaned -- since logging comps are pulled in at runtime I'm not convinced the scanner will know we've addressed it, so may still have to mark as mitigated - need to experiment with this

**Comment by planetf1** [comment]
I'm trying a build with the owasp plugin to see how it works with the dependencies & spotbugs output

**Comment by cong78** [comment]
> If anyone can post details of how to configure this that would be great, otherwise I think we should do option 2.

Hi Graham, thanks for the comment and I think you are right. I am trying to ask someone sitting next to us as they have solved this issue before. :)


> I'm trying a build with the owasp plugin to see how it works with the dependencies & spotbugs output

Please let us know how that plugin will work if it can save us a lot of time.

**Comment by planetf1** [comment]
still valid

**Comment by shederman** [comment]
Anything on this? We may have to move off SLF4J if no resolution is available. Would hate to do that, I love it. But security is security, and we can't use a logger that can be compromised so easily.

**Comment by planetf1** [comment]
No update, though note that by default logging is now disabled. We've put effort into trying to create rich AUDIT events which capture everything we believe should be needed to aid in operating the system. There's also now an audit log framework which allows for destination connectors to be written which use different back-ends for the actual logging
