### ISSUE TITLE
Data Engine OMAS - update functionality

### ISSUE THREAD

**Issue by popa-raluca** [odpi/egeria#1684]
This issue covers the update functionality for the Data Engine OMAS. 
The payload for updating processes will be the same as for the creation, Data Engine OMAS will add following checks for each process:
	* verify if the process exists based on the provided qualified name, if it does it will update the process properties.
	* verify if the portImplementations/portAliases are different from the new ones, based on the qualified names. Create the new ports, update properties for the existing ones and delete the old ones.  
	* verify if the schemType exists, based on the qualifiedName. If if does, update the proerties and verify the shcemaArributes. Update existing schemaAttributes, create new ones and delele the ond ones.
	* verify if a relationship exist before creating it(for all relationships - ProcessPort, PortDelegation, PortSchema, LineageMapping)

**Comment by popa-raluca** [comment]
@cmgrote , @mandy-chessell can you confirm that this is the desired behavior for Data Engie OMAS on update? I'm not sure about removing old ports and schema types(that are no longer present in the payload).
Can I assume that the payload for a process will always include all the ports & schemaTypes needed? And should the old ones be deleted on update?

**Comment by cmgrote** [comment]
In the case of DataStage, I expect to send you a complete payload each time even for the update (so that you can delete anything that is not included in the payload I send in the update that might already exist on your end).

However, I'm not sure whether we should assume this to be the case for _all_ data engines...  As such, it might be worth adding an "update semantic" enumeration to the update payload -- something along these lines:

- `REPLACE` would mean take only what is in the payload sent to the update, and remove anything that already exists that is not included in the payload
- `APPEND` would mean add whatever is in the payload sent to the update to whatever already exists (ie. don't delete anything)

**Comment by popa-raluca** [comment]
Thanks @cmgrote , I will add the new updateSemantic enum to the payload. It will only be taken into account at update time, and it will be optional. The default behavior if the enum is not present will be REPLACE.
Do we need it need at process level, or is it ok to have something like:
{
	"processes": [
    	{...},
    	{...},
  	],
    updateSemantic: "REPLACE"
}

**Comment by cmgrote** [comment]
> Do we need it need at process level, or is it ok to have something like:

I think either way is reasonable -- up to you.

**Comment by popa-raluca** [comment]
Resolved with Data Engine OMAS - implement update functionality #1808
