### ISSUE TITLE
Create release notes for 1.1

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#1717]
Create release notes for the 1.1 release

Suggestion: We can do this before we branch for 1.1, and cumulatively add for the next release? Topic for discussion ...

**Comment by planetf1** [comment]
Part of supporting https://github.com/odpi/egeria/issues/1384

**Comment by mandy-chessell** [comment]
I have created a draft release note - we should review on one of the calls this week. See https://github.com/odpi/egeria/blob/master/release-notes/release-notes-1-1.md

**Comment by planetf1** [comment]
Thanks. 

Additional content we should consider
 - Bug fixes (to existing function)
 - Dependency updates

whether we do or not, we should adopt a tagging scheme consistently on the issue sso it's easy to query at any time (and also ideally update release notes concurrently)

Alternatively we could tell the reader how to do the query and not actually include those lists in the release notes themselves.

**Comment by mandy-chessell** [comment]
@planetf1 agreed these are going into the code - are you suggesting that each release spells out its code dependencies and the bug fixes make?

I think the code dependencies is helpful.  Maybe we highlight the bugs fixed only in released function rathher than all function?  There were over 2000 commits between rel 1.0 and 1.1 so would not want to list them all.

Seems like we need to be checking all PRs to ensure that the release notes are being updated as fixes are added?

**Comment by mandy-chessell** [comment]
One thing that is missing is the IGC and Atlas connectors - these needs to have releases and we need to tie them into the Egeria releases so they are properly described and advertised.

**Comment by cmgrote** [comment]
> One thing that is missing is the IGC and Atlas connectors - these needs to have releases and we need to tie them into the Egeria releases so they are properly described and advertised.

Agreed -- the connectors themselves currently build based on Egeria core's master (snapshots): I think it would be good to ensure that we base a release of the connectors on an Egeria core release (rather than core's snapshots).  But presumably I could do this based on having a 1.1 release branch around before we cut the release itself (so I can build and verify against that branch)?

I'm also of the opinion that we might eventually want the connectors to have their own relatively-independent release cycle, so that we can include new features (like read / write operations, new type mappings, etc) that won't rely on any changes to Egeria core, but would also mean that way we don't need to wait for an Egeria core release to make such changes to the connectors themselves.  Probably we should keep this aligned via semver...

Which raises the next question for me:

- We're keeping to `1.x` for our releases, which I'm assuming is because all changes will be backward-compatible?
- Any changes that introduce breaking (non-backward-compatibility) we should move to the next major release (`2.x`, etc)
- Not sure what our plans are for patching (ie. security) of previous releases?  This would presumably give us `1.x.y` versions on Egeria core...
- We need to decide how we want to treat the connectors: should they have their own semver strictly adhering to the appropriate semantics (breaking vs non-breaking changes within the connectors themselves: so we might end up with a `2.x` of a connector while Egeria core is still on `1.x`), or should we try to reasonably align to the Egeria core release on which they're based (in which case we should probably try to have `1.x` portion of `1.x.y` of the connector version be matched to the Egeria core version, but perhaps add a `.z` for the connectors' version so that the `.y.z` portion of the connectors' version could vary according to the lifecycle of the connector itself)?  For example: IGC connector `1.1.0.2` could be a non-breaking change from `1.1.0.0`, both of which are based on Egeria core `1.1`; `1.1.1.0` would be a connector with a breaking change (relative to `1.1.0.0`) but still based on Egeria core `1.1`; etc.

**Comment by mandy-chessell** [comment]
Connectors that need their own release cycle should be in their own git repository like the Atlas and IGC connectors.  When they release they should define the Egeria dependencies.

The x.y.z releases are for emergency fixes.  No features will be added so they are not planned releases.  If we need to patch a release we will add a new release document to git.

As agreed in the design meetings, we are not doing breaking changes as a matter of policy.  We may be integrating technology that does have breaking changes and in that case, because these technologies are wrapped with connectors, it is the connector code that has to work around it.

**Comment by cmgrote** [comment]
So summarizing:

- We only have `1.x` (eg. `1.1`) as releases -- the only place new features are allowed.
- We only allow `1.x.y` (eg. `1.1.1`) for critical fixes against existing releases (no new features allowed).
- We never have a `1.x.y.z` (eg. `1.1.1.1`) release.
- We have no plans for a `2.x` release, to ensure that we actively retain backwards compatibility as a matter of policy.

(Which is nice: to keep things relatively understandable in terms of versions.)

**Comment by mandy-chessell** [comment]
Well 1.1.1.1 may happen if a patch is bad :)

2.0 will probably be a sign that we are reasonably functionally complete and want to make a statement to that effect.  If we stick to the schedule then could be doing a 2.0 in September 2020?

**Comment by cmgrote** [comment]
> Well 1.1.1.1 may happen if a patch is bad :)

Hmmm.... why not just go to 1.1.2 if 1.1.1 is bad (keeps things simple)?

**Comment by mandy-chessell** [comment]
It is indeed simpler for us - just less obvious for people consuming it - particularly if 1.1.2 is already taken.  But as long as it is documented it should be ok

**Comment by cmgrote** [comment]
Since 1.1.2 would also only be a patch (no new features) and 1.1.1 would be “broken”, the 1.1.1 users need to upgrade to something anyway — why not 1.1.3 (fixed 1.1.1 on top of 1.1.2, which presumably would still be broken in the same way as 1.1.1 if it was created before broken part of 1.1.1 was discovered)?

**Comment by mandy-chessell** [comment]
Notes from @planetf1 

We should be able to ship a 1.2.1 patch technically, but I think our intent here is to focus on the 1.3, 1.4 etc releases with an expectation adopters would quickly move up. At some point we may need to think about a broader service strategy, LTS releases etc, but I think it's too early for that. The number of . updates will be low
The docker images, helm charts, docker compose definitions should also be aligned with a release.  (1595/1640) - I'll look at this as I need to work with build team.
If we make changes to egeria side bar, hopefully the existing mobile approach of using a top menu instead will continue working (short of real estate)
For connector releases, I think the release notes for egeria should point to the connector project, perhaps a specific page on egeria release support 
We should aim to get the lineage coco demo sorted as concurrently with the code as possible.. but it depends on how stable/usable it is. 
The release notes have a strong outline for the next 10 months.I think it's time to start using 'milestones' in github to track our progress 
I am having discussions with the build team around getting 1.1 out. If anyone has any objections let me know, I expect we will branch imminently (will mention on call today)
There are some issues relating to release that we need to focus a little more on - outstanding security issues for example, ensuring licenses are documented (for example the polymer/UI licenses which need to be documented)
I would add information about dependencies being updated, but ideally this would be in the form of a github or similar query - it may be too noisy and unreliable to add in text?
Similarly I would add a list of significant known bugs/caveats that may affect anyone using the release (perhaps again we agree on bug labelling and define it as a query) - avoids duplication and clutter
Agree with chris - the nav bar text is teeny small
Going to the website on mobile (safari - xs max) now results in lovely main page text but no navigation at all (that I could see). Safari, as an example, has options to display like a mobile 
Agree with chris on rewording the docker/k8s reference in the script (I can open a PR?)
New features going through PRs should now ensure they update release notes at a suitable point

**Comment by planetf1** [comment]
From #1852 two outstanding notes need adding:

Status of UI - for example the glossary area is not working (work in progress) - see #1851
Notebooks, docker, k8s - use master.

Will create a PR & suggest specific issues are opened for any followons referred to in the discussion above.

**Comment by mandy-chessell** [comment]
It seems we are treating the UI differently to the rest of the code - is this because it is more visible?

**Comment by planetf1** [comment]
Yes, but I think we should defer most of this improvement on release notes to 1.2 - there are many areas we've improved, and known bugs we have fixed and many more areas that are work in progress.

I will just add the docker note.

**Comment by planetf1** [comment]
Added note about docker. closing.
