### ISSUE TITLE
Proposal: Change InstanceProperties type Date to Long

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#1746]
Currently, there is a PrimitiveDefCategory for DATE, and the underlying property value is stored as a Java Date object. This causes problems with serialisation and deserialisation, which until now have gone unnoticed, but if you look carefully at what actually happens on a REST exchange or when an OMRS Instance Event is sent, you'll find that the deserialization is not as you would expect. There is currently code in PrimitivePropertyValue that attempts to cope with the deserialisation, but because we always get back a String (a formatted date) it sets the value null. Trying to parse formatted dates is likely to make it difficult to support internationalization.

I have experimented with Spring and Jackson date serialisation options but am not happy that they provide sufficient (or any) control, nor that we could rely on Date serialisation continuing to work in the future. 

I would therefore like to propose that we change PrimitivePropertyValue so that a Date is always stored as the timestamp which is a Long. It would still be possible to work with Java Dates in the OMASes, etc, but when getting or setting a PrimitivePropertyValue for PrimitiveDefCategory OM_PRIMITIVE_TYPE_DATE it will expect and return a Long. 

We can update the repository helper methods (addDatePropertyToInstance, getDateProperty, removeDateProperty, addPropertyMapToInstance) so that they still accept and return Date objects, and convert internally to Long. So provided you are using one of the helper methods there should be no change.

We can also code the PrimitivePropertyValue setPrimitiveValue method to accept a Java Date and convert it to a Long. But if someone calls the PPV getter directly, the getter would always return a Long.

This proposal does not affect createTime, updateTime or effectivity dates. They would all remain as Java Date objects. The proposal only relates to Date objects as primitives in InstanceProperties.

Please let me know if you have any concerns or suggestions regarding this proposal.

Many thanks.

**Comment by mandy-chessell** [comment]
This makes sense to me ...

**Comment by planetf1** [comment]
Absolutely agree strongly.

**Comment by cmgrote** [comment]
I suspect it will have some impact on some of my connector stuff, but shouldn't be drastic -- happy to handle as-needed on my side.

Just to confirm: when we say we're storing as `long` does this mean that we are also going to follow the paradigm of _always_ storing the time internally using a single, consistent timezone (ie. GMT)?  (So that the helper or other methods that still receive a `Date` will do a `.getTime()` which explicitly uses GMT by definition, and presumably those that return a `Date` will always return it as GMT?)

We should just be clear on any interface we allow people to use directly that receives a `long` that the `long` they send must represent milliseconds since epoch in GMT, not the milliseconds since epoch in some other timezone or locale...

**Comment by mandy-chessell** [comment]
The long is the number of milliseconds since the epoch (1st Jan 1970) - it is independent of timezone.

**Comment by cmgrote** [comment]
You’re right — because epoch is explicitly defined as the time from Jan 1, 1970 UTC (so timezone is inherent in definition of “epoch”) — so sufficient to just refer to “epoch” in our interfaces to avoid any misinterpretation.

(Agreed we shouldn’t have to be this explicit, but I’ve been surprised in other conversations about people’s varying interpretations of such things.)

**Comment by mandy-chessell** [comment]
Agreed - lets be explicit

**Comment by davidradl** [comment]
Looks good to me

**Comment by planetf1** [comment]
Good clarification. I had assumed it would be epoch based - that was burnt in at an early age :-)

**Comment by grahamwallis** [comment]
Please see PR #1780

**Comment by planetf1** [comment]
PR now merged so close?

**Comment by grahamwallis** [comment]
Thanks for all the feedback. Closing.
