### ISSUE TITLE
SchemaType optimizations for Data Engine OMAS

### ISSUE THREAD

**Issue by popa-raluca** [odpi/egeria#1826]
Some changes need to be done in DE OMAS for including the schema types optimizations defined in https://github.com/odpi/egeria/issues/1669 & https://github.com/odpi/egeria/issues/1317

 * DataEngine OMAS creates/updates TabularSchemaTypes with the associated SchemaAttributes. Each SchemaAttribute will have a TypeEmbeddedAttribute classification for providing the type information. The SchemaAttributes will no longer have SchemaTypes associated to them. 
* Review and update the SchemaAttribute propeties - based on the changes done in https://github.com/odpi/egeria/pull/1545/files
* Replace the deprecated property 'name' with 'displayName' for SchemaAttribute

**Comment by popa-raluca** [comment]
@cmgrote @mandy-chessell can you confirm that this is the desired behavior for DataEngine OMAS? At this moment, it only creates TabbularSchemaTypes with associated SchemaAttributes, so I assume that it shouldn't created the SchemaTypes for the attributes anymore?

**Comment by cmgrote** [comment]
Sounds correct to me:

- Create / update a `SchemaType` for the `TabularSchemaType`
- Create / update `TabularColumn`s (including a `TypeEmbeddedAttribute` classification on each `TabularColumn` and an `AttributeForSchema` relationship between `TabularSchemaType` and each `TabularColumn`)

And indeed do not create any `TabularColumnType`s for the `TabularColumn`s.

What I can't recall is whether we're treating everything as Tabular, as this would imply, or whether we're using the more abstract (super) types: eg. `SchemaType` instead of `TabularSchemaType` and `SchemaAttribute` instead of `TabularColumn` (?)  Either way I think it will be important to be consistent and either use only the abstract super types, or only the more granular tabular-specific types...

**Comment by popa-raluca** [comment]
It creates TabularSchemaTypes with SchemaAttributes right now, I'll modify it to be consistent

**Comment by cong78** [comment]
@popa-raluca @mandy-chessell 
Can we have this feature being done in the 1.2 release instead of 1.3?

**Comment by mandy-chessell** [comment]
There are only 3 days left to complete the release.  Can it be done in time?

**Comment by cong78** [comment]
> There are only 3 days left to complete the release. Can it be done in time?

hmm in this case probably not then.

**Comment by popa-raluca** [comment]
The implementation is done, I have a PR in draft for the changes. I will do some tests today and move it into ready status if everything is ok with the tests

**Comment by popa-raluca** [comment]
Implemented by https://github.com/odpi/egeria/pull/1937
