### ISSUE TITLE
Final step(s) of release for Apache Atlas connector fails

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#1989]
Once a release has been approved, the log seems to indicate that the `jfrog` command is missing from the path when trying to distribute to Bintray:

```
2019-11-08T14:37:43.5375631Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/01e5d8a4-ea61-4356-bf1a-e7452c1c45a9.sh
2019-11-08T14:37:43.5469686Z /home/vsts/work/_temp/01e5d8a4-ea61-4356-bf1a-e7452c1c45a9.sh: line 1: jfrog: command not found
2019-11-08T14:37:43.5471425Z /home/vsts/work/_temp/01e5d8a4-ea61-4356-bf1a-e7452c1c45a9.sh: line 2: jfrog: command not found
```

@bramwelt any ideas? 🙏

**Comment by bramwelt** [comment]
I hardcoded the path to the executable because I wasn't sure how to manage the PATH, and I'm guessing a new version came out. I'll update the job and comment back once it's working again.

As it'll be a temporary fix and it'll affect the Egeria release as well, we should make a ticket to track getting it to work 'correctly'.

**Comment by cmgrote** [comment]
For this Apache Atlas connector, I'm primarily just testing out the process -- so fine to wait as well if we think the 'correct' fix is relatively quick / imminent.

**Comment by bramwelt** [comment]
Well the temporary fix worked :wink: . The atlas connector is on Bintray now. I opened a request to get the base package and `-adapter` included in JCenter (which is a requirement for pushing to Maven-Central), but I couldn't open a request for `-package` as it's missing a sources.jar.

**Comment by cmgrote** [comment]
> but I couldn't open a request for -package as it's missing a sources.jar.

Got it -- I'll look into how to address that, probably by adding the solution that Nigel's been using elsewhere to create an empty set of jar files for the sources and javadocs. (There aren't any unique to `-package` as all it does is put together a single `jar` file to avoid consumers needing to download multiple separate jar files -- the module itself has no code, thus no sources, and therefore also no docs.)

**Comment by planetf1** [comment]
I would suggest that is a good quick-fix, but I'm conscious I should revisit that quick fix in the light of recent learnings about debuggability (for example hitting the jfrog sources artifact issue) so have opened a new issue (on egeria - but would affect all of our projects). It may be a non-issue but needs some time spent to figure out.

**Comment by planetf1** [comment]
@cmgrote - with egeria core published hopefully you can tidy up/resolve the release of the connectors now? Feel free to move to the 1.3 milestone if appropriate (I will close out 1.2 shortly)

**Comment by bramwelt** [comment]
This should now be fixed in the Egeria and Egeria connector release pipelines. So in the future new releases of the JFrog CLI shouldn't break Egeria release.

It was a simple `ls` the download directory of the binaries, and reference that when updating the path; it just took a bit to understand the AZP logging [commands](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#overview)

**Comment by planetf1** [comment]
thanks - good news. 

I suggest we close this now - and reopen if any further errors occur
