### ISSUE TITLE
CTS extensions for testing read-only repositories

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#2010]

**Comment by cmgrote** [comment]
A few updates from testing on your branch -- in general, it looks better (I'm able to pass the mandatory profile with the IGC connector even without having properly working write operations now).

However, a few things I noticed that raised some additional questions:

1. When creating a new instance, it looks like the CTS is sending its own `qualifiedName`.  I hadn't thought about this, but is that what we expect?  Or do we expect that the repository itself is responsible for managing this name (the same way it manages the GUID of an instance), ie. to allow the repository itself to ensure its uniqueness?
1. Looking at the definition of the `Glossary` type, we have a `language` property which is just a String at the moment, and which the CTS is therefore sending values for like "TestLanguage".  Conceptually this feels a bit nonsensical to me -- and that we should probably have `language` be an enumeration or the like?  There are after all standards in this space already (https://en.wikipedia.org/wiki/ISO_639)...  In practice, having it as a free-form string presents an issue for the likes of IGC as IGC uses an enumeration to decide which language to use for displaying content to a user based on their chosen settings in the software (and I'd strongly suspect it isn't unique in this approach).  If we have a free-form string that we cannot definitively map to and from meaningful languages, then automatic language-specific content-choosing by the software (based on a user's preferences) can't operate.
1. When creating new entity instances I see there is an assertion `repository-entity-lifecycle-12: <type> new entity is unattached.`  Is this to confirm that there are no relationships associated with the new entity?  I can understand the rationale behind checking this, but unfortunately there are some entities that must have relationships at the time of creation: in IGC these include GlossaryTerm and GlossaryCategory, and I believe this is the same for Atlas (ie. that each of these can only exist within a Glossary)?  This likely applies to other types as well (eg. that you wouldn't be able to create a hive column without first having a hive table, etc)...
1. I've also noticed from the output an interesting point about the "optional" `OMRSMetadataCollectionBase` methods, like `saveEntityReferenceCopy`: these all first call a parameter validation method, and then throw a `FunctionNotSupportedException`.  This means that if anything in the parameter validation method fails, though, that some other exception and not the `FunctionNotSupportedException` will be thrown.  Should we be expecting to validate parameters for a method we don't intend to support anyway?  If not, should we expect repositories to override all of these optional methods to only throw the `FunctionNotSupportedException` (skipping the parameter validation), or should we update the base class to remove the parameter validation and only throw the `FunctionNotSupportedException` directly?

**Comment by cmgrote** [comment]
@mandy-chessell ^^ good to have your thoughts as well on the points above 😬

**Comment by mandy-chessell** [comment]
Some response (not sure I would qualify them as answers yet :)
1) We expect qualified name to come from the application layer - generally it refers to the thing in the real world and allows the metadata entity to be located without knowledge of the guid.  So it is typically created by the caller of the respective OMAS and not set by the repository.  The simple way to distinguish is that the repository is responsible for the header and the caller is responsible for the properties, classifications.  This split is most clearly seen in calls such as addEntity() where the caller passes what they are responsible for and the respository assembles the instance, filling in the header etc that it is responsible for.
2) The language property is a string to keep the standard open.  Typically you would expect it to be backed by a reference data table.  Our enum support is too rigid - requiring a type update to cover a new language.
3) this is a good point - we should probably relax this and turn the test into logging a discovered property relating to the automatic insertion of relationships. @grahamwallis FYI
4) the logic is that the base is a template for writing a new repository connector.  If we took out the validation then a new implementer may not notice the support for a validation class.  In the OMRS implementation, bad parameters never actually get to the real respository implementation because it is wrapped in the local respository connector which validates the parameters before passing the request to the repository.  However the repository connector may be running in a different implementation where validation does not occur.

**Comment by grahamwallis** [comment]
Thanks for testing it so promptly Chris - I will add a new test case to cover search against a readonly repo today.

On point 1, I agree with Mandy's response.

With regard to point 2, is language something we should be using ValidValueSet for?

With regard to point 3, I don't understand this. I understand Chris's overall point - and I'm happy to relax the test case - but I'd like to understand it more especially if we view it as a discoverable property. At the OMRS API level on completion of the OMRS addEntity() method being tested I would not expect to find any relationships - I would have expected them to be added subsequently by the caller, to associate (for example) the new GlossaryTerm with a Glossary. Or is there some kind of implicit, singleton Glossary to which any new GlossaryTerm is automatically associated internally within the repository, during the scope of the addEntity() method? If so, how does a caller (of OMRS) learn of the creation/existence/identity of such an implicit Glossary? 

With regard to 4, I'm happy to flip the base class methods if it would help. But as Mandy said they are a good template for repository connector implementors.

**Comment by cmgrote** [comment]
1. Fair enough; however, we probably won't be able to support any create operations to IGC in this case, as it has nowhere to store (and assert uniqueness) of such a property.
1. I was also thinking ValidValueSet, but that might add other complexities (?)  In general, even if reference-table-backed, we'd want to have some way of translating values that we're sent to values that the connector / repository understands -- this translating between different representations of the same meaning is the crux of the reference data "problem".
1. In the case of IGC, as part of configuring the proxy connector I allow defining a "default glossary".  (If none is provided I create my own default.)  Any new term or category created via `addEntity()` is automatically created inside this default glossary -- as it isn't possible to even create eg. a term without defining the parent object (glossary) that contains it.  And judging from the Atlas UI it seems to be the same there (it's not possible to create a term or a category without first having a glossary in which to create it).
1. Yes, fair enough, I was thinking the same.  Sort of wondering if I'm doing something wrong that causes the parameter validation itself to fail first; but on the other hand, as I have no intention of ever implementing some of those methods, probably best for me to just override them with a simple throw of FNS.

**Comment by cmgrote** [comment]
On (4) I'm tempted to add a new base class, that extends `OMRSMetadataCollectionBase`, and just overrides any optional methods to immediately throw `FunctionNotSupportedException` via the `reportUnsupportedOptionalFunction()`.  Then any metadata collections which intend to implement only (or primarily) the mandatory profile can extend this as their base class, and only need to override methods that they actually intend to implement...  Would this be OK?

I'd probably call it something like `OMRSMetadataCollectionMandatoryProfileBase` (?)

**Comment by cmgrote** [comment]
On second thought, that approach is probably just creating extra maintenance & confusion for people implementing (more classes to look at to figure out what to implement)...  What about swapping the method calls in the existing base class, and simply adding a comment so that implementers know that they should remove the line that's throwing the FNS exception when they implement?

Eg. changing from this:

```java
{
        final String methodName  = "getLinkingEntities";

        /*
         * Validate parameters
         */
        this.getLinkingEntitiesParameterValidation(userId,
                                                   startEntityGUID,
                                                   endEntityGUID,
                                                   limitResultsByStatus,
                                                   asOfTime);

        /*
         * Perform operation
         */
        reportUnsupportedOptionalFunction(methodName);
        return null;
    }
```

to this:

```java
{
        final String methodName  = "getLinkingEntities";

        /*
         * Default to unimplemented: remove this line and fill in implementation below under
         * "Perform operation" when overriding (actually implementing) this method
         */
        reportUnsupportedOptionalFunction(methodName);
        
        /*
         * Validate parameters
         */
        this.getLinkingEntitiesParameterValidation(userId,
                                                   startEntityGUID,
                                                   endEntityGUID,
                                                   limitResultsByStatus,
                                                   asOfTime);

        /*
         * Perform operation
         */
        return null;
    }
```

IntelliJ doesn't seem to complain about this, though I can imagine that Sonar will probably do some deeper digging and complain about code smell...  At least with this approach we keep everything in a single class, and the default behaviour is not to validate any fields for unimplemented methods -- yet those that want to override can still plainly see the validation methods they should call before doing their implementation?

Given the magnitude of methods that are not part of the mandatory profile, this approach would probably saves implementer ~500-1000 lines of copy/pasted method signatures, overrides, and JavaDoc headings that would then also need to be kept in sync should anything change going forward in the base class...  So I think well worth it in order to lower the barrier to adoption for connectors trying to just meet the mandatory profile?

**Comment by cmgrote** [comment]
@grahamwallis one other point I forgot on the CTS -- even in your branch, I changed line 208 of `RepositoryConformanceWorkbench.java` from:

```java
superType = entityDefs.get(superTypeName).getSuperType();
```

to:

```java
EntityDef implementedSuperType = entityDefs.get(superTypeName);
superType = (implementedSuperType == null ? null : implementedSuperType.getSuperType());
```

Without this change I get an NPE very early on in the testing...  I'm not sure what this is doing within the CTS, and whether we should be checking for a null and short-circuiting (as in my change), or instead logging some other problem if a null is found (?)  Seems problematic to just crash out with an NPE, though...

**Comment by grahamwallis** [comment]
Good point about line 208 - sorry had not included that change in the branch. Consider it included :-)

**Comment by cmgrote** [comment]
Regarding my earlier suggestion to swap around the validations and FNS throwing, agreed on call on 19/11 that this should not be necessary -- if the validation is throwing other exceptions before reaching the FNS then there is a bug somewhere else that should be resolved. (In any case, it should not be necessary for connectors to override the methods they do not plan to implement.)

**Comment by grahamwallis** [comment]
Please see PR #2034

**Comment by mandy-chessell** [comment]
Is this finished?

**Comment by cmgrote** [comment]
> Is this finished?

I believe so -- closing...
