### ISSUE TITLE
Build project reports for Egeria

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2120]
'mvn site' can l build some standard reports including test coverage, dependencies, licensing etc.
It can also build javadoc, and a cross ref with the code for browsing
It may be possible to add pmd, spotbug reports

This could replace the build plugin approach currently used for enabling CVE (-PCVE) and licensing (-PLicensing) in a more integrated, better format way.

Aggregate reports can cause some issues with dependencies -- one set of issues was fixed recently in #2054  - with those done, we can revisit reporting

The output of mvn site can be seen on many projects, for example
https://maven.apache.org/plugins/maven-project-info-reports-plugin/dependencies.html

is part of report for the report plugin itself (!) which nicely lays out licenses used by the project

https://maven.apache.org/plugins/maven-project-info-reports-plugin/surefire-report.html is a summary of test case execution

Many more exist, and we are a much larger project than this example, but auotmatic generation of such information could help accurately describe the project,  if run as part of a release (or a daily build)

**Comment by cmgrote** [comment]
As discussed on today's call, this sounds like an avenue to pursue in order to aggregate the JavaDocs into a single project-wide set that could be published into GitHub pages (for example), and therefore would provide a publicly-accessible, version-controlled (ie. with each release) set of detailed documentation for developers (?)

I've done a little experimentation on my side, and it looks like separating this into the `reporting` phase (so it is only constructed on a `mvn site` rather than the normal build process) ensures that it does not bog down anything else.  (Which would be good, as a `mvn site` with the default settings I'm testing with takes ~45 minutes to complete!)

**Comment by planetf1** [comment]
I agree with the goal of building  more complete aggregated docs

In recent months though, IMO, our use of maven is starting to creak at the schemes. We've hit issues with inflexibility, performance, lack of support in the community, bugs.

I would also want to consider how we might drive the creation via gradle ( I did actually try this briefly and it looks reasonable) as I think it will be better long term.

**Comment by cmgrote** [comment]
Fine for me to do that for the longer-term, but I'm keen even on a quick-fix for the near-term (ie. assuming it could take another several months or more for the gradle build to finalise and be embedded in our release pipelines, etc) (?)

**Comment by planetf1** [comment]
Sure if there's a quick way to do it go for it. It was more an ongoing concern of investing too much in legacy

**Comment by planetf1** [comment]
No easy plugins to do this in gradle. Will open up issues on any particular aspects that need addressing.
Closing
