### ISSUE TITLE
CTS version number is not representative of release?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2165]
Just noticed this when responding to #2164 -- the CTS workbench version that is reported does not reflect the actual release (seems to be fixed at 'V1.0 SNAPSHOT'):

```json
{
  "class" : "OpenMetadataConformanceTestLabResults",
  "testRunDate" : 1575540518760,
  "testResultsFromWorkbenches" : [ {
    "class" : "OpenMetadataConformanceWorkbenchResults",
    "workbenchId" : "repository-workbench",
    "workbenchName" : "Open Metadata Repository Test Workbench",
    "versionNumber" : "V1.0 SNAPSHOT",
    "tutType" : "Open Metadata Repository",
    "tutName" : "myserver",
    "profileResults" : [ {
```

**Comment by mandy-chessell** [comment]
It is correct that the version of the CTS is not tied to the workbench - however as we have officially released the CTS, then is should be V1.0 now ...

**Comment by planetf1** [comment]
We're going to have to be careful if using a hardcoded value of the form xx-SNAPSHOT since changing those texts are part of the release process, and it would be easy to do this one too in error, if indeed they should differ.

Ideally we'd not have any hardcoded version references - such as in docs/tutorials and even code, but they are there, in addition of course to the poms - which are easier to scope.

**Comment by mandy-chessell** [comment]
I think once we have removed "SNAPSHOT" from the version number it will not be picked up by the change to the poms for each release.

The reason that the CTS does not follow the release number is that a vendor would not want to have to rerun the CTS for each release unless the CTS had changed.  SO we only increase the CTS version when new test cases have been added.

**Comment by planetf1** [comment]
If we want to strictly manage the CTS independently from the release, it could be that hosting in a seperate repo would make more sense? However this adds a fair bit of overhead (builds, release, fixes etc)... but since the purpose of the CTS is as a somewhat independent arbiter of the server code, it may be justified. On balance that would probably be my preferred approach

**Comment by grahamwallis** [comment]
If the CTS version is formatted as "V.R" (e.g. 1.0) we should discuss when we would move from a minor to a major. 

For example, for Egeria 1.3 there will be some refactoring of the testcases, relationship searches become optional, some additional testcases. I would assume that refactoring alone would result in a minor bump (or no bump); additional testcases or change in profile status (mandatory vs optional) would require at least a minor bump - would they warrant a major bump?

**Comment by grahamwallis** [comment]
Here's my proposed text for the Egeria 1.3 release notes, relating to the changes to the Conformance Suite in this release.

The following enhancements have been made to the Conformance Suite:

- Search for relationships is now covered by the optional RELATIONSHIP_SEARCH profile. A repository connector can therefore be fully conformant with the (mandatory) METADATA_SHARING profile without needing to pro-vide search facilities for relationship instances. 

- The earlier ADVANCED_SEARCH profile has been split into two profiles: ENTITY_ADVANCED _SEARCH and RE-LATIONSHIP_ADVANCED_SEARCH. They are both optional profiles. This change is to accommodate the above change to make relationship searches optional. A repository connector can be fully conformant with the ENTI-TY_ADVANCED _SEARCH profile, even if it does not support relationship searches at either the basic or ad-vanced level.

- The CTS now includes testing of the mappingProperties field in the InstanceAuditHeader.

- The existing CTS tests for rehome of a reference copy have been refactored to emulate a third (virtual) reposi-tory rather than making a reference copy of an instance mastered in the CTS Server's repository.

- The CTS notebook (under open-metadata-resources/open-metadata-labs has been enhanced:

- [ ] In the Conformance Profile Results cell there is additional reporting for the new profiles described above

- [ ] A sample "Polling for Status" cell has been added for determining whether the repository-workbench has completed (its synchronous tests), which can be used to support automated test runs

- [ ] A sample "Monitoring Progress" cell for monitoring progress through the repository-workbench. This can be run durnig a test and reports how many tests have completed, etc.

- [ ] Additional HTTP response checking and improved reporting of errors (such as not being able to connect to the platform if it has not been started)

On this basis I think we need at least a minor bump (to 1.1) for the conformance suite version.
Does anyone think we should go to 2.0?
