### ISSUE TITLE
Should we have common AuditCode and ErrorCode enums from which to extend?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2302]
Looking through the Sonar reports, it seems a significant amount of duplication / code smell is being identified because we inevitably duplicate the structure of the enumerations for things like AuditCodes and ErrorCodes.

Should we create some top-level enumerations in some sort of commons module from which we can extend?  I think this would not only reduce the Sonar flags, but also should enforce consistency in how we're all defining our Audit and Error entries (ie. that we always ensure they have a messageId, severity, message, systemAction, userAction, etc) -- without needing to copy all of the getters / setters each time (?)

**Comment by cong78** [comment]
I agree. When I started developing OMAS and governance servers, I copied quite few of them and made some naming and description changes. Some of them are quite common across OMASes. 

And it would be also valuable to have consistent audit/error code as a common module?
Such as "OMAS-DATA-ENGINE-404-001 " is OMRS_NOT_INITIALIZED could be same for "OMAS-DATA-PLATFORM-404-001 ", which can be also easier for developers to start with and understand what are the audit and error scenarios to be considered?

**Comment by cmgrote** [comment]
Ah, what I didn't realise is that in Java the enums all implicitly extend `java.lang.Enum` and therefore I don't think there is any way to achieve this without changing them from enums to just standard classes (because there can't be multiple class inheritance) (?)

**Comment by bogdan-sava** [comment]
Exactly.
They shouldn't be enum in my opinion.
The code will be more flexible.

**Comment by mandy-chessell** [comment]
The enums are used to group information about each external message together - that is the message id, message text, system action and user response.  Each external message that is output should be unique (or include enough data) so it is possible to understand exactly where the message came from and why it was produced.  This is one of the principles of first failure data capture.  It does not make sense to have a common root for these values.

A component may choose not to use enums - as long as the external message definitions are cleanly separated from the code and maintain their unique properties then a component owner can choose another mechanism.

**Comment by mandy-chessell** [comment]
So all instances where the enums are the same in different modules are actually bugs.  The messageId should at least be unique.

**Comment by mandy-chessell** [comment]
The audit log includes a query interface.  This interface allows audit log records to be queries based on different attributes.  One of these attributes is the messageId.  If you wanted to known whether the Data Engine OMAS was started then having a unique start up message for that component is useful.  It would not be helpful if every component used the same start up message.

**Comment by cmgrote** [comment]
Of course: my question was more about having a common “superclass” that defined the common construct (that all of these need a message ID, numeric REST code, description, user action, etc) — not the individual instances themselves.

In an ideal OOP world I would not expect to need to redefine these basic class members and their getters over and over again when they’re identical (every enum we are defining we need to again list these 5 or so members and redefine all the same getter methods again) — I’d want to define them once and then extend that superclass each time to inherit all the members and the getters.  Then all I’d need to define in the sub-enum is the actual unique instances of the enum which are indeed unique to each area.

I just didn’t realise that this seems to be fundamentally impossible in Java when it comes to enums (since despite being capable of having their own members and methods, they cannot inherit from / extend anything, and therefore cannot have a superclass that defines these for reuse).

Seems the only way to accomplish this would be to move away from enums entirely and presumably rely on some kind of complicated “static final” instances of a normal class (which I guess can introduce other challenges when it comes to things like threading?)

**Comment by bogdan-sava** [comment]
I still believe the codes shouldn't be enums. But even they are enums.

Enums can't extend and cannot be extended but can implement interfaces.
Having a common interface for all AuditCode classes (let's call it AuditCodeInterface) will allow OMRSAuditLog to have a method `logRecord` with the interface as param. Like:

```
public void logRecord(String                      actionDescription,
                         AuditCodeInterface auditCode)
    {
        destination.logRecord(reportingComponent,
                              auditCode.getActionDescription(),
                              auditCode.getlogMessageId(),
                              auditCode.getseverity(),
                              auditCode.getlogMessage(),
                              auditCode.getadditionalInformation(),
                              auditCode.getsystemAction(),
                              auditCode.getuserAction());
    }

```

And all over the project, code like (picked up random):
```
VirtualizationAuditCode auditCode = VirtualizationAuditCode.SERVICE_INITIALIZING;
            auditLog.logRecord(actionDescription,
                    auditCode.getLogMessageId(),
                    auditCode.getSeverity(),
                    auditCode.getFormattedLogMessage(),
                    null,
                    auditCode.getSystemAction(),
                    auditCode.getUserAction());
```
 becomes 

            auditLog.logRecord(actionDescription,
                    VirtualizationAuditCode.SERVICE_INITIALIZING);


But if we are willing to refactor even more, we can encapsulate all the fields in one class and this will minimize the repetitive code in AuditLog classes (only one getter of the encapsulation) but more important will be open for extension. 
In this case `logRecord` method will be a little changed than above.

**Comment by mandy-chessell** [comment]
Creating a common interface for these enums looks an interesting approach and we could offer it as an option on the audit log interface and common exceptions.   It only reduces the number of parameters on the audit log call/exception constructor - it would still be necessary to build the formatted message.   The code example above only works for the message that does not have any inserts - this is the small minority of situations.  Currenly the logic to format the message is in the Enum class so that it is not needed in each place where the message is generated.  We could create a common class that all enum classes use to format the message - this would mean we could go to one implementation of this logic for both exceptions and log messages which sounds attractive.

Happy to do that.  It does not solve Chris's objection to having to define the getters.  Removing them could be done by having public attributes in the enums.  These methods add very little value. 

I think @cong78 is making an important point that we need to go through the expectations for logging for each component.  It should be a recorded session because all contributors need to understand this - and maintainers need to enforce it in their components.  This is not something that is standard in general software development - but necessary in embedded middleware.  This is why it is not taught at universities or on software programming courses so we can not expect new community members to know how to do this.

All components should output a start up and shutdown message but that is a tiny part of the messages that a component should define unless it it trivial.   OMRS for example has many hundreds of messages both for the audit log and the exceptions it throws.  Some of the OMASs have a very small number of messages and exceptions which suggests that there may be more work to do in those components.  

Getting this logging right is critical for our future as we need growth in the number of organizations running Egeria and many do not have deep software engineering skills.  Third parties offering support should be able to diagnose all config and operational problems in Egeria without our assistance and without needing to refer to the code or recreate the problem.  Where there are bugs, the exception thrown or the associated audit log entries should be enough for them to identify the area of the code to make it possible for the support teams to recreate the problem and show why it is failing (and hopefully supply a fix :).

This is hard to do and is something that needs to be integral to each component's design.  It is something that we will need to continuously improve as we gain experience in running Egeria in different environments.

**Comment by bogdan-sava** [comment]
This is what I meant in the second part, with a class that encapsulates the fields from the enums. 
That class will also have the getFormattedMessage. 
And the enums and interface will have a single getter that return that encapsulation class.
If we want to push even more, I think it might be possible to use reflection into the default implementation in the interface, to get that single field.

**Comment by mandy-chessell** [comment]
The enum is a class that encapsulates the values for each message and the message formatter.  I thought we were trying to improve on that?

I am not sure I understand the reflection point, could you provide an example?  I am not sure which class it would use reflection on?  I assume you are not suggesting that we implement a separate class for each message - I think that would be hard to maintain - so I am missing something.  With the enum it is easy to test message id unqiueness and we can generate a message manual from the enums.

I was thinking that since the component start up and shutdown messages are special cases and always needed, the audit log could provide dedicated methods for them.  They would need a way to create the unique message id.  This could be done by adding the message id root eg "OMAS-DATA-PLATFORM" or "OMAS-DATA-ENGINE" and it would add "_START" or "_STOP" to the root to create the unique message id.  Alternatively this message Id root value could be added to the constructor/factory methods.  The audit log instance knows enough about the component to create these messages and the standardization on the message id post fix would make it easier for any automation thati s processing these message.

**Comment by cmgrote** [comment]
On the fields, any chance they be defined as final to make them immutable?  If so I don’t see any reason not to make them public and avoid the need for getters altogether (?)

**Comment by bogdan-sava** [comment]
Encapsulate the fields

```
public class AuditCodeFields {

    private String logMessageId;
    private OMRSAuditLogRecordSeverity severity;
    private String logMessage;
    private String systemAction;
    private String userAction;

    public AuditCodeFields(String messageId, OMRSAuditLogRecordSeverity severity, String message,
                           String systemAction, String userAction) {
        this.logMessageId = messageId;
        this.severity = severity;
        this.logMessage = message;
        this.systemAction = systemAction;
        this.userAction = userAction;
    }

  
    public String getLogMessageId() {
        return logMessageId;
    }


    public OMRSAuditLogRecordSeverity getSeverity() {
        return severity;
    }
    
    public String getFormattedLogMessage(String... params) {
        MessageFormat mf = new MessageFormat(logMessage);
        return mf.format(params);
    }
    
    public String getSystemAction() {
        return systemAction;
    }

    public String getUserAction() {
        return userAction;
    }
}
```
The common interface:

```
public interface AuditCodeInterface {
      AuditCodeFields getAuditCodeFields();
}
```

The code enum example:

```
public enum ExampleAuditCode implements AuditCodeInterface {

    SERVICE_INITIALIZING(new AuditCodeFields("VIRTUALIZER-0001",
            OMRSAuditLogRecordSeverity.INFO,
            "The Virtualizer is initializing a new server instance",
            "The local server has started up a new instance of the Virutalizer.",
            "No action is required.  This is part of the normal operation of the service.")),
    SERVICE_INITIALIZED(new AuditCodeFields("VIRTUALIZER-0002",
            OMRSAuditLogRecordSeverity.INFO,
            "The Virtualizer has initialized a new instance for server {0}",
            "The local server has completed initialization of a new instance.",
            "No action is required.  This is part of the normal operation of the service.")),
    SERVICE_SHUTDOWN(new AuditCodeFields("VIRTUALIZER-0003",
            OMRSAuditLogRecordSeverity.INFO,
            "The Virtualizer is shutting down its instance for server {0}",
            "The local server has requested shut down of a Virtualizer instance.",
            "No action is required.  This is part of the normal operation of the service."))

    ;

    private AuditCodeFields auditCodeFields;

    ExampleAuditCode(AuditCodeFields auditCodeFields) {
        this.auditCodeFields = auditCodeFields;
    }


    @Override
    public AuditCodeFields getAuditCodeFields() {
        return auditCodeFields;
    }
```

They will have a single getter for the class AuditCodeFields.
OMRSAuditLog will use the interface for logRecord.
AuditCodeFields can be extended.

**Comment by bogdan-sava** [comment]
Sorry, cannot use reflection to get rid of the single getter. :) bad idea.

**Comment by bogdan-sava** [comment]
Final fields is good but not allow extension as using a class for encapsulation.
That class can be extended, for ex by InitializingAuditFields (String idPrefix, String service Name) because most of the Strings are the same, or NoActionRequiredAuditFields in order to not repeat that String hundreds of times .
The getFormattedMessage can be override if needed into a different one.
More functionality can be added into a different one that extend.

**Comment by bogdan-sava** [comment]
logRecord should add 2 signatures by overloading 
`public void logRecord(String actionDescription, AuditCodeInterface auditCode)`
`public void logRecord(String actionDescription, AuditCodeInterface auditCode, String additionalInformation)`

to allow using interface instead of fields, with or without additionalInformation , as it is null in many cases

**Comment by cmgrote** [comment]
Have just had a brief deeper look into implementing this, building from Bogdan's suggestions...

- My thinking would be to put the base classes and interfaces into a common, relatively independent location for re-use
- `common-services/ffdc-services` seems like the most logical choice (?)
- I would then expect to have all other areas that define audit codes or error codes to include the `ffdc-services` as a pom dependency (and define enums that implement the interface and use the field classes accordingly)

However, there seems to be an inverted dependency at the moment where `ffdc-services` depends on `repository-services-apis`.  (And actually a number of other modules as well.)  Not sure if this is something that we could / should refactor so that `ffdc-services` becomes relatively independent?  Or should we consider a new module that implements these base classes and interfaces, that becomes a dependency to `ffdc-services` and other modules?

**Comment by mandy-chessell** [comment]
We need to step back a bit.  Ultimately the audit log base needs to go into GAF to make the implementation of AuditableConnectors a bit cleaner.  OMRS will still hold the Egeria implementation of the audit log.  I will take Bogdan's suggestion into account when I do the restructure.

**Comment by mandy-chessell** [comment]
A couple of points on the suggested implementation since it does not quite work.  The audit log interface needs to be able to receive the formatted message as well as the fixed part of the messge definition.

It is not true that most strings are the same from message to message - these are mostly different except for modules where the component owner has not yet done the FFDC implementation.

The example of the virtualizer shown above is an example of a module with poor diagnostics.

Agree with Bogdan that we need the getters because when the messages are translated, the getters need to select the right language version.

**Comment by cmgrote** [comment]
> The audit log interface needs to be able to receive the formatted message as well as the fixed part of the message definition.

I'm not so clear on the reason for this...  Can we not have a standard interface with a method that just receives say the enum instance + a `String ...params` that is used to format the message (passing the `...params` to the message formatter), rather than needing to construct the formatted message first and pass it along to the interface?  This approach would reduce all the calls to logging from 2 lines (construct error message, call auditlog method) to a single call (call auditlog method), and I think would mean we can use this same method whether there are 0 such parameters for formatting or 20?

**Comment by mandy-chessell** [comment]
I think the intention was that the format message method will be part of the super class of AuditCode and ErrorCode?  Seems the most logical place as this will be the code that needs to ready the appropriate language version of the message and format it.  This is why it belongs to the message set logic.  Since different components - particularly from third parties - may have different methods for managing their translated message selection, we can not have this process in a core module.  It has to be possible for a component provider to override it.  This is why the message sets are kept with the owning component.

Today the format message methods all take the variable number of string parameters - there seems no reason to change it.

I also agree that the severity must be kept with the message set as it is a key part of the message definition.

**Comment by mandy-chessell** [comment]
@bogdan-sava did you say that you had a list of the common phrases that are used in the audit log messages and exception codes?  I am coming around to the idea of having common definitions for them at the very least to act as markers where the message is a placeholder and needs more work.  I agree with you that would mean that a translater would not waste time translating messages that are likely to need changing.  Could you post them to this issue?

**Comment by bogdan-sava** [comment]
The most used is the user action:
"No action is required.  This is part of the normal operation of the service."

Next are the ones used in the 
 SERVICE_INITIALIZING, SERVICE_INITIALIZED, SERVICE_SHUTDOWN, SERVICE_INSTANCE_FAILURE
that are different only by the name around 23 occurrences for each 

Ex: {Here is a different name} is unable to initialize a new instance; error message is {0}

**Comment by bogdan-sava** [comment]
@mandy-chessell do you mean to have severity in both AuditCode and Error code ?

**Comment by bogdan-sava** [comment]
Produced logs suppose to have the severity of the code, not to be parameter in the methods logRecord and logException. 
That means we need to add severity to all AuditCode, or a default one for the existing already codes.

**Comment by cmgrote** [comment]
I believe this is now complete -- closing (please re-open if not 😬)
