### ISSUE TITLE
FindEntityByPropertyValue Exception when search criteria is null or empty

### ISSUE THREAD

**Issue by danielaotelea** [odpi/egeria#2382]
Based on the documentation, findEntitiesByPropertyValue method should return the entities of the given type if the search criteria is null or empty.
     * @param searchCriteria String Java regular expression used to match against any of the String property values within the entities of the supplied type, even if it should be an exact match. (Retrieve all entities of the supplied type if this is either null or an empty string.)

I have tried to call this method with null for search criteria and I get the following exception:
{
    "relatedHTTPCode": 400,
    "exceptionClassName": "org.odpi.openmetadata.repositoryservices.ffdc.exception.RepositoryErrorException",
    "exceptionErrorMessage": "OMRS-REPOSITORY-400-055 An unexpected exception was received from a repository connector during the findEntitiesByPropertyValue operation which had message: Invalid condition: null",
    "exceptionSystemAction": "The system is unable continue processing the request.",
    "exceptionUserAction": "This error suggests there is a logic error in either this repository, or the home repository for the instance.  Raise a Github issue to get this fixed."
}

I commented out the validation for search criteria (validateSearchCriteria) from the OMRSMetadataCollectionBase in order to issue the query.

**Comment by cmgrote** [comment]
Agreed -- and this is the behaviour that used to exist, so it sounds like the parameter validation has (relatively recently) changed?  We should update the JavaDoc on the validation method as well, as I note that it doesn't have the same detailed description as the `findEntitiesByPropertyValue` method itself, which may be what led to the confusion.

**Comment by grahamwallis** [comment]
It's odd but it looks like this has been policed by the validator since June 2018 - but that's not really important. What's is important is that the documentation for the metadata collection class says null is OK, and the validators don't allow it.. 

We could:
 [re-]introduce support for searchCriteria being null in the connectors and remove the validation that disallows null.

Or we could:
Continue to not allow null searchCriteria but correct the documentation.

There is a already a way of achieving a 'full' retrieval - i.e. not filtering by seachCriteria or specific match properties - and that is to use findEntitiesByProperty() and pass a null or empty match properties object. This is the method I use in the new CTS search tests, i.e:

```
InstanceProperties emptyMatchProperties    = new InstanceProperties();



knownInstances = metadataCollection.findEntitiesByProperty(workPad.getLocalServerUserId(),
                                                                              entityDef.getGUID(),
                                                                              emptyMatchProperties,
                                                                              MatchCriteria.ALL,
                                                                              0,
                                                                              null,
                                                                              null,
                                                                              null,
                                                                              null,
                                                                              null,
                                                                              pageSize);

```

When I spoke to Mandy about this she observed that it may be preferable to have one way to do this. So, with that in mind, if the above would be sufficient then it may be better to fix the documentation and continue to disallow searchCriteria set to null.

Happy to do either. What do people think?

**Comment by danielaotelea** [comment]
In this moment, we can change the documentation for findEntityByPropertyValue and use the findEntityByProperty to get entities by entity type.
