### ISSUE TITLE
Should we be catching Exception instead of Throwable as our catch-all?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2425]
From my limited reading on the topic, it sounds like it may not be best practice to catch `Throwable` rather than `Exception`.  `Exception` includes runtime problems, while `Throwable` is a superclass of `Exception` but also includes errors like out-of-memory and stack overflows -- things that an application generally won't be able to recover from itself.

At the moment it appears that we tend to catch `Throwable` rather than `Exception` and I'm wondering if this is intentional (eg. to ensure we always can provide a standard response body back via REST?) or if we should re-consider whether to move to only catching `Exception` as our catch-all?

(see, eg. point 6 in https://stackify.com/best-practices-exceptions-java/)

**Comment by bogdan-sava** [comment]
Moreover, there are places where we are doing:

```
catch (Throwable  error)
        {
            // nothing to do - keep going
        }
```

which is a serious source of trouble.

It is very important to log the Throwable or Exception if it is caught.

**Comment by cmgrote** [comment]
Yikes!  Can you flag the places where you still see that?  We need to fix those regardless of the Throwable vs Exception debate...

**Comment by bogdan-sava** [comment]
There are 4 but in the important methods in:
GraphOMRSMetadataCollection 
InMemoryOMRSMetadataCollection

**Comment by grahamwallis** [comment]
I can fix those - which of the following styles is preferable?

Change the catch block to catch each of the 8 possible exceptions
or
Change the catch block to catch Exception (i.e. just the supertype).

In either case I would expect the catch block should be audit logging that it could not do the desired clean up and then carrying on with the delete/purge of the entity.

**Comment by mandy-chessell** [comment]
It is difficult to be definate because there are different situations.  However for most places in Egeria we need to catch Throwable - possibly after dealing with the checked exceptions for the method.   This is because we are a framework with many pluggable components written possibly by 3rd parties.  They are integrating and working with external resources so runtime exceptions are possible.  In this environment, we are serving many requests (and tenants) so exiting gracelessly is not a good option.

In the core Egeria code base we are practicing first failure data capture (FFDC).  This means that we are looking to trap errors as soon as they occur and gather additional information to log or include with the exception.  As much as possible we are looking to contain the error, and hopefully recover from it.  Sometimes it is not possible to recover, so it becomes just an information gathering exercise.

So the short answer is catching Exception is often not sufficient because it misses the runtime errors.  Only with Throwable are we sure to catch everything.

**Comment by mandy-chessell** [comment]
I think we should still discuss this on the next community call because if I am wrong and the situations where Throwable occurs means that there is no chance to do any gathering of more info then we can relax it to catch a lesser error.  

Yesterday we discussed some proposed best practices for exception handling and this should be folded in to the broader discussion.

**Comment by cong78** [comment]
![IMG_3725](https://user-images.githubusercontent.com/11947525/72503580-5694b180-383c-11ea-853a-22e7eb271050.jpg)
These are some of the discussion results. We can discuss it to see how can we make best practice for the community.
