### ISSUE TITLE
getKnownTypeDefs method always returns null

### ISSUE THREAD

**Issue by danielaotelea** [odpi/egeria#2460]
The OMRSRepositoryHelper - getKnownTypeDefs method returns null, even if there are type available in the cohort. 
The getKnownTypeDefGallery is correctly populated and it returns the active type defs from the cohort.

**Comment by mandy-chessell** [comment]
This is a simple one to fix.  The `getKnownTypeDefs()` is retrieving the types from the active TypeDefs rather than the known TypeDefs.  This means it is only getting populated with the types known to the local repository.  If the local repository is the in-memory or graph repository then this problem is undetectable.  However if there is no local repository then the null is returned - as reported in the issue.

The getKnownTypeDefGallery correctly pulls types from the known TypeDefs.

There is a similar problem with the getKnownAttributeTypeDefs.

**Comment by planetf1** [comment]
To add cross-references
 - prior report but not persued : https://github.com/odpi/egeria/issues/1340
 - original reporting problem was https://github.com/odpi/egeria/issues/2433 (since notebook environment has a server without local repo)
