### ISSUE TITLE
Add more detail to test failure reports in CTS

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#2474]
This issue is to add more detail to the assertion messages to make it easier to ascertain the cause of a failure - adding things like number of expected results vs number of actual results, etc.

**Comment by cmgrote** [comment]
Hmmm...  This looks like it's becoming more important as I think the CTS test cases (at least around search) have some element of randomness in what's tested (or at least are relatively non-deterministic)?

I believe I've run the same config against an environment populated with the same sample data, twice, and came up with two different results (one conformant, the other with a couple of test failures).  Without being able to see what the specific criteria were on the failures I'm not able to easily identify what edge case(s) are causing the problematic results; but equally it seems like if I run the CTS a few times there's a reasonable chance that one of the runs will be error-free (which feels problematic to me?)

At least in the case of search, I'm also starting to wonder how strict we should be on failures: in the sense that we've said a couple times in calls that searches should be "best efforts" for the repository (and from a "do no harm" perspective presumably they won't harm the cohort by not returning results to complicated searches)?  In other words: I'm wondering if we should move failures on searches to a "partially conformant" rather than "non-conformant" status, and if this issue is resolved so that we can see what edge cases do not succeed we could even include them in connectors' release notes as "known issues" with the connectors' ability to support search (?)

This would help greatly in the case of Apache Atlas, for example, where there are certain known limitations in the search API; but also in the case of IGC where certain properties or complicated search criteria are likely to have bugs or have varying levels of support across different versions of IGC.

**Comment by grahamwallis** [comment]
There should be no randomness in anything but the search tests. And the search tests try to be as repeatable as possible. The only room for variation in behaviour in the search tests would come from getting back a different starter set of seed instances in the initial query. The query retrieves a page full. If the page size is set very small and the order of results is not consistent then you may see greater variation. That's the only reason I can think of. Using a large page size would reduce the effect. Or we could stipulate a sequencing property. 

I don't like the idea of 'partially conferment' from search testing - the search tests are purely local to the one repository being tested - there is no asynchronous timing or federation to explain why results differ. Any failure during the search tests should be treated as a failure - i.e. a query did not match the expected result - which is based on the initial seeding query, so the repository has already returned an instance which it later fails to retrieve. SO whilst you could get a false positive I don't think you can get a false negative, so the test should be marked as a failure.

**Comment by cmgrote** [comment]
In that case I would suggest we add a sequencing property (something that would be there in all cases like sorting by GUID) to the searches to force consistent seeding, as otherwise we are open to this multi-run problem where some runs are conformant and others not.

**Comment by cmgrote** [comment]
Per the general issue here, though, is there a particular reason we have neither audit log output nor debug log output for the detailed test cases the CTS is carrying out?  Even if we modify the response to include more information on failures, I'm wondering if it wouldn't be valuable to also inject far more detailed logging into the CTS in general...

- I would suspect that the primary audience running the CTS is going to be metadata repository / connector developers -- a different audience from those running Egeria in production (?)
- even in rare cases where another audience runs the CTS it seems unlikely to me that anyone would run it against a production set of metadata (given it does instance adds and deletes as part of the testing, and I believe we've documented that we actively advise against running it against a production repository?)
- therefore the risk of exposing some sensitive information should be very low
- having something logged would make it far easier to track down what specifically has failed
- not having anything logged means those running the CTS repeatedly end up needing to add their own logging, re-build everything, and then re-run the test suite -- a round-trip that inevitably takes a few hours, every time (and is made even more challenging if the results aren't repeatable 😉)
- this puts a learning curve and an IMHO unncessary hurdle in the way of those trying to pass the CTS

To be a bit provocative: fundamentally the CTS seems to fit more into the category of development tooling than any of the rest of the platform, and yet it seems to be the only place that we've entirely left out any detailed developer-oriented logging (?)

**Comment by grahamwallis** [comment]
A couple of thoughts:

i) sequencing property - I was referring to the existing ability to sequence results based on an instance property - no need to sort by GUID for example. Currently the CTS does not elect a sequencing property, so the connector is free to return results in any order. For a single CTS run this has no consequences - but over multiple runs, if the connector returns results in a different sequence and then they are truncated by pageSize - the seed set would be different. Suppose a very small pageSize were being used and (in extremis, for sake of illustration) a single instance were returned; it would be the property values from that single instance that would be used in the subsequent search tests. What the CTS does (on all those search tests) is to insist on seeing at least the results it predicts from the seed set and it verifies any additional results are a valid match for the search query. So in our extreme example it would expect to see the one instance it has already seen - and it would tolerate additional instances that happen to also match. Using a large pageSize provides a broader seed set of instances, with a wider set of property values - so the CTS would be more likely to discover problems.  We should add testing of the sequencing property to the CTS - it is not there yet - but just adding the sequencing property would not "fix" the above issue with the seed set. At risk of ove-using the extreme example of pageSize=1, sequencing of the seed query results would have no effect at all. A large pageSize is the best way to address this, with the disadvantage that the search tests will be slower.

ii) I am in favour of embellishment of the CTS in terms of reporting of unexpected exceptions and detailed reporting of test failures (e.g. what was being tested, what results were expected, what did we actually get, why did the test fail, etc.as in the instance test exception handling already added). These improvements would turn the CTS from a conformance 'inspection' tool into an aid to a potential connector developer. That said - I am not working on these things at the moment, but that doesn't prevent someone else from making the changes. 

BTW - to add to your list above of strategies for diagnosing a test failure, I tend to re-run just the failed test and use the debugger - it's a pretty quick way of nailing the problem.

**Comment by cmgrote** [comment]
> i) sequencing property - I was referring to the existing ability to sequence results based on an instance property - no need to sort by GUID for example. Currently the CTS does not elect a sequencing property, so the connector is free to return results in any order.

Yes, this was part of my point: when not requested to provide a sorting of the results, many repositories will return results in an undefined order (so some runs through the CTS will have results that exhibit bugs in the repo / connector, and other runs will not include those results).  My thought on sorting by GUID would force the repository / connector to always include the same set of results each time it is run against that environment -- so always with results that exhibit problematic behaviour or always not.  Indeed increasing the page size would ensure that we get the broadest set possible (and hopefully include all potentially problematic results), but at least forcing the repository / connector into returning a consistent ordering for each CTS run would ensure that we don't have one run of the CTS against an environment succeed and another fail, even though it's precisely the same code, sample data and environment just because the repository / connector in one run returned results in one order and in another run in another order (and in one case a problematic result was included within the pageSize cutoff and in the other it wasn't).

(And I know we can sort by properties, but GUID is one of the sequencing options and importantly one that would be available on _all_ instances -- all instances have a GUID, not all have properties.)

> BTW - to add to your list above of strategies for diagnosing a test failure, I tend to re-run just the failed test and use the debugger - it's a pretty quick way of nailing the problem.

Hmm, good reminder that this is an option -- can you point me to any info on how to re-run just the failed test? 🙂 

While this approach is good for a few very detailed targeted problems, I'd be concerned that if it's an initial run-through of the CTS and there are 10's or 100's of failures then it might be nicer to be able to look at all the details in aggregate in the results and try to identify some initial patterns to attack rather than trying to dig into each one-by-one via the debugger (likely to be very time-consuming?)

**Comment by cmgrote** [comment]
Have added further details to the messages for search test cases, where it seems most critical (given the invocation of a search has so many parameters with potentially different values).  Not sure if it would make sense to have the same extra details in other test cases as well (perhaps a separate issue, if so)?
