### ISSUE TITLE
Cohort heartbeat

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#2475]
To cater for situations where Kafka (for example) is not available during startup and a server's cohort registration is not sent, the sending of a periodic cohort heartbeat would provide an opportunity to trigger a fresh round of registration requests to enable the servers in the cohort to discover one another.

The heartbeat message should be compacted only need contain the identity of the sender and the count of cohort members (from the point of view of the sender).

**Comment by planetf1** [comment]
An example of a situation where this occurred is covered in #2119 - whilst we also will rework how kafka is handled, this capability should add an extra level of protection in case of any lost registrations.

**Comment by planetf1** [comment]
I hit this issue again today -- I had tried to run a cohort on a different machine to usual (CTS) and kafka initially wasn't installed, then the listeners weren't configured correctly. Egeria was (mostly) queueing the messages. I can't guarantee none were dropped. I observed that once kafka was correctly enabled many messages flowed, but the cohort members remained unaware of each other. The heartbeat would have addressed this.

I restarted a cohort member, and suddenly things sprung into life - exactly as expected, since the reregistration requests flowed and cohort members got updated membership information

**Comment by mandy-chessell** [comment]
I want to keep this idea open - along #3144
