### ISSUE TITLE
Critical exceptions caught by OMAGServerOperationalServices are never logged

### ISSUE THREAD

**Issue by GuyAckermans** [odpi/egeria#2490]
Whenever an exception is thrown within the OperationalServices of any governance server that is not caught by that governance server itself, the exception is caught by OMAGServerOperationalServices instead. Subsequently an HTTP error response is returned to the user, but no logging of the error occurs whatsoever.

Errors occurring in a governance server's OperationalServices are usually fatal, preventing the server from starting, so it seems vital to me that these exceptions are somehow logged. The auditlog is server specific and so cannot be used on this level, so my proposal would be to use the sl4j logger to log these exceptions. What are your thoughts on the matter?

**Comment by mandy-chessell** [comment]
This is a similar problem to the access services.  The server start up sequence assumed that the services it is starting are performing first failure data capture which includes logging their errors to the supplied audit log.  This did not turn out to be true for too many of the access services so we also added logging to the start up sequence for access services as a safety net.  It looks like we need to do the same for the governance services.

Each governance service is passed an audit log when it is called to initialize in the server and it should be logging errors as well as information messages during its start up.

I do not understand the comment that the audit log can not be used `at this level` because it is server specific.  The governance services are only ever started in an OMAG Server context so the audit log is completely appropriate for this logging.

I think we need to add this additional logging to the start up sequence - but also raise issues against the governance services that are not doing FFDC properly.

**Comment by mandy-chessell** [comment]
I have defined these messages to surround the start up of the governance services subsystems.
These bracket the start up and report any errors.  They also encourage people using Egeria to raise issues against the governance subsystems that do not properly log start up since this is a deficiency in the subsystem.

<img width="1113" alt="Screenshot 2020-01-25 at 13 37 21" src="https://user-images.githubusercontent.com/12354195/73122051-fdcdc300-3f77-11ea-88ab-ccceaee0b191.png">

There are also similar messages for the access services.

I have also added the calls to the `restCallLogger`.  It logs the start and end of a rest call along with how long it took.  The response entry includes all of the response so errors are logged at this point.  It is only debug logging because it is designed for investigating the elapsed time of specific calls.

I had been working my way through the different Egeria serivces adding these calls as I had time.  Just had not got to this module yet.  Eventually we will have good coverage.

**Comment by bogdan-sava** [comment]
This is the same issue with catch Throwable and swallow the exception without logging.

For example, if execution reaches catch(Throwable error) no logging will tell you what is wrong.
Maybe because in the Handler, captureRuntimeException is calling captureCheckedException ?



```
 public SuccessMessageResponse activateWithStoredConfig(String userId,
                                                           String serverName)
    {
        final String methodName = "activateWithStoredConfig";

        SuccessMessageResponse response = new SuccessMessageResponse();

        try
        {
            errorHandler.validateServerName(serverName, methodName);
            errorHandler.validateUserId(userId, serverName, methodName);

            response = activateWithSuppliedConfig(userId, serverName, configStore.getServerConfig(userId, serverName, methodName));
        }
        catch (OMAGInvalidParameterException error)
        {
            exceptionHandler.captureInvalidParameterException(response, error);
        }
        catch (OMAGNotAuthorizedException error)
        {
            exceptionHandler.captureNotAuthorizedException(response, error);
        }
        catch (Throwable  error)
        {
            exceptionHandler.captureRuntimeException(serverName, methodName, response, error);
        }

        return response;
    }
```

**Comment by mandy-chessell** [comment]
@bogdan-sava that is not quite true. 

The code shown above is the exit of the method from the server where we are capturing all results into the response object.  No exception should be thrown at this point because we do not want to export stack traces from the server.  All error handling should have been done.   However we do capture all unexpected exceptions and make sure they get into the response object.  If we trusted all internal component to behave properly we could potentially remove the Throwable clause - but that risks exporting stack traces or returning exceptions without proper error message/system action/user response.  I do not think we are ready to do this. (And probably never wil be :)

The governance service that is not doing proper FFDC processing is at fault.  Only that module understands its internal components, the configuration values it needs and the external resources it uses.  This is why it has to be that module that logs the start up of its components and any errors that occur.

I have added some additional try...catch to the admin service code to pinpoint which service is not behaving properly.  This will provide the emergency logging.  It should not be necessary if all our the governance service where behaving properly.  However I realise that it is too much to expect all of these modules to be at that level of maturity all of the time which is why I added this back stop to the admin module.

We should respect the architecture and put the proper code into the proper places rather than distort the code that is behaving according to spec to compensate for other code that is not.

**Comment by GuyAckermans** [comment]
I think we are talking about different things. I am talking about the case where an exception is thrown by a governance server which was not expected by the developer and thus not catched within the governance server. For instance, say that I make a programming mistake in class org.odpi.openmetadata.governanceservers.openlineage.admin.OpenLineageServerOperationalServices and because of some rare combination of factors, an unexpected nullpointer exception is thrown which is not catched by this class itself. It will then be catched by the class org.odpi.openmetadata.adminservices.OMAGServerOperationalServices, on line 730 especially. Method exceptionHandler.captureRuntimeException will then be called so that an HTTP response containing an error is returned to the user, however this nullpointer is in no way logged and thus invisible from the console. My proposal would be to log any throwable exceptions that occur here as well.

**Comment by mandy-chessell** [comment]
In this case the governance service startup method should be catching its own exceptions and logging them - particularly if it is an unexpected exception.  This helps the person setting up the service to know that they have not done anything wrong but actually it has triggered a code defect.

**Comment by GuyAckermans** [comment]
@mandy-chessell  I deleted my message because we wrote our comments at the same time and you already addressed what I referred to in your own comment.

So is it then intended for the developers of governance servers to surround their entire OperationalServices class with try/catch to catch unexpected exceptions like these?

**Comment by mandy-chessell** [comment]
:) no worries ... basically yes - particularly the startup method.  A module should guard its edges and also its calls to plug in components such as connectors so that we can quickly isolate errors at least to the right module.

(By edges I mean where it provides external interfaces.)

**Comment by mandy-chessell** [comment]
Although it seem counter-intuitive, I find I am much more productive if I put the error handling in early because I pin-point my bugs much quicker and reduce the cycle time.

**Comment by bogdan-sava** [comment]
I was referring exactly to such cases, when the above code is not handling as it suppose. 
As you said, shouldn't reach that statement. But IF reach it, no logging is produced.

**Comment by GuyAckermans** [comment]
Thanks for your reply, I will catch throwable in my own class then.

> The code shown above is the exit of the method from the server where we are capturing all results into the response object. No exception should be thrown at this point because we do not want to export stack traces from the server.

What exactly would the security risk be if we would use sl4j logger here to log the exception?

**Comment by bogdan-sava** [comment]
@GuyAckermans  you can added to your code, but not resolve the issue.

The problem with the code above is that assumes that all the branches of the execution are handling all Throwable and the this code only catches and send the response (of course, as @mandy-chessell said, if true, this catch can be removed). 
But is not an ideal world. So, any runtime not handled anywhere in the execution, will be swallowed here, by this code, without logging.

**Comment by GuyAckermans** [comment]
I will add the catch to my code, but I indeed agree it could be advantageous to also log in the OMAGServerOperationalServices class because we should assume that no component is failproof. Therefore I am wondering what the specific disadvantages to logging in the OMAGServerOperationalServices class are.

**Comment by mandy-chessell** [comment]
The specific disadvantages are the same as we have covered in other issues - basically it gives the component owner that has not added FFDC to their code no incentive to fix it.

We now have audit logging that specifically points to the component throwing runtime exceptions.
