### ISSUE TITLE
Introducing the Audit Log Framework (ALF)

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#2537]
The ALF is a new framework for Egeria.  It defines the APIs and base classes for our FFDC implementation.

Today, each Egeria component manages its message sets for its exceptions and audit log messages using whatever impementation method they choose as long as the messages are externalized and can be extended to support multiple language version.  Most components use an enum.
The audit log implementation is provided by the repository services (OMRS).  This includes support for logging destination connectors that enable the audit log messages to be routed to different destinations depending on whatever characteristics the implementer chooses.

ALF will do the following:
* take over ownership of the audit logging API from OMRS
* provide base classes for the message sets.
* provide unit test base classes for message sets

The AuditableConnector interface will also move from OMRS to OCF and the OCF will depend on ALF.

The reason for doing this is to create base classes for the messages sets and allow individual message definitions to be passed to the audit log rather than extracting each property of a message definition to pass independently to the audit log.  ALF provides the home for these classes and avoids circular dependencies between OMRS, OCF and most of the other modules.

The Egeria frameworks are designed to be used independently of the Egeria OMAGServerPlatform.  ALF will also provide an independent set of interfaces for an audit logging service that could be adopted by other projects wishing to adopt FFDC.

**Comment by cmgrote** [comment]
I love the new simplicity of logging audit messages! 👏

Now a significant portion of #2302 seems to be implemented on the audit log side; it would be nice if we could make similar simplifications on the error (exceptions) side?  (Even if we need to leave the current many-parameter constructors for external usage, would be great to have a simpler constructor defined in the exception super-classes that takes something like the `MessageDefinition` object (eg. a new `ErrorDefinition` object) which simply calls the many-parameter constructor for us with its properties?  Then at least within the Egeria code we can use a similar interface-based mechanism to define our error codes and simply throw exceptions with the one `ErrorDefinition` object instance rather than all the parameters each time.)

**Comment by mandy-chessell** [comment]
This is all part of the plan.
The exception part is in place in the ALF - just needs to be added to the exception implementations themselves.  I am beginning to work through the modules to make this happen.  The OCF and repository services are high on the list.

**Comment by cmgrote** [comment]
I think this is now complete (can we close)?

**Comment by planetf1** [comment]
This seems complete so closing
