### ISSUE TITLE
Kafka - offset at server start

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#2547]
We've seen a number of instances where we have a 'split cohort' scenario, ie multiple servers in a cohort have joined that cohort, and are subscribed to the omrs topic, but are not aware of each other. If a new server is added or removed, the re-configuration messages cause the cohort to be resynced and each server is then aware of the other members.

Kafka typically manages offsets on behalf of an application by consumer group. By default each of our servers use their own consumer group which is generated randomly at restart, though this can be overriden via properties to facilitate HA use cases. This means that when a server restarts no offset is stored

When a consumer subscribes to a topic it will normally pick up the offset previously stored for that group id. However no offset is stored in this case as it's a new consumer group, so kafka makes use of a property 'auto.offset.reset'. Our kafka topic connector does not specify 'auto.offset.reset', and the default value for this is latest. (unless overriden in properties)

See explanation: https://docs.confluent.io/current/clients/consumer.html

The consequence of this is that by default egeria will only pick up new messages when a server is started, and won't see anything prior to that time. This makes startup ordering crucial, and a little more fragile. 

that being said, to a large extent egeria will generally 'catch up' as events occur within the cohort -- so it's actually the lack of cohort membership that is a worst-case.

We need to (re)consider how we make use of consumer groups and auto offset reset.

* Starting from the beginning would allow catchup, but we could have a massive amount of stored messages to catch up with
* In development use cases replaying old messages could cause confusion (ie from prior tests) 
* Starting 'a little bit back' is very inprecise - how far would we go to (we could use seek() )

One option is to leave as-is. If a particular use case requires different behaviour, they can specify the required consumer group, and also are able to override auto.reset.offset. In this case documenting the behaviour may be appropriate

This is likely the root cause of #2119 and also led to the suggestion of #2475 whilst likely cause had previously been assigned to #1876 and it's prior related issues 
Opening for discussion and explanation.

cc: @mandy-chessell @cmgrote @grahamwallis @danielaotelea

**Comment by cmgrote** [comment]
Given that we're keen to keep this agnostic to the underlying event bus (ie. not Kafka-specific) it's probably worth considering what we might expect the default behaviour for other back-ends to exhibit...  Would they be more likely to behave in the "pickup all events, from the beginning, when I subscribe" way, or in the way it behaves now ("pickup only any new events that arrive after I've subscribed")?

**Comment by grahamwallis** [comment]
@cmgrote - Good point about maintaining portability.

General comment: From looking at the code yesterday I am under the impression that when we create the consumer we actually assign the consumer group id to be the serverId. If that is genuinely random (from Nigel's comment above) then it seems that perhaps we should not use it, because it would prevent recognition that a restarted server is the same server as was previously running. The ideal would be for a server with a known name (e.g. 'cocoMDS2') to be recognisable on restart; so if the topic consumer were created in a consumer group for 'cocoMDS2' it could pick up where it left off prior to being shutdown - i.e. it would pick up the first message after the last committed message it previously consumed. Is that the behaviour we would like? If so using a random group seems odd, if indeed serverId is random.

Separate comment: I don't think we should leave this as is - it is confusing and unreliable. A cohort heartbeat may alleviate the problem, but I would like to understand why the current cohort registration processing is not sufficient. If on restart a server (re-)joins a cohort, it should send out a cohort registration; which should be sufficient for the existing cohort members to spot the new member and to reciprocate with their registration details. We seem to be missing that registration trigger, but it's not clear why that's the case.

**Comment by mandy-chessell** [comment]
The localServerId used as the consumer group id comes from the server configuration document.  Each time a server is started, it continues in the same consumer group.  It is only if the configuration document is recreated on each start up that there is a change in consumer group because effectively this is a new server.

A server that has joined a cohort keeps information about the other members of the cohort in its cohort registry file.  This is used on restart as the initial list of remote members.  It means that even if registration messages are missed, it will start with the same list of remote members as were in the cohort when the server went down.  The cohort registry file should only be deleted if the server is being destroyed.  If it is deleted between server restarts then the server is completley reliant on receiving the registration requests via the cohort topic.

**Comment by planetf1** [comment]
Thanks for the clarification. This helps explain why I see the issue regularly, since for testing k8s deployments, or indeed running/testinc code locally I start off clean every time - no config, and hence a different consumer group.

This is quite unlike a production environment with a more stable configuration

**Comment by mandy-chessell** [comment]
What is the proposed next step on this one?

**Comment by planetf1** [comment]
In my view we just need to ensure the current behaviour is adequately documented, both in the detailed docs for the kafka topic connector, but also ensure it is linked to from any info we have more generally that talks about the event bus/cohorts.

We could add a note in the understanding cohorts notebook.

We should add notes in our API def that (ie instance create) would result in launching a new topic listener to clarify the behaviour - though we don't have API docs to hook off currently.

When we write up anything about HA we should add it.

I've not reviewed the current docs in sufficient detail to consider exactly where.

I don't see the need for any code changes, other than the separate issue we still have open for the heartbeat

**Comment by planetf1** [comment]
@wbittles I'm wondering if it makes sense to combine this with your fixes for our kafka topic connector as your insight will result in better docs around how exactly egeria behaves with kafka - both normally and in error conditions, of which the above is a small note?

**Comment by wbittles** [comment]
@planetf1 I wouldn't hold up that fix for the extra documentation, however it makes perfect sense to provide that documentation as part of the new kafka connector

**Comment by planetf1** [comment]
Given our recent changes to perform some retry during bringup, and that in terms of getting messages the concern is only where a new server is added it will only get messages from that point (which seems entirely reasonable and obvious) it's difficult to see what specific action is to be taken for this issue. It was originally noticed since we didn't have retry and create the cluster clean every time, but in a real world scenario messages will be picked up once servers are configured - which is the normal case

More general architecture info may be useful but at this point I think closing this issue is the correct action. 

Please reopen with reasoning if you disagree
