### ISSUE TITLE
Potential npe in GovernanceZoneRESTServices

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2580]
I am looking at the use of instanceHandler code and can see this pattern in the code:

An example in GovernanceZoneRESTServices is:
 
" public VoidResponse createGovernanceZone(String          serverName,
                                             String          userId,
                                             ZoneRequestBody requestBody)
    {
        final String   methodName = "createGovernanceZone";

        RESTCallToken token = restCallLogger.logRESTCall(serverName, userId, methodName);

        VoidResponse response = new VoidResponse();
        OMRSAuditLog auditLog = null;

        try
        {
            if (requestBody != null)
            {
                auditLog = instanceHandler.getAuditLog(userId, serverName, methodName);
                GovernanceZoneHandler handler = instanceHandler.getGovernanceZoneHandler(userId, serverName, methodName);

                handler.createGovernanceZone(userId,
                                             requestBody.getQualifiedName(),
                                             requestBody.getDisplayName(),
                                             requestBody.getDescription(),
                                             requestBody.getCriteria(),
                                             requestBo
"

Going into the instanceHandler, I see the code can return null, if this happens  handler.createGovernanceZone call will npe. It looks like this code pattern might be used quite a lot.

 I originally thought we should never return null, so it only should return an object or throw exceptions. I think null means that it has not been initialized - so the fix should be in the caller to tolerate that null can be returned.

**Comment by davidradl** [comment]
I have labelled as a good first issue. It seems the fix would be to check for null , if it is null we need to work out what to return. It is probably a fix in one method.

**Comment by mandy-chessell** [comment]
I need a bit more information to understand how the NPE can occur.  Adding a test for null only masks the problem and does not resolve the root cause.  The call to retrieve either the auditLog or the instance for a service should never return null and we need to resolve why/how it is occuring.

I had a look at the code and I can not see what the problem is.

The code calls down to the `getInstanceForPlatform()` method in `OMAGServerPlatformInstanceMap`.  This has 2 major partitions - one where the server instance is not null and one where it is.  

In the case where the server instance is null (ie the server name is not known), the `handleBadServerName()` is called to throw the exception.  The `return null` at the bottom of the method is unreachable.  It is needed because Java does not know that `handleBadServerName()` always throws an exception.  Ugly, but not relevant to this issue.

I then went to look at the partition where server name is known and the instance exists.
There is code to throw `UserNotAuthorizedException` if the user is not allowed to access the service and then `getRegisteredService()` is called to get the actually handler for the service.

I looked in this method and again there are the security authorization checks and a test for null on the handle.  An exception is thrown if the handler is null (ie this server does not support this service).  Otherwise the 

Please would you supply more details because I am clearly missing something obvious.
Are we mapping server names or service names to null in the maps?

**Comment by davidradl** [comment]
@mandy-chessell I think the return null; "Ugly, but not relevant to this issue." was what misled me :-) ,  as you say it  could never be driven. I will close.

**Comment by mandy-chessell** [comment]
I'll add a comment to the code to say it is unreachable ...
