### ISSUE TITLE
Merge the different OMAG...ServiceRegistration with ServicdeRegistration

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#2593]
Raised to track issue raised as a  review comment from #2577 " eventual merge these different OMAG...ServiceRegistration classes into one? They're looking pretty identical now that the ServiceRegistration class they register is identical across all of them (?)"

**Comment by mandy-chessell** [comment]
Need to provide more information about what is to be merged - I have added comments to #2592

**Comment by mandy-chessell** [comment]
The service registration for access services and view services are different because they are very different types of services that are likely to develop in very different ways.  This means their statuses and the values in the registration need to be able to diverge.

Even today, they are different because access services have in/out topics and view services do not.  If view services are to be providing an async service it would be good not to call them the in and out topics because all of the documentation assumes they are attached to access services.

As such I do not think it is appropriate to merge them.
