### ISSUE TITLE
Guava introduced into Egeria build without discussion

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#2602]
Why is Guava needed?
Why was it introduced without discussion?

**Comment by GuyAckermans** [comment]
Unassigned myself because it is not used in my code and the dependency can be removed as far as my code is concerned. @DimitriosMaimaris ?

**Comment by DimitriosMaimaris** [comment]
I used it for Immutable Collections. Why what is the issue with it is Apache2 license?

**Comment by planetf1** [comment]
It is used explicitly in OLS - as @DimitriosMaimaris mentioned.

note that in addition even if we don't use directly, we may need to keep the version spec within `<dependencyManagement>`. Guava is used by testng & mockito (testing only), janusgraph & cassandra. We may need the transitive dependency declaration to get the right versions included to resolve clashes (unless this was only caused by OLS)
