### ISSUE TITLE
Questions concerning classify/reclassify/declassify events

### ISSUE THREAD

**Issue by GuyAckermans** [odpi/egeria#2631]
1.	Can the reclassify and declassify evens be extended to include the original classifications? Similar to the updated entity event.

2.	Does a classify event refer to a single classification added to an entity, or can the event contain multiple classifications?

3.	Does a reclassify event refer to a single classification or multiple? 

4.	Does a declassify event refer to a single classification or multiple? 

5.	Which event covers the change of a specific property within a classification? Should there be a new “updated classification” event?

6.	Where could we obtain a sample declassify event?

**Comment by mandy-chessell** [comment]
This is a good opportunity to broaden your skills in the repository services.

The file to begin in is the LocalOMRSMetadataCollection.  This is the metadata collection for the connector that wraps the real repository connector, intercepting and validating requests and also sending out events if there is no event mapper.

From this file you should be able to answer the questions above.

This is the link to the LocalOMRSMetadataCollection

https://github.com/odpi/egeria/blob/master/open-metadata-implementation/repository-services/repository-services-implementation/src/main/java/org/odpi/openmetadata/repositoryservices/localrepository/repositoryconnector/LocalOMRSMetadataCollection.java

**Comment by GuyAckermans** [comment]
Hi Mandy,

Thanks for the pointer. It seems that a classify/reclassify/declassy event always refers to only a single classification.  The only questions I have left are:

-Could we extend the reclassify event to also include the old entity? 
-Wouldn't "updatedEntityClassificationEvent" be more clear and consistent with the other names than "reclassifiedEntityEvent"?

**Comment by mandy-chessell** [comment]
Adding the old entity to the classification event would not be as helpful as you imagine because there is no guarantee that the asset lineage receives all events.  It may be down for a while for example - or the OLS may be down and miss events from the Asset Lineage OMAS.

Therefore the correct test is for the OLS to verify the updated entity against the information stored in OLS.  The old value of the entity from the repository is irrelevant.
(This is also true for the updateEntity event).

On the naming - yes, the name you suggest might be better but it is too late to change it.
