### ISSUE TITLE
Optimize lineage flow

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2660]
I've run through syncing from the DataStage proxy through to DE OMAS (and from there to OLS?) locally including the changes in #2647 to confirm things are still synced as expected, and it still appears to work fine; however, processing our very simple Coco Pharma examples still takes ~5 minutes from start to finish.

I'd like to work through how we can further optimize this end-to-end flow, as this feels to me like it still takes far too long to process. Extrapolating to 10 000 jobs of similar (trivial) complexity this would be ~1 full week of non-stop processing at the current speed...

**Comment by DimitriosMaimaris** [comment]
The running time for the Coco Pharma is exactly as you explaining and it is a big issue when we will have more complex jobs correct. I am totally with you it needs enhancement. First thing that can help in that direction is the remote connection to a gremlin server that has instances of Janusgraph instead of using Janusgraph embedded in the code.Which also means no use of BerkleyDb. This change I can say it can enhance speed up to 100 times with some tuning.

**Comment by grahamwallis** [comment]
@DimitriosMaimaris Do you have a write-up/test-code that shows the performance comparison and results?
