### ISSUE TITLE
Egeria 1.7 Release Notes

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#2873]
I have a few suggestions for inclusion in the 1.7 release notes.
Just trying to capture candidates at the moment. Some of the following are features; others are bug-fixes. 

In no particular order:
- JanusGraph updated to version 0.5.0, plus associated dependency updates
- Repository Explorer
- Case insensitive RepositoryHelper regex methods
- Graph Repository support for case-insensitive searches 
- Tighter validation when setting a property to a primitive value
- Correction of In-Memory repository getEntityNeighborhood() instance graph
- In-Memory repository findEntitiesByPropertyValue(), findRelationshipsByPropertyValue() check status filter
- In-Memory repository findEntitiesByPropertyValue() checks classification filter

**Comment by planetf1** [comment]
I am checking in the changes to make 1.7 the current release. I will check these in once the build verification completes. The release is likely to ship in the next day or two.

Please can you make any additional updates for the release notes - since this is in master it does not affect release packaging

Note that Janusgraph 0.5.0  & repository explorer were in the 1.6 release.

@mandy-chessell If there is anything yet documentable for valid values/RDM could you also add notes please?

**Comment by planetf1** [comment]
1.7 has now shipped. removing milestone. You can still update release notes if required, but if you want any changes to the release abstract on GitHub please cc: me.

**Comment by planetf1** [comment]
1.7 has gone so closing
