### ISSUE TITLE
Need to add any new packages in a release manually to JCenter

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#2917]
I just noticed while trying to stage release for one of the connector repositories that the new `audit-log-framework` package (I think first available in the v1.6 release?) was not available in Maven Central.  It seems that there is an extra manual step we need to take in Bintray to first add any new package to JCenter before there is even an option to sync it to Maven Central.

(As a result any automation we had on Maven Central syncing is not handling these net-new packages.)

I've manually resolved this for the `audit-log-framework` for v1.6, but not sure if there are others that we need to take the same manual action against / any easy way to identify them?

Flagging as a reminder for future releases as well...

**Comment by planetf1** [comment]
The current scripts should throw an error if a package is in bintray and can't be synced to maven central (as would be the case here). Then we need to add manually

The last run was at https://dev.azure.com/ODPi/Egeria/_releaseProgress?_a=release-environment-logs&releaseId=131&environmentId=381

My attempted refactor for the last release lost the error, and so we got:
```
2020-04-09T07:13:57.3499730Z STARTING - Sync audit-log-framework:1.6
2020-04-09T07:13:57.5455946Z RESULT - Sync audit-log-framework:1.6 = {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
```

Checking, we have this issue with:
open-metadata-ut:1.6
stewardship-engine-services-api:1.6
stewardship-engine-services-client:1.6
stewardship-engine-services-spring:1.6

I'll do the others now, and then in this issue correct the sync job (for 1.7), though just for error checking (which is why I missed it - my bad). I've looked before to see if we can sync manually but not clear we can with the api. Any tips @bramwelt

**Comment by planetf1** [comment]
I've added open-metadata-ut -- which wouldn't really impact anyone.

Also , just as in 1.5, the stewardship-engine-services artifacts are incorrect. They do not yet contain code, so fail validation. @mandy-chessell is aware of this, and the intent was to update them in a future release (perhaps 1.6). This also means the 'partial fix' I suggested above to get the process to fail, may be inadvisable for now... and close inspection of the logs may be needed short term.

Ideally we should not permit incomplete/incorrectly formed artifacts, or have a way to exclude them from upload. AND address the automatic addition to JCenter....

Will leave open for us to think through this.

Thanks for spotting the missing ALF artifact

**Comment by planetf1** [comment]
I added a note in the 1.7 release issue (just opened) https://github.com/odpi/egeria/issues/2923 

That template is a good example (IMO!) for an issue template  #2880 - I've tagged it to discuss in the call tomorrow. At the same time I would at a minimum create a blank issue template - we can in parallel perhaps refine. Discussion over there?

**Comment by planetf1** [comment]
We didn't have any challenges in this release. I will summarise the overall challenges in the release process in an issue in the 1.8 timeframe to see what we can improve.

**Comment by planetf1** [comment]
Have raised with LF team -> https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-19687

**Comment by planetf1** [comment]
will track in #3914
