### ISSUE TITLE
Initial Load flow for Lineage

### ISSUE THREAD

**Issue by DimitriosMaimaris** [odpi/egeria#2924]
Hello,

As we have discussed in a functionality call we need to find a way to load existing  processes for lineage when Open Lineage Services start for the first time. This is the outcome from the design session we had.

![Copy of Initial Load (2)](https://user-images.githubusercontent.com/50103684/79230884-8bc59580-7e65-11ea-89dd-37d93fd5b394.png)

First time it will start it should search based on type. So it should search for all processes that it can find in the cohort. If processes are found it will get the context for the Process and all the attached external types that related to that process. In case that it does not find anything we would expect that the relevant DataEngineProxy will try create the processes that have been found from an ETL tool to the Egeria local repository and this will trigger OMRS events that will be picked up by Asset Lineage and processes accordingly to provide lineage to Open Lineage Services. @cmgrote I would like to have your input on this is this correct assumption.

**Comment by cmgrote** [comment]
> First time it will start it should search based on type.

Just to check my understanding: I thought we'd also discussed the "scanner" approach where there was a constantly-running background thread that queries for processes.  Is this what we mean by the "search based on type"?

> So it should search for all processes that it can find in the cohort. If processes are found it will get the context for the Process and all the attached external types that related to that process.

Per above comment on the "scanner" approach, indeed I would expect the scanner logic to "branch out" any processes it finds to all of their related instances (assets, schema types, ports, etc), and to recursively do these relationship traversals up to some logical ending point to build up the necessary context for lineage.

> In case that it does not find anything we would expect that the relevant DataEngineProxy will try create the processes that have been found from an ETL tool to the Egeria local repository and this will trigger OMRS events that will be picked up by Asset Lineage and processes accordingly to provide lineage to Open Lineage Services.

I think this is simply a parallel thread that's going on at the same time the scanner is running, rather than an either / or approach.  Certainly I can't imagine there would be any trigger to the DataEngineProxy if nothing is found by the scanner -- that would require the scanner knowing what it does not know in order to know when to trigger something else...  This parallel DataEngineProxy thread would indeed be responsible for picking up any processes from the ETL tool(s) it proxies and storing them into an Egeria repository as externally-homed instances.  This would in turn trigger OMRS events that _could_ be picked up by Asset Lineage OMAS and translated along to the Open Lineage Services.

However, by storing the information into an Egeria repository (that is part of the cohort), the "scanner" above would also then be capable of picking them up from that Egeria repository during its scanning.

(Hence why I think we also suggested doing a quick check on the "version" of anything that's received vs what's stored already to see if an update is necessary before calculating the diffs and applying any updates -- it's possible (highly likely, even) you'd get the same information, at the same "version", through multiple channels.)

**Comment by DimitriosMaimaris** [comment]
Based on the latest discussions we had I updated the diagram as can be seen below.
![Copy of Initial Load (2) (1)](https://user-images.githubusercontent.com/50103684/79848458-64208100-83c1-11ea-877b-e3e9cfb28d0b.png)

@cmgrote if this aligned with the points we made please confirm so we can move forward by implementing it.

**Comment by cmgrote** [comment]
Initial Load still looks the same as your original diagram (or did I miss something?)

I also think that:

- We probably need to at least illustrate that the two independent threads are operating as such (at the moment I just see one activation box on Open Lineage Services, which makes it all look like a single thread / activity).
- The `getContextNonExistingEntities` I would expect could still end up querying back through the Enterprise Connector to underlying repositories, if the context is not already available in Asset Lineage OMAS (?)
- There's in reality another parallel process that's not illustrated at all here, which is the data engine proxy activity...  That doesn't occur via the repository, and in the case of DataStage will be the only source of _Process_ information (you won't get that from IGC)...  Unless by "Repository" in these diagrams you mean a persistent repository for Egeria itself (like the graph repo)?

**Comment by cmgrote** [comment]
Updated discussion: we think that we can use a single approach across both the initial load and subsequent "scanning" as follows:

- On startup, the OLS will look for any previously-persisted date & time of queries it has run against AL OMAS
- If none are found, OLS will persist the current date and time and then query the AL OMAS for relevant objects that have either been created or updated between `null` (or epoch 0 time) up to the current date and time
- (AL OMAS queries to the cohort for `SemanticAssignment` and `LineageMapping` relationship changes that have occurred on or after that time (0 <= `createTime` / `updateTime` <= current date and time)
- As part of querying the cohort, AL OMAS should cache information about the context it builds up for each object (avoiding re-retrieving the same table, schema, database, host information for all the columns in the same table, for example).
- When OLS next runs this "scan" process, instead of using the `null` (epoch 0) starting point, it uses the date and time that were persisted at its last execution

This covers initial load (OLS starting up for the very first time in an existing cohort).  We then also need to cover the scenario where a new repository joins the cohort -- since this could have metadata whose creation / updates pre-date the time and date offset stored for the cohort in general within OLS.  For this we need to:

- Listen to any new registration events
- Based on the registration events, submit a query to AL OMAS that causes the query to the cohort to be done based on the new metadata collection id (+ a "new" offset of `null` / epoch 0)
- We can either then manage these metadata-collection-id-specific date & time "offsets" going forward, or try to consolidate this back into a single across-the-cohort offset after the "initial load" of this new metadata collection is completed (?)

(Note: we probably need to take the various bullets above and create some more granular issues to track their progress...)

**Comment by cmgrote** [comment]
Re-opening, as I assume this is still needed (was auto-closed) ?
