### ISSUE TITLE
Optimisation options for Enterprise Connector

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#3058]
We discussed another possible (configurable) optimisation strategy to implement for the Enterprise Connector:

- Prefer to return results from the local repository -- these results are all that are synchronously used to respond to the request to the Enterprise Connector
- Asynchronously trigger (in parallel) background requests out to the cohort to refresh the results of the same query from those other members of the cohort
- If there are no results from the local repository, then run the federated query and return those results (so still take a hit on a miss against the local repository, but next queries for this same info would then hit the first condition in this list)

This gives us eventual consistency for the Enterprise Connector's local repository, but ensures that we do not always need to wait on all results from all cohort members to provide a synchronous response from the Enterprise Connector.  (That is, it should significantly improve performance and give more reliable performance characteristics to the Enterprise Connector in general wrt searches.)

**Comment by grahamwallis** [comment]
I'd like to add an observation to this issue:

This scenario may have arisen because I had got my cohort into an unusual state of registrations, but I saw the following.
There were two servers with repositories - one of them running and one not:
Repo1 - was running but did not contain the entity I was looking for,
Repo2 - was not running but did contain the entity I was looking for. 
I issued an enterprise query, and would have maybe expected to get an exception reporting  ENTITY_NOT_KNOWN from Repo1. Instead I saw an exception saying that Repo2 was not running. Although they are both 'empty' results I would have thought that the ENTITY_NOT_KNOWN from Repo1 is the more interesting and authoritative of the two.

**Comment by planetf1** [comment]
I think mapping federated responses is tricky. In that scenario, the user requested an entity. The system knows it exists, but just could not retrieve it. Therefore I would have expected a response that mirrors that. It absolutely is known, just temporarily out of reach. I don't like the server down exception particularly, but it probably is closer to the truth, since if it was up you'd have your entity...

I'd maybe like something like ENTITY_UNREACHABLE ?

This sounds like an interesting area for a design review

**Comment by grahamwallis** [comment]
@planetf1 - I don't think it's possible to have an expectation as to whether the entity exists or not, prior to the query. Knowing the entity GUID doesn't help the user/system to known where to expect to find the entity. So I disagree that "the system knows it exists" and with the owning repository server (hopefully temporarily) stopped it cannot know. I think the best one can do in that situation would be to say - 'in all the places I could look there was no such entity' and this particular case that would be EntityNotKnown from Repo2.

**Comment by planetf1** [comment]
In that case I agree - I'd misinterpreted  - though I wonder if we could also flag that some servers didn't respond. We have a partial result - and know that
