### ISSUE TITLE
 Found by me defects and bug

### ISSUE THREAD

**Issue by immmus** [odpi/egeria#3060]
Hi!

I noticed that when I make a request to update glossary, term, etc., without making a nothing change, the object is updated, the version and date of the update are updated, although the object is identical to the previous one. The same situation is observed with soft removal.

When you delete an object, its version changes and when you restore an object, it also changes, that is, at the output we get +2 version although the object did not change, but only went to the basket.

I also found an error with getting all the categories that I described and fixed in https://github.com/odpi/egeria/pull/3050. This bug is present in both master and 1.8 and 1.7 versions.  All of the above shortcomings I found when working with subjectArea.

Also in the master branch there was a problem with embedded kafka. In 1.7 release this problem not found.

Problem appears at this moment:

```
 2020 test Startup OCF-KAFKA-TOPIC-CONNECTOR-0001 Connecting to Apache Kafka Topic egeriaTopics.server.test.omas.assetlineage.outTopic with a server identifier of 2fabba15-9284-42d6-8b88-ff7c10761cd0
 2020 test Startup OCF-KAFKA-TOPIC_CONNECTOR-00015 The local server is attempting to connect to Kafka, attempt 1
 2020 test Startup OCF-KAFKA-TOPIC_CONNECTOR-00015 The local server is attempting to connect to Kafka, attempt 2
```

**Comment by mandy-chessell** [comment]
Hi Ilya,
The versioning behaviour that you are seeing is correct.  It is important that every change increments the version number so we can sequence events effectively if they are jumbled in the event bus.

The kafka logic has just changed so that if kafka is down, the server waits for a while, retrying the connection a number of times.  If kafka does not come up in time, the server should fail to start.  If you don't want event support then reconfigure OMAS services to define null in and out topics in the configuration document.

I'll leave David to comment on the Categories issue :)

**Comment by planetf1** [comment]
> The kafka logic has just changed so that if kafka is down, the server waits for a while, retrying the connection a number of times. If kafka does not come up in time, the server should fail to start. If you don't want event support then reconfigure OMAS services to define null in and out

And to add to this Ilya .. see #3021 which is a bug whereby the server unfortunately does start - it should not. We found this when testing the retry

**Comment by immmus** [comment]
Thank you for your responses). I can close this issue?
