### ISSUE TITLE
Split single cohort topic into multiple

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#3144]
@grahamwallis @mandy-chessell and I had some email-based discussion on the potential of the cohort topic being "flooded" by events in certain scenarios, which given our single-topic approach to date would mean that some events would end up queued up behind a long list of other events and could therefore face an unnecessarily significant delay before being processed.

From our discussion, we'd like to suggest splitting the current single cohort topic into at least 2 (probably 3) topics, as follows:

1. Instance events
1. TypeDef events
1. Registry events (may be combined with (2) for simplicity, though given increasing volume of (2) probably makes sense to already separate out?)

**Comment by cmgrote** [comment]
Suggesting that we try to get this into v2.0, as I believe it would be a breaking change (not backwards-compatible), at least not without some overhead in various places catering for both the single-topic and multi-topic setups (?)

**Comment by grahamwallis** [comment]
Agreed.
As an adjunct to this we should augment our KafkaOpenMetadataEventConsumer so that if it gets an exception from commitSync() it should at least log it - and preferably take some action on it if appropriate. Currently it seems to implicitly throw the exception to the rebalance operation (in Kafka) and I think Kafka throws another exception back in response to our poll of the topic. By logging we would at least find out why the commitSync has failed.

**Comment by planetf1** [comment]
Could another option be to create additional topics for let's say 'high' priority
* In our topic connector we could always listen to both regular & high, and aim to process any on high first
* we could have a map of events to priority
* A configuration could control if we SEND any messages on the high priority queue - we would only tell the admin to do this if all cohort members are at a suitable version (ie 2.0 or above) - we might be able to do this dynamically

This would work with explicit instance/typedef/registry also

ie.. I think we could make it non breaking if we wanted?

One concern is we have a lot of suggestions for 2.0 and may have too many to get in at once?

**Comment by cmgrote** [comment]
Approach discussed on Thursday call:

- Leave existing cohort topic there for backwards compatibility -- with all events
- Add 3 new topics: one for instances, one for typedefs, one for registry events
- Rework event managers to work across both sets of topics (ie. cover new topics as well as original)
- Enterprise event manager should only reconfigure the enterprise connectors when a registration event indicates something has changed

We could dynamically decide whether we need to put events onto the old topic or not, based on the version of the members of the cohort that are registering.

**Comment by mandy-chessell** [comment]
Still needed

**Comment by lpalashevski** [comment]
Still relevant as discussed on the last community call

**Comment by mandy-chessell** [comment]
There is renewed interest in this issue due to the focus on HA operation for OMAG Servers where there are multiple replicas (instances) of the same server running on different platforms.  In this environment we need registry events to be picked up by each active replica of a server where as the other event types should only be picked up by one of the replicates.  To do this, the servers need to register with the topic using different settings of the consumer group id.  The simplest way to do this is to have 3 topics - one for each type of event.

**Comment by cmgrote** [comment]
I think this is complete now, and released in 2.11 (@mandy-chessell please confirm by closing issue, if so 🙏 )

**Comment by planetf1** [comment]
@mandy-chessell Is this now implemented as the default for v3 as per https://egeria-project.org/open-metadata-implementation/admin-services/docs/user/configuring-registration-to-a-cohort.html ?

**Comment by mandy-chessell** [comment]
not yet

**Comment by mandy-chessell** [comment]
@planetf1 Three chort topics is the default for V3.
