### ISSUE TITLE
GlossaryView OMAS navigation add search capability and endpoints.

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#3153]
**Issue:**
GlossaryCategory without Glossary are not reachable through the API.
GlossaryTerms without GlossaryCategory Glossary  are not reachable through the API.

Basically if there is no Glossary in the repos no term and/or category is reachable.

**Proposal solution:**
Add endpoint method for all the GlossaryCategory.
Add endpoint method for all the GlossaryTerms.

Add filtering by name / displayName , description, qualified name (not sure how useful would be)

**Comment by immmus** [comment]
> **Issue:**
> GlossaryCategory without Glossary are not reachable through the API.
> GlossaryTerms without GlossaryCategory Glossary are not reachable through the API.
> 
> Basically if there is no Glossary in the repos no term and/or category is reachable.
> 
> **Proposal solution:**
> Add endpoint method for all the GlossaryCategory.
> Add endpoint method for all the GlossaryTerms.
> 
> Add filtering by name / displayName , description, qualified name (not sure how useful would be)

If I understand correctly, then GlossaryCategory without a Glossary and GlossaryCategory without a Glossary cannot because it their hierarchy and they depend on each other. But endpoint method for all the GlossaryCategory and all GlossaryTerms make necessary. 

If by filtering you mean a search by the necessary properties, then such a change will need to be made for the getAllGlossaries method as well. I can try to implement this.

**Comment by immmus** [comment]
Hi @bogdan-sava  
 While I can offer you endpoints without filtering - https://github.com/odpi/egeria/pull/3169

**Comment by bogdan-sava** [comment]
@immmus. Thanks, 
Yes that's fine.

**Comment by immmus** [comment]
> @immmus. Thanks,
> Yes that's fine.

Well), you are welcome)
