### ISSUE TITLE
Issues in Admin View services 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3177]
While working on #3176 I fixed up some errors in the admin view services.  The create all view services works and create an individual view service works.

Outstanding issues to be addressed by this issue:
1- retrieving the omag configuration does not contain the list of view services - even though it is in the config file. As the omag config file is now secure - using this API is the only way to  obtain the config.
2- I would like to identify and create a postman collection for the view services in line with the 
access services.   
3- create all view services command does not produce usable view services as the remote metadata service and url have not been specified. I need to investigate whether the view service options can be used to send these through.

**Comment by mandy-chessell** [comment]
The postman collection for the server configuration is here: https://github.com/odpi/egeria/blob/master/open-metadata-implementation/admin-services/Egeria-admin-services-server-configuration.postman_collection.json

**Comment by mandy-chessell** [comment]
Fixes added as part of #3707

**Comment by grahamwallis** [comment]
Just for historical interest... the create all view services method was subsequently removed in #3848, as described in issue #3836

**Comment by mandy-chessell** [comment]
Why was this method removed?  Why would you not want all view services active on the same view serveer talking to the same metadata server?

**Comment by planetf1** [comment]
Presumably different view services have different requirements in terms of what they need to be running on the metadata server -- ie which OMAS? We also don't have a way of enabling all OMASs so the approach for view services seems consistent?

**Comment by grahamwallis** [comment]
"Why was this method removed? " - please see issue #3836 (part 3). It's not about which server a view service communicates with, it's that the configuration for an integration view service and solution view service have different parameters, so unlike access services that use accessServiceOptions, we would have to leave the view services to default and it's not clear how to default the resource endpoints for an integration view service. The point in issue #3836 remains open, but until we have a design for how to enable all view services, I removed the implementation as it is otherwise misleading.

"... different view services have different requirements in terms of what they need to be running on the metadata server -- ie which OMAS? " - almost, but it's not about the OMAS for an integration view service. 

"We also don't have a way of enabling all OMASs " - actually we do - you can POST to the .../access-services URI and all access services will be enabled with a single set of accessServiceOptions. This doesn't (yet) make sense for some view services, as described above and in issue #3836.
