### ISSUE TITLE
egeria-ui --server.servlet.context-path option

### ISSUE THREAD

**Issue by zoranid** [odpi/egeria#3181]
In case user wants to specify --server.servlet.context-path option, ui.yaml needs to be modified to modify container's entrypoint command.  Probably better would be to propagate  this into values.yaml as an option, so user would need just to specify an optional correct value in values.yaml. The change needs to be reflected in ingress.yaml as well.

**Comment by planetf1** [comment]
@sarbull This was originally brought up in relation to hosting the spring based UI. 
Given the refactoring that will occur in that UI shortly I think it's best you evaluate if any changes are needed in the k8s deployment after those changes are made specific to this issue

**Comment by sarbull** [comment]
@planetf1 we'll have to see at PR, i think some java spring ENV var will be removed (the required zuul ones), after this the backend it's all by itself with **no link to the UI**, the UI will be refactored so that it knows about the backend with the default deployment strategy we discussed by adding that ENV file which will provide minimal info for the THEME and API_URL and maybe other properties..

other than this, having the UI completely separated from the backend, anyone can decide what fits best for their needs as deployment

**Comment by planetf1** [comment]
Given the refactoring it may be appropriate to close this issue now, and just ensure relevant docs are in place for deployment after the refactoring -
