### ISSUE TITLE
(Re?)Design where config information for virtualizer should sit

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#319]
In the PR for the virtualizer review
https://github.com/odpi/egeria/pull/316

It was noted that a varity of configuration information is kept in an application properties file

...-metadata-demos/virtual-data-connector/virtualizer/src/main/resources/application.properties

This includes gaian endpoint, kafka endpoint etc.

Opening to review configuration in more detail -- and noting that we will have similar questions with other components including the UI, tagsync etc.

**Comment by mandy-chessell** [comment]
Egeria's configuration needs to be managed through a connector.  This is because in cloud-based or virtualised environments the file system is continually wiped and so it can not be used for persistent storage.   The connector can be replaced, allowing the storage of the properties to be redirected to safer persistence locations.

The design we have today is only currently implemented for the OMRS/OMAS services but needs to be extended for the governance daemons such as the virtualizer (and governance engine sync) along with the UI.  The only exception is configuration used directly by Spring which can not be set any other way.  Spring is also replaceable (for example IBM uses liberty/microservices in the cloud) so I am not so concerned with that.

Baiscally the admin services are responsible for building config documents for any Egeria server.  This may be a virtualizer server, repository proxy, etc.  When a server is initialized, it is passed a config document and initializes the requested services.  This means we may have the virtualizer running in the same server as the OMASs/OMRS or a different server, depending on how the configuration documents are defined.

The initial commit of the virtualizer just brings the virtualizer into Egeria so it can use the server chassis.  What need to happen next is:

- a bean structure for the virtualizer needs to be added to the server config bean.  It should contain the properties needed by the virtualizer.
- a new Spring resource and REST API should be added to the admin services to be able to manage the virtualizer properties.
- the initialize and terminate methods for the admin services need to detect the presence of the virtualizer config and initialize the virtualizer service with the appropriate config and terminate the service are requested.
- the virtualizer code needs to be able to work with the config passed from admin services.

**Comment by mandy-chessell** [comment]
In terms of the virtualizer code, there should be a new maven module for the server "cartridge" of the virtualizer.   It is located in egeria/governance-servers and called information-view-generator. This provides the code that the admin services call to intialize the virtualizer if it is configured in the server's configuration document and sets up the Kafka consumer to listen for events from the Egeria Information View OMAS.  It also provides any Spring resources for any REST APIs (in a separate spring submodule).

The virtualizer supports 2 types of connectors:
- the connector reponsible for configuring views in the IV platform (eg Gaian or BigSQL)
- the connector reponsible for any transformation between real data sources and the views.

The definition of the connector API and base class is put in the api submodule of information-view-sync and the specific implementations go into their own modules under egeria/adapters/open-connectors/governance-daemon-connectors/view-generator-connectors.

**Comment by planetf1** [comment]
@ruxandraRosu passing this over in case there's any additional actions you wish to take - or else close?

**Comment by innerTide** [comment]
Hi, Nigel. The new version of virtualizer as an OMAG service has been merged to master. The configuration is now stored at the generated file via restful API. This issue can be closed now. :)
