### ISSUE TITLE
Implement external authentication via user supplied custom side car authenticator

### ISSUE THREAD

**Issue by zoranid** [odpi/egeria#3270]
```
 pod
    egeria-ui           custom auth
    container ------->  container
              rest
```
egeria-ui would make a call to a side car custom auth container container in following form
```
curl --header "Content-Type: application/json" --request POST --data '{"username":"zoran@example","password":"xxxxxx"}' http://containername:4567/auth
```
readiness could be tested like this 
```
curl http://containername:4567/hello 
```

**Comment by bogdan-sava** [comment]
right now we have 2 authentication ways:
1. LDAP ( )
2. against a H2 database prepopulated on startup. This used for demo purpose.

The plan is to move out H2 authentication and place it in classpath ( lib folder ) if you wanna use it, instead of default LDAP.

In order to have a custom authentication you'll need to create such a dependency and place it in the lib folder.

**Comment by zoranid** [comment]
Would I be able to do that without re-building a container myself?

**Comment by bogdan-sava** [comment]
Hmmm.
I don't know what container you mean.
Definitely you should have another UI refactored version which means yes, you should rebuild the container.
The way your custom plug-in dependency reach the lib folder may have several solutions.

**Comment by zoranid** [comment]
Either way it should be ok.  Lib flexibility would be ok.

**Comment by zoranid** [comment]
We can use pretty much any solution you suggest. Thanks.
