### ISSUE TITLE
Server-Side Request Forgery possible from UI 

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#3272]
Server-Side Request Forgery ('SSRF') occurs when an attacker can initiate a network connection made by the affected application server. The type of network connection may depend on the specific part of the URI that the attacker can take control on the web application requests.

It is possible to perform port scanning of another host by taking advantage of “serverURLRoot” JSON parameter for example in the endpoint "/api/types/typeExplorer".  

The UI application will make request to the requested destination server and return (expose) internal communication details to the requestor. For example if requested port is not open will return 400 error

```{"httpStatusCode":400,"exceptionText":"The repository could not be reached, please check the server name and URL root and verify that the server is running ","typeExplorer":null}```

however if different open port is used, then the UI server is responding by revealing extra details on the status of the remote call:

```HTTP/1.0 504 Gateway Time-out
Cache-Control: no-cache
Connection: close
Content-Type: text/html
<html><body><h1> 
504 Gateway Time-out</h1>
 
The server didn't respond in time
</body></html>```

This behaviour allows the attackers to scan ports of other hosts through the OpenMetaData application.

**Comment by lpalashevski** [comment]
Potential solutions suggested on the last community call:

- White listing destination servers and performing only allowed calls to well-known backend destinations
- Enhance error hanging for all calls that do this or similar backend operations and obscure the reason for the communication failure (keep it only to the technical logging level and respond to the requestor with generic internal error message).

**Comment by planetf1** [comment]
I think this is currently being worked on by @grahamwallis  - assigning

**Comment by grahamwallis** [comment]
Update and questions: 

This is now fixed for the Rex, Tex and Dino interfaces via the presentation-server. The current solution there uses configuration of resource endpoints in the configuration of each view service. The longer term proposal is that resource endpoints should be stored in a repository (instead of being configured). This changes has been discussed and it was agreed that it may be worked on in the new year.

No changes have yet been made to Rex and Tex in the Polymer based spring-based ui-chassis interface. 

My questions:

(I am not making any recommendations here - just laying out options and seeking opinions.)

* Is it the intention to continue to have Rex and Tex interfaces in the ui-chassis interface? The alternative would be to rely on the presentation-server interface for these functions. If Rex and Tex were removed from the ui-chassis this issue is already fixed, and only requires the future migration from configuration to repository storage of endpoints.

* If Rex and Tex are still wanted in the ui-chassis, should we work on a stop-gap solution that uses configuration, prior to the move to repository-based resource endpoints? My guess is that any such configuration would probably go into application.properties, but this may be incorrect. We would need to add the configuration and modify the RepositoryExplorerController and TypeExplorerController to retrieve them and deliver them via a new REST API. We would also modify the browser-based code to invoke the new API and present lists of available platforms and servers. The server-side code would also need to be updated to not accept URLs, but to only accept platformName and to resolve the appropriate URL on a per-request basis - this is what the presentation-server interfaces do.

* If Rex and Tex are still wanted in the ui-chassis, should we instead wait until the resource endpoints are stored in a repository and then implement this? This would require similar changes to those listed above (for endpoint retrieval, display and name->URL resolution) but would avoid the intermediate stage of adding configuration to application.properties prior to the move to repository storage.

All comments and suggestions welcome. I do not have a strong preference on the above, but a slight concern about the middle option due to the introduction of configuration that is subsequently removed in favour of the repository solution. That is what has happened with the presentation-server interfaces but only due to unfortunate timing; we had already developed the configured solution prior to the discussion about repository storage.

**Comment by planetf1** [comment]
SInce we now have tex/rex/dino being maintained in presentation server, my preference would be for #1 above

The only caveat is to
 - ensure we document the change in release notes (both UIs are in dev status in any case)
 - ensure that we always aim to keep the current presentation server working - ie we're far enough down the dev path (I think we are)
 - we keep the docker containers/environments working so there's an easy route to entry for using P.S.

I worry that 2, 3 leads to more ongoing work to support in both places?

The purpose of the P.S. UIs are more focussed on integrators/developers whilst the polymer UI is more focussed on business users at this time?

**Comment by mandy-chessell** [comment]
Lets discuss on one of the community calls this week

**Comment by mstrelchuk** [comment]
We do have rex/tex in Egeria UI (polymer based) currently and at least for coming few months, therefore the preference is for option 2. 
As discussed during the call, the topic of UIs will be covered in December workshop.

**Comment by grahamwallis** [comment]
Probably still relevant
