### ISSUE TITLE
The Subject Area API will be enhanced to map all of the OMRS Exceptions that the API can get to Subject area Exceptions. 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3273]
As a follow on issue from pr #3245. The Subject Area API will be enhanced to map all of the OMRS Exceptions that the API can get to Subject area Exceptions. The API should be able to programmatically get the inserts from the Exception. 

Note that Subject Area PropertyServerException does not appear to be used currently - buts is on the client API.  I have suggested some mappings as follows.  

| OMRS Exception | SA OMAS ExceptionDescription | parameters | proposed FVT test | notes |
| ----------------- | ----------- | ----------------- | ----------- | ----------------- |
| ClassificationErrorException.java | ClassificationErrorException.java | invalid classification | Add an invalid classification| the subject area omas does not handle this yet |
| EntityConflictException.java | EntityConflictException.java | The old code did not handle this but the new code |
| EntityNotDeletedException.java | EntityNotDeletedException.java | guid | | |
| EntityNotKnownException.java | EntityNotKnownException.java | guid | send in an invalid guid | |
| EntityProxyOnlyException.java | EntityProxyOnlyException.java | guid | | |
| FunctionNotSupportedException.java | | | Not be easily testable in an FVT -unless we start a repository that does not support some functions |
| HomeEntityException.java | PropertyServerException | | |
| HomeRelationshipException.java | PropertyServerException | | |
| InvalidEntityException.java | InvalidEntityException.java | guid | | |
| InvalidParameterException.java | InvalidParameterException.java | invalid parameter names and values | try to target the code that sets this. | |
| InvalidRelationshipException.java | InvalidRelationshipException.java | guid | | |
| OMRSRuntimeException.java | PropertyServerException | | | |
| PagingErrorException.java | PropertyServerException
| PropertyErrorException.java | PropertyServerException
| RelationshipConflictException.java | RelationshipConflictException.java | guid | send in an invalid guid | |
| RelationshipNotDeletedException.java | RelationshipNotDeletedException.java | guid | | |
| RelationshipNotKnownException.java | RelationshipNotKnownException.java | guid | send in an invalid guid | |
| RepositoryErrorException.java | PropertyServerException | | | |
| StatusNotSupportedException.java | StatusNotSupportedException.java | invalid status | send in an invalid status | |
| UserNotAuthorizedException.java | UserNotAuthorizedException.java | userid | send in an null userid | |

Once we agree these - we should look to enhance the FVT as per the suggestions in the table and  document this table in the subject area design documentation.

**Comment by mandy-chessell** [comment]
Are all of these exceptions needed for the client - for example, can they perform a different action based on each exception?

A separate exception is only needed if the client should take a separate path.  It is not needed to distinguish between different types of errors.  This is handled by the message contents that go in the exception.

Other OMASs use just 3 exceptions:
* Invalid parameter - the client is in eror and has passed invalid values - client needs fixing
* user not supported - the client is accessing a resource that it should not - change resource it is using, change access controls for resource etc  ...
* Property server error - Server has either got a bug in it, been set up incorrectly or operated incorrectly.  Talk to operations team to get it resolved.

The OMRS exceptions are very fine-grained, designed for use by the internals of Egeria.  If they are returned to an OMAS it may be that there is a bug in the OMAS?   Is a straight forward mapping possible?

Finally, the SA exception names should reflect the concepts in the SA interface - I thought it used concepts such as Nodes and Lines rather than Entities and Releationships?

**Comment by immmus** [comment]
> Are all of these exceptions needed for the client - for example, can they perform a different action based on each exception?
> 
> A separate exception is only needed if the client should take a separate path. It is not needed to distinguish between different types of errors. This is handled by the message contents that go in the exception.
> 
> Other OMASs use just 3 exceptions:
> 
> * Invalid parameter - the client is in eror and has passed invalid values - client needs fixing
> * user not supported - the client is accessing a resource that it should not - change resource it is using, change access controls for resource etc  ...
> * Property server error - Server has either got a bug in it, been set up incorrectly or operated incorrectly.  Talk to operations team to get it resolved.
> 
> The OMRS exceptions are very fine-grained, designed for use by the internals of Egeria. If they are returned to an OMAS it may be that there is a bug in the OMAS? Is a straight forward mapping possible?
> 
> Finally, the SA exception names should reflect the concepts in the SA interface - I thought it used concepts such as Nodes and Lines rather than Entities and Releationships?

I agree. That is why I minimized the number of exceptions, that is, in the three of which you speak.

**Comment by davidradl** [comment]
@immmus @mandy-chessell, I agree with the principles. I was thinking that:
-  it is useful to know if an Entity or Relationship is not found, it would be useful to indicate that explicitly it was not some other server error.    
- I was thinking that if something was not deleted then caller would want to know so as to still treat that item as active.  
- I agree that for consistency,  all the references to entity should be node and all the references to relationships should be lines.  Also the getRelationships APIs should be getLines. Good spot :-)  
- currently nothing is mapped to PropertyServerExceptions, so the previous fix regresses the API in this area.  
- I thought it useful to indicate function not supported to the user  / client so they do not immediately try this operation again. They could choose to retry at some later date if the cohort had a repository that did support that function.   
- On reflection InvalidRelationshipException.java, RelationshipConflictException.java and the same of entities could be PropertyServerExceptions. Also EntityProxyOnlyException.java should be propertyExceptions. I hope that all other other Exceptions I mention would be meaningly and could be acted on in the client app / UI.

**Comment by immmus** [comment]
> @immmus @mandy-chessell, I agree with the principles. I was thinking that:
> 
> * it is useful to know if an Entity or Relationship is not found, it would be useful to indicate that explicitly it was not some other server error.
> * I was thinking that if something was not deleted then caller would want to know so as to still treat that item as active.
> * I agree that for consistency,  all the references to entity should be node and all the references to relationships should be lines.  Also the getRelationships APIs should be getLines. Good spot :-)
> * currently nothing is mapped to PropertyServerExceptions, so the previous fix regresses the API in this area.
> * I thought it useful to indicate function not supported to the user  / client so they do not immediately try this operation again. They could choose to retry at some later date if the cohort had a repository that did support that function.
> * On reflection InvalidRelationshipException.java, RelationshipConflictException.java and the same of entities could be PropertyServerExceptions. Also EntityProxyOnlyException.java should be propertyServerExceptions. I hope that all the other Exceptions I mention would be meaningful and could be acted on in the client app / UI.

In this case, we will again return to processing five-story "try-catch" constructions, which is not good, and we will also force the client to process a lot of errors. :(

If you really necessary all these exceptions. I propose to slightly modify the handling and scrolling of exceptions at the RepositoryHelper level so that us do not have to change the API at all other levels. At the same time, leaving 3 exceptions as it is at the moment. 
Just at the moment of a Throwable exception, we will check whether this error is the successor of OCFCheckedExceptionBase and if so, we will pull out all the information we need from it and then throw it as a PropertyServerException, but for unknown errors we will leave the current implementation. 
This will be the cleanest solution possible. Otherwise, it is just over-enginering. After all, this will not help much to the user, but for us in the future in the further support it will simply add some trouble. The number of exceptions thrown for the client is generally better to reduce to one.

**Comment by davidradl** [comment]
@immmus I do not think it is a bad thing to be able to have a deal with a  five-story "try-catch" constructions, if the callwer wants to see this detail because we think that they can act on each of the specific errors differently.  It is always possible to catch the Exception superclass, if the caller does not want to process the detail. I also need to deal with these exceptions in node js, so having an explicit Error without needing to be aware of the java class hierarchy would work well for other languages.

**Comment by davidradl** [comment]
An example of an existing message is url
 ```
https://localhost:9443/servers/cocoView1/open-metadata/view-services/glossary-author/users/faith/glossaries?offset=0&pageSize=1&searchCriteria=.*
response.data
{
  class: 'InvalidParameterExceptionResponse',
  relatedHTTPCode: 400,
  responseCategory: 'InvalidParameterException',
  messageId: 'OMAS-SUBJECT-AREA-400-035',
  actionDescription: 'findGlossary',
  invalidPropertyName: 'serverName',
  message: 'OMAS-SUBJECT-AREA-400-035 Invalid parameter processing request serverName.',
  exceptionClassName: 'org.odpi.openmetadata.viewservices.glossaryauthor.services.GlossaryAuthorViewGlossaryRESTServices'
}
```

As you can see invalidPropertyName: 'serverName', can be accessed programmatically.

**Comment by davidradl** [comment]
@immmus I also want to have a connect button -for the case where the downstream view server is down. I have logic keying off this error in the presentation server.

**Comment by immmus** [comment]
> @immmus I do not think it is a bad thing to be able to have a deal with a five-story "try-catch" constructions, if the caller wants to see this detail, because we think that they can act on each of the specific errors differently. It is always possible to catch the Exception superclass, if the caller does not want to process the detail. I also need to deal with these exceptions in node js, so having an explicit Error without needing to be aware of the java class hierarchy would work well for other languages.

To handle the error in the response, its description is sufficient. There is no hierarchy to know, neither for js nor for other languages. 
if for example we take this error -> https://user-images.githubusercontent.com/35165540/85881514-67cbec00-b7e6-11ea-8af4-eed6e593090e.png

For the frontend developer and the person reading this error, everything is extremely clear. The name of the error for them is "OMAG-MULTI-TENANT-404-001". In this case, the message clearly shows that serverName is the problem. And in this case, no additional classes and fields had to be entered, and the client does not need to process different answers, just write the code for the standard answer.

**Comment by mandy-chessell** [comment]
The InvalidParameterException also has the name of the parameter as a property so it is possible to programatically determine which property is in error.  UserNotAuthorizedException has the userId.  They all have a map of additional properties that can added (called exceptionProperties)

The repository handler just uses 3 exceptions since that is sufficient for error handling for the following OMASs:
* AssetConsumer
* AssetOwner
* DigitalArchitecture
* GovernanceProgram
* DiscoveryEngine
* CommunityProfile

In the initial implementations of these interfaces, I had many more types of exceptions but realized that I was confusing what was needed to determine the next stage of processing in a client and what was needed to determine what went wrong.

The reality is that the client can not do much to recover from the error apart from capture the diagnostics and report error to its caller.

The message definition and related properties in our exceptions cover the need to understand precisely what went wrong. Having multiple exceptions to indicate the type and cause of an error is not needed.

The 3 exceptions used by the repository helper separate (a) a coding error in the client causing it to pass invalid parameters (b) an error in user's permissions needing an admin action (c) a transient error in the repositories requiring the Ops team to look at what is not running.  The reality is that the client can not do much to recover from the error.

If I was designing the OMRS API again, now that we have the ALF in place, I would have a much simpler exception list for the methods and would collapse exceptions such as EntityNotFoundException into InvalidParameterException etc.

**Comment by davidradl** [comment]
Adding a comment to keep open
