### ISSUE TITLE
Admin client has no support to launch a server

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3291]
The admin client has support for configuring a server.
However once configured, there is no ability to then control (including start)  the server that has been configured

ie the equiv of posting to 

```
"/open-metadata/platform-services/users/" + user + "/server-platform/origin"
```
identified whilst working on #426

**Comment by mandy-chessell** [comment]
This is still needed.

**Comment by mandy-chessell** [comment]
The platform origin request is part of the platform services rather than the admin services (see module name in URL).
It is available through the PlatformServicesClient.

However, I think this is still a valid issue as the commands to start and stop servers is owned by the admin services and currently is not included in the admin clients.  I have codes an new Admin Services client called OMAGServerOperationsClient and this starts and stops servers -as well as adds open metadata archives to a running server.

The new client should be in my next PR
