### ISSUE TITLE
Egeria needs to tell us the connector datasource type (DB2, MS-SQL etc) and property names for different types to be extracted.

### ISSUE THREAD

**Issue by guptaneeru** [odpi/egeria#331]
Currently, egeria does not have a place holder for  connection data source type. So if a connector of DB2 type is created in source repository, a target repository does not know about data source type from OMRS entities. 
Since the properties in connection object can vary depending on data source type, it is not clear which properties should be read from this object. 
Egeria needs to provide this information in Connector type or other related entity.

**Comment by mandy-chessell** [comment]
Please provide more more information on the use case for this enhancement.  

Connectors are local java objects and can not be transferred between repositories.  Their configuration can be exchanged between repositories.  I am reading "So if a connector of DB2 type is created in source repository..." as "So if a connection of DB2 type is created in source repository..." since it is easy to use the wrong word :)

The type of connector is defined in the connector type object linked to the connection object.  This tells the ConnectorBroker which type of connector to create.  Specifics of the data source are stored in the Endpoint object linked to the connection object.   Both of these objects support additionalProperties as well as the connection object.

It is possible to define the list of supported properties in the connector type.

What is special about the use case that means these options do not work.

**Comment by guptaneeru** [comment]
@mandy-chessell You are right, I am talking about connection and not connector.

My point is whenever a cohort member send events for a connection and connector type, there should be OMRS specification about what properties it needs to send in connector type along with additional properties. In the absence of defined OMRS property names or connection types, every repository can send different names. For instance IGC can call it MS-Sql while WKC can call it msSql and so forth.  Same is true for property names.  It can be userName, or Username or username in different repositories. How will consuming repository handle these differences. 

Like entity type def names are defined by OMRS. Every member repository  can map those names to its own types. But it does not need to worry about  other repositories' naming conventions. 

I hope it makes sense.

**Comment by mandy-chessell** [comment]
It does not make sense.  The contents of the connection/connector type/endpoint is aimed at the connector implementation.  It defines the properties it reads (and ignores the rest).  The specification of the additional properties supported by the connector is defined in the connector type.   This was added at Cassio's request for just this scenario - so I need more information as to why the current support is not adequate.

**Comment by guptaneeru** [comment]
"The specification of the additional properties supported by the connector is defined in the connector type."

where can find more information about above?

Will ConnectorType also tell me the type of connector (DB2, MSSql, Oracle, informix etc). If so what should I look at in connector type?  Any documentation or java doc will be helpful.

**Comment by mandy-chessell** [comment]
That is correct.  The purpose of the connector type is to define the type of connector.  It is described in the Open Connector Framework (OCF) javadoc.  When we talked about this last time, we agreed we needed to define common connector types for the connectors that were common between our platforms (even if the connector implementation is slightly different).  That is what I thought this issue was about initially until I read the text a bit more carefully.

**Comment by guptaneeru** [comment]
@mandy-chessell Excuse me if I am not using the correct terminology. Part of the reason is, I am not aware what part already exists and what is missing. I will go through the OCF documentation. But essentially, yes the issue is to track the missing pieces in the existing connector type implementation.

So, please use this issue for to define common connector types for the connectors that were common between our platforms.

**Comment by mandy-chessell** [comment]
WKC and IGC (and I will ask SAS too) each need to provide a list of connectors that they support.  Then we can document them in ODPi Egeria if that is where you think the documentation is needed.

**Comment by guptaneeru** [comment]
@Casio I need your help to answer Mandy'q questions.
