### ISSUE TITLE
Add governance actions to Term in the glossary author presentation server 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3346]

**Comment by mandy-chessell** [comment]
Goverance actions (connectors that implement remediation) or do you mean governance classifications

**Comment by davidradl** [comment]
> Goverance actions (connectors that implement remediation) or do you mean governance classifications

@mandy-chessell I was thinking of not calling them classifications and treating them as attributes of Term in the OMAS. I got governance action from the title of https://github.com/odpi/egeria/blob/master/open-metadata-publication/website/open-metadata-types/0422-Governance-Action-Classifications.md. Do you think it would be more clear to change the name?

**Comment by mandy-chessell** [comment]
I would rather they were not called actions since they do not define an action - only a classification.  This classification is then linked to different actions depending on the situation.

We use governance actions specifically to mean the connectors that run in the stewardship server/connectors and perform specific governance actions.

I also have these classifications as attributes in the asset but I still call them classifications as this is a common term in English.  

 ... "I have classified this as confidential"

**Comment by davidradl** [comment]
@mandy-chessell makes sense - as part of this change I will rename

**Comment by davidradl** [comment]
I will wait for https://github.com/odpi/egeria/issues/3417 and use the new mechanism around governance levels
