### ISSUE TITLE
server-chassis logging pattern

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#3392]
Logging pattern recently changed to 
`%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n`
and cannot be set up from application.properties anymore.

It still can be set by placing logback.xml into the classpath. Ex:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/base.xml"/>
</configuration>

```

As a requirement, I think, logging pattern should be configurable and not depend on the implementation.

**Comment by planetf1** [comment]
Our libraries should only use the slf4j-api and hence not include any logging implementation
our runnable jars - ie chassis, UI, utilities, samples - will need a binding, and we typically use logback for this
(test cases also either use logback-test.xml or bind with slf4f-simple)
logback will then use the config it finds on the classpath - which could be from one we specifically add, a dependency, or found externally.

Is this occuring in the chassis, UI, a specific utility?

Looking at our current tree,  we only have logback.xml for some of our samples, CTS client & archive utilities

I checked git history and it seems we've never had an overriding logback.xml for the server chassis or UI etc

The format I see running the chassis with no additional config is:
```
17:59:43.192 [main] INFO  o.o.o.s.s.OMAGServerPlatform - Starting OMAGServerPlatform on planetf1mac with PID 40630 (/Users/jonesn/IdeaProjects/egeria-maven/open-metadata-implementation/server-chassis/server-chassis-spring/target/server-chassis-spring-2.2-SNAPSHOT.jar started by jonesn in /Users/jonesn/IdeaProjects/egeria-maven)
17:59:43.200 [main] INFO  o.o.o.s.s.OMAGServerPlatform - No active profile set, falling back to default profiles: default
17:59:48.648 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 9443 (https)
17:59:48.694 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["https-jsse-nio-9443"]
17:59:48.694 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
17:59:48.694 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.36]
```

This looks similar to the default pattern from the logback docs at http://logback.qos.ch/manual/configuration.html - though I note class names are abbreviated. 

It does differ from the spring docs at https://docs.spring.io/spring-boot/docs/2.1.6.RELEASE/reference/html/boot-features-logging.html

Looking in the server chassis archive I did find an instance of logback.xml at
```
server-chassis-spring-2.2-SNAPSHOT.jar/BOOT-INF/lib/open-metadata-types-2.2-SNAPSHOT.jar/logback.xml
```

This sets pattern to
```
       <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
```

this is brought in through the dependency chain
```
 [INFO] org.odpi.egeria:server-chassis-spring:jar:2.2-SNAPSHOT
 [INFO] |  +- org.odpi.egeria:repository-services-implementation:jar:2.2-SNAPSHOT:compile
 [INFO] |  |  \- org.odpi.egeria:open-metadata-types:jar:2.2-SNAPSHOT:compile
```

This was added by me for #2693 under commit 5b1d84605c77ff72019eae0e63613e5fcb654f59

the reason for this is that OpenMetadataTypesArchiveWriter.java contains a main() and I had read it as a utility to create the type archive -- which must have a logging binding.

However we are using the module in 2 ways
 - as a dependency library
 - and an application

This probably explains your observation, but to resolve may need a little more unpicking. We may need to refactor this module so that we seperate the library (no logback config) from an application that uses it (the archive writer)

cc: @mandy-chessell

**Comment by bogdan-sava** [comment]
Goog catch @planetf1 .
UI is fine.
The main should be separated in my opinion.

Not sure why logback.xml was necessary, as I ran the main and it has no output whatsoever. It is completely silent yet .
Javadoc is ambiguous. I had to follow the code with debugger to realize that is writing the OpenMetadataArchive into file OpenMetadataTypes.json  .

I agree that main should be separated from the lib and needs logging in order to become more verbose. At least to say what file has been written. Count maybe ?!

**Comment by planetf1** [comment]
On reflection I've created a PR which removes logback. As you say, the current main() does not use logging. This resolves the slf4j config contamination I believe.

I also added a comment in the main() of the utility to link back to this defect in case the code is modified in future to do logging - and it does rather need something if it is to be useable.

I think this is a good balance of doing enough for now given focus/priorities.

**Comment by bogdan-sava** [comment]
this issue is reported as still present

**Comment by planetf1** [comment]
@bogdan-sava - where is it still wrong?

Our approach so far - or at least the *intent* is to include a logging configuration only for 'executables' that are directly run. This means the test tools, utilities, and the main applications (chassis/UI). Library modules should not include.

If we don't include any logging configuration at all then we will see an error at runtime.

The issue was previously caused by a rogue logback.xml being picked up from a non-executable.

For anyone who has a specific requirement it should be overridable also

**Comment by bogdan-sava** [comment]
It seems that, there is still picked up and overrides spring-boot default behavior, which has a very good logging pattern by default and allows to config logging pattern from a property.

So, let's check again the executables.

**Comment by planetf1** [comment]
I recursively unpacked the jars in the server chassis using the 'rjar' utility.
The result:
```
jonesn:xtract/ (master) $ find . -name 'logback.xml'                                                                  [17:40:56]
./server-chassis-spring-2.4-SNAPSHOT.jar/BOOT-INF/lib/open-metadata-types-2.4-SNAPSHOT.jar/logback.xml
jonesn:xtract/ (master) $ pwd                                                                                         [17:41:02]
/Users/jonesn/src/egeria/open-metadata-implementation/server-chassis/server-chassis-spring/target/xtract

```
commit 37e493b appeared to correctly remove logback

I see no current references to logback in the open-metadata-types and 'mvn dependency:tree' is not explicitly showing any
HOWEVER whilst it doesn't pull in the logback configuration (which I'd focussed on), it DOES pull in a configuration file -- so I think will cause the effect you describe

The real problem - in my view - here, is that, as mentioned in the original analysis, this module is used BOTH as a library, and offers an executable.

the *correct* fix is to split out these two capabilities so that the utility is in a seperate module, dependent on the libraries. Only the module needs logback configuration - both library & config.

A possible proposal would be to
 - add a new directory  'open-metadata-resources/open-metadata-archives/open-metadata-types-archivewriter' and module 'org.odpi.egeria:open-metadata-types-archivewriter' (names clunky)
 - mv src/main/resources/logback.xml & src/main/java/org/odpi/openmetadata/opentypes/OpenMetadataTypesArchive.java  to new project
 - add back the logback reference in the pom
 - remove the build with dependencies from the original module & move to new module
 - update assembly to pick up archive tool from new module

@bogdan-sava does this sound as if it will address your concern?
@mandy-chessell does this sound reasonable in terms of the type archives. I'm guessing only you currently use the archivewriter, but we still need to ship it?
