### ISSUE TITLE
Add Sample Data to vdc-open chart

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#344]
Add an additional pod to vdc-open helm chart with
 - postgress
 - OCO Pharmeceuticals sample data (unlike the charts thus far, this will require a persistant volume claim)

**Comment by mstrelchuk** [comment]
In order to use Coco Pharmaceuticals sample datasets for BI use-cases we need to have Primary Keys and  Foreign keys defined on those datasets. Below you can see how Coco Pharmaceuticals tables are connected.

![pk and fk coco pharm](https://user-images.githubusercontent.com/40057799/49378881-0e84ff00-f70e-11e8-8975-ba84f709478f.png)

**Comment by planetf1** [comment]
Also I will create a static gaian config for an interesting table to assist in testing (prior to virtualizer integration), but other views will be configured via the virtualizer (when ready)

**Comment by planetf1** [comment]
Ok.. I have a postgres container. I am working on the egeria config currently, but will aim to get sample data loaded into that container. 

The sample data is at https://github.com/odpi/egeria/tree/master/open-metadata-resources/open-metadata-deployment/SampleData though in my latest PR I have moved that slightly (though not changed the files)
