### ISSUE TITLE
Enhance the CTS to test more classification mutations

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#3455]
We just hit a problem where the in memory repository behaved differently from the graph repository when the subject Area FVT was run.
Two differences have been found 

- when supplying classifications with a new entity, the in memory repository did not insist that the classification was supplied with a type but the graph repository did. 
- The FVT issues an update on an entity to change a Glossary term from 4 to 3 classifications. The OMAS code ends up needing to issue a declassification, this required a change to the Graph repository code 

I suggest we enhance the CTS to cover these cases and ensure both repos pass.

**Comment by grahamwallis** [comment]
Both repositories use the Repository Helper to validate the classification is valid and further that it is valid for the type of entity. So it is a little surprising that they have different behaviours. From inspecting the code it looks like the classification that was supplied must have had no properties. PLEASE CONFIRM/REFUTE. If that were the case, then the Repository Validator (in validatePropertiesForType() - which is checking the classification's properties versus the classification's type) will allow the classification to pass, prior to checking its type. If the classification is accepted past that point then we are into the internal storage in the repositories, during which the graph repository does insist that the classification has a name, a type and a metadataCollectionId. If any of these properties are missing it will throw a CLASSIFICATIONS_PROPERTIES_ERROR.

I suppose a key question is which behaviour do we consider to be 'correct'? Do we want both (all) repositories to only accept a classification if the type is supplied, or do we want to accept an untyped classification? My inclination would be to insist on the type being supplied.

If we agree that the type is mandatory, we can add CTS tests that deliberately break that rule and ensure that any repository reports the error. Alternatively, if we want to allow untyped classifications, we can include the same tests but would expect that any repository would accept the untyped classification and fail the test if it doesn't.

@mandy-chessell @davidradl @cmgrote Thoughts welcome ^^

**Comment by mandy-chessell** [comment]
It is clearly wrong that classifications can not have properties - many ClassificationDefs define properties.  These properties follow the same rules as properties on entities and releationships.

It is reasonable to assume that the classification's header is properly filled out - it must have a metadataCollectionId to identify its home repository.  The type is less important because the classification name is actually the same as the ClassificationDef's type name so it can be looked up if the proper type is missing.  However, the type is supplied to validate that there are no clashing definitions - just having the classification name is not sufficent to perform that check.

**Comment by mandy-chessell** [comment]
BTW - the generic handlers are now supporting classification propagation so the repositories will see both values of ClassificationOrigin as well as classificationOriginGUID filled out.  I do not think the propagated classification option was used before.

**Comment by grahamwallis** [comment]
@mandy-chessell In response to your first comment "It is clearly wrong that classifications can not have properties..." - agreed - but that wasn't actually what was said: The classifications can optionally have properties (or not), but in the case where a classification does not have any properties the validator will return without throwing an exception, prior to checking whether there's a type. So in the case of no properties there is no check that the classification has a type - which is why we get through to the specific repository implementations - which currently differ in their tolerance of type-less classifications. (My confirm/refute question was really to @davidradl regarding whether his test classification did have properties or not, my assertion being that in this particular test it seems it had none, otherwise my explanation for why we see a difference in behaviour does not make sense, because with properties it would have been caught by theRepository Content Validator).

We could beef up the validation in the Repository Content Validator to insist on type being supplied, or we could ensure that both repositories enforce it.

**Comment by davidradl** [comment]
@grahamwallis the Subject Area FVT test I think you are talking about concerns setting, updating and changing the governance classifications (Criticality ,Confidence, Confidentiality and Retention). The tests included updates of the level property (an enum) to different values, updating to level to null (it is not mandatory) is the test that is now commented out. I did not include tests for the classifications with no properties, for the subject area omas I am not sure the confidentiality classification mean anything without its level property; It might be worth the OMAS policing the inclusion of a level as mandatory.

**Comment by grahamwallis** [comment]
@davidradl OK interesting - given that your classifications had properties it is hard (at present) to see how the repositories exhbited different behaviour. They both use the repository content validator to verify the classification and given that you supplied classification properties, the type check in the validator should have bounced the classification in both cases. I would have expected the RCV's validateProeprtiesForTYpe method to throw an OMRSLogicErrorException for either repository.

**Comment by davidradl** [comment]
From what I recall, in the older code the update entity was not mutating the classifications, so my Subject Area code manually mutated the classifications. After the big PR, the update entity code was changed to correctly mutate the classifications in the update entity call, so the subject area code mutation of the classification code is now redundant and needs cleaning up and the FVT test re enabled. 
The subject area code is trying to delete classifications that have already been deleted by the omrs update entity call. I think the graph implementation had more rigourous checking and noticed that a remove classification was being issued on an entity that did not have that classification. The in memory implementation did not error in this case. I have not retested recently - to confirm this is still the behaviour.
