### ISSUE TITLE
Not flexable security

### ISSUE THREAD

**Issue by immmus** [odpi/egeria#3468]
Hi dears @planetf1 @mandy-chessell and others.
I would like to consider the issue that Egeria does not have a flexible security setting system.
In current case  I want to consider the problem with OpenMetadataRepositorySecurity interface  but I think that this problem 
exists in other similar interfaces.  The problem is in use all void methods. For example:
I'll show you using the method **validateUserForEntityRead**
<img width="978" alt="Screenshot 2020-08-07 at 15 48 00" src="https://user-images.githubusercontent.com/35165540/89651394-884e9200-d8cc-11ea-9e95-6e151bcedd6d.png">

Let's say I wanted to restrict reading for users to a certain algorithm. The only way to do this through the void method is to throw an execution. But let's say a user made a request for terms and got a list of 100 entities. The algorithm implies that the user should get access to read 80 entities out of these 100. But as you can see in the screenshot below, if at least one entity from the list is unavailable to the user, he will not see the rest of which he has the right to view.
<img width="1156" alt="Screenshot 2020-08-07 at 15 48 15" src="https://user-images.githubusercontent.com/35165540/89655702-2a717880-d8d3-11ea-9b09-4fea3c35bd09.png">

I have shown just one example of many.
I think it is worth revising this and making a more flexible solution for configuring security. If necessary, I can think of a solution, but I would also like to hear suggestions from you.

**Comment by planetf1** [comment]
Looks like a good point. I would also expect that the viewable entities would be returned .. but .. read on

that could still be done with the exception, the issue is we're throwing the UserNotAuthorizedException from within the loop when the first entity is not readable.

We can get into a discussion about visibility here -- should the user know they don't have access, or should we behave as if the entity doesn't exist. For a single entity it's easy to do either. When we're processing a list should it be expected the list is already suitable and this is just double checking. I don't think we can say that, so like you, I would err to returning an incomplete list. (optionally we could annotate the results with how many security failures we had - but I think it unnecessary). We can't really return not authorized can we?

**Comment by immmus** [comment]
> Looks like a good point. I would also expect that the viewable entities would be returned .. but .. read on
> 
> that could still be done with the exception, the issue is we're throwing the UserNotAuthorizedException from within the loop when the first entity is not readable.
> 
> We can get into a discussion about visibility here -- should the user know they don't have access, or should we behave as if the entity doesn't exist. For a single entity it's easy to do either. When we're processing a list should it be expected the list is already suitable and this is just double checking. I don't think we can say that, so like you, I would err to returning an incomplete list. (optionally we could annotate the results with how many security failures we had - but I think it unnecessary). We can't really return not authorized can we?

In this context, the user is authorized because this method **validateUserForEntityRead** called after **validateUserForServer** and **validateUserForService** methods which responsible for accessing the service and requesting. This user only does not have access to some entities from the list.

<img width="802" alt="Screenshot 2020-08-07 at 21 52 39" src="https://user-images.githubusercontent.com/35165540/89678834-8ef2fe80-d8f8-11ea-8960-4ba4108f4f58.png">
<img width="831" alt="Screenshot 2020-08-07 at 21 52 18" src="https://user-images.githubusercontent.com/35165540/89678865-9914fd00-d8f8-11ea-8fd3-63092778b078.png">

And this just one scenario what I could come up. There can be many scenarios. Each company may have a different logic for protecting its metadata, and therefore I think the methods for the connector should be more flexible in customization.

**Comment by mandy-chessell** [comment]
This is not actually a problem.  Just because the exception is thrown by the security module does not mean it is returned to the user.  The function that it working through the list can use the exception to skip instance it does not have access to.  There are plenty of examples of this.

**Comment by mandy-chessell** [comment]
I put the comment above in quickly and here is more explanation.

So firstly, I agree we should change the logic on the return from the find requests to skip instances that are not authorised.  This is what we do in the methods called in the level above.  This does not require a change in the security connector interface, only the LocalRepositoryConnector implementation.

The repository security interface is actually not as useful as you would expect because of its position in the architecture.
 1. The metadata instances within the repository are being sent to other repositories in the cohort.  This means that even if the local repository eliminates an instance from the return results, it does not mean that another repository does not return it and then it appears in the combined results from the enterprise connector.
1. A single REST API call typically results in many calls to the repository services that are distributed across multiple repository instance.  Beyond a binary decision "should this user see this instance or not" the repository services typically do not have enough context to do anything particularly complex.

So the repository security interface is simple as a result and the assumption is that if a more sophisticated solution was required, it should be added by creating repository connector implementations that wrap the real repository connector.

We could extend the reposiotry security interface on read to allow the repository to filter out specific properties.  So the instance would be passed in and returned by the security module.   This would only be effective if the instance was not distributed to other members of the cohort.

At the moment the control of what is sent out on the cohort (and what is received and stored) is controlled by rules.  These rules are simple and really only allow filtering based on type.  There was an idea to have a connector to wrap these rules to allow a more sophisticated model.  From this discussion, it would seem that extending the metadata security connector to provide this support would make a lot of sense.  That way, the security module could prevent certain instances from being replicated to the cohort and then adding the filering option makes sense.
