### ISSUE TITLE
Created New Server for Improved Development in OMAG Configuration UI

### ISSUE THREAD

**Issue by jmmadsen** [odpi/egeria#3543]
Currently, the UI is being served in production mode for local development, making it very inefficient. I have created two new directories `cra-client` and `cra-server` that have the same functionality as the original code, but are optimized for development. I also refactored the server code to be more organized, as opposed to in one large file.

@davidradl - we discussed you testing the UI with a configured server to ensure I did not break anything during this process. I have updated the README.md, but to start you should:

1. Navigate into `cra-client`, and run `npm install`.
2. Navigate into `cra-server`, run `npm install`, then run `npm start`.
3. UI should be accessible at `https://localhost:3000/aaa` - I could only get it working with Firefox.

**Comment by jmmadsen** [comment]
More on my Chrome issues. I do not think this is a new issue I introduced in CRA, I experience the same issue with the original code. My version of Chrome is `84.0.4147.105`. 

![image](https://user-images.githubusercontent.com/57506409/92259609-4f8ee200-eea5-11ea-9bfa-c2bff0839015.png)

**Comment by planetf1** [comment]
Looks like the same issue I came across in #1403 -- In the draft PR #3238 I created new certs which def avoid this issue -- but I haven't yet had a chance to go back and complete the work.

In the PR are the commands to generate a compliant cert. Additionally the cert already checked in for the server should be fine.

I'd be pretty confident that is the only reason it doesn't work in chrome - simply because later browsers are being more strict with their security validation.

Either
 a) If @davidradl agrees get this PR in & then raise an issue to correct the certs (I can help)
 b) Wait until #3238 is completed
 c) let me know when the PR is nearly done (now?) and I can push an update -- but it may take me a day or three due to a blocking release issue

**Comment by jmmadsen** [comment]
Hi Nigel, thank you for the information.

I would prefer that this PR be merged and we address as we continue development focused on the UI. I have spoken with @dkneisly and others who are working on different pieces of the UI, and it would be helpful for them to have a working development environment to dynamically view changes. Let me know what you all think.

**Comment by planetf1** [comment]
I'm ok with any of the above  - just probably best to ensure there is an active issue referencing the change we need to do to security (and perhaps any of the other issues that you agree with we identified in the PR review - note that you can use the menu in github web ui to create an issue from a comment, though I think where possible group related ones together). It's good to ensure each comment is responded too/closed with an action ie not doing it/disagree / fixed, or will be addressed in later issue (add note). ok?

**Comment by jmmadsen** [comment]
That makes sense to me, I addressed and closed each comment you had. Opened up a new issue, and also address #1403 in a few. I think this has all been addressed now - let me know if not.

**Comment by planetf1** [comment]
divoluThanks. I think the only question left was whether the log. statements in the code would divulge any personal info (this includes ids, ip address etc), and to understand where it was logged to. If so it may need to be off by default.

**Comment by planetf1** [comment]
I tried building the client/server

In the case of firefox I get:

```
Secure Connection Failed

An error occurred during a connection to localhost:3000. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the web site owners to inform them of this problem.
```

That could be due to the code using an old TLS version? 

i also got a lot of warnings on the console output when running the server - I presume this is debug work in progress? I posted the text to https://gist.github.com/b1e1fb810b3f740cadfb0662bd0373ba

**Comment by jmmadsen** [comment]
Addressing the last piece first, yes that is just the JS linter. Not errors
but better practices that we will eventually address.

For the first error, did you make a .env file in both the cra-client and
cra-server following the  .env.template?

**Comment by planetf1** [comment]
No. My bad. I'll have to skip for today, but will try and learn the use of the UI soon so I can contribute to the security/packaging aspects.

**Comment by jmmadsen** [comment]
No problem! If you add the .env files, I’m 99% sure that will resolve the
issues.
