### ISSUE TITLE
Find Methods do not trigger REFRESH_ENTITY_REQUEST for entities that are not available in the local repository

### ISSUE THREAD

**Issue by danielaotelea** [odpi/egeria#3674]
I called findEntitiesByPropertyValue using the Asset Catalog OMAS (search method).
The response contains entities that are not stored in Egeria local graph repository. I was expecting to see on the cohort topic REFRESH_ENTITY_REQUEST for these entities, but there was nothing published out on the cohort topic after these call.
I looks that requestRefreshOfEntity was not called.

**Comment by danielaotelea** [comment]
For the EnterpriseOMRSRepositoryConnector, the localMetadataCollectionId is always null. This is the cause of the issue. Not only findByPropertyValue is not triggering the refresh events for the entities that are not in the local repository, all the find methods have the same issue.

**Comment by danielaotelea** [comment]
The same issue occurs for findRelationships- in the makeRefreshRecommendations method, the localmetadataCollection id is null.

**Comment by grahamwallis** [comment]
It looks to me like this might be a sequence problem.

The call to registerConnectionConsumer happens in the start() method of the EnterpriseOMRSRepositoryConnector. But this only happens after the attempt to setLocalConnector. The setLocalConnector call will iterate over the registeredConnectorConsumers and call setLocalConnector on each - but because the start has not yet happened there are no registered consumers. So the localMetadaaCollectionId never gets set.

**Comment by planetf1** [comment]
This was autoclosed in error - I added the wrong reference in the PR. Reopening!

**Comment by grahamwallis** [comment]
I have a go at fixing this. The attempted fix is in PR #3921 

The reason I am not certain it is a complete solution is because its very difficult to test. Even if I start one metadata server (with a local repo) and create a test entity in that repo; and only then start a second metadata server from which to issue the findEntitiesByPropertyValue search; as soon as the second server starts it picks up the NewEntityEvent from the earlier entity creation, so it has a reference copy before the find request is issued. It is possible to step through the enterprise  query and result accumulation - but the returned entity comes from the local repository so its GUID is added to the locallyStoredInstancesGUIDs array, and this means that when the result accumulator is deciding on refresh recommendations, the entity does not qualify as refresh requests are only sent for non local entities. 

I am not sure how to prevent the querying server from finding out about the new entity prior to the search.

@danielaotelea @mandy-chessell Please could you look at the fix and check it makes sense, and if possible test to see if it helps with the generation of the refresh requests?

**Comment by mandy-chessell** [comment]
There is a readonly metadata repository (used to introduct static content into the cohort) - would that help?

**Comment by danielaotelea** [comment]
Hello,

I have tested on my local environment and it looks that the issue is still there.
My setup is:
0. Kafka up and running
1. Create a platform with server1. 
On "server1" I have enabled local graph, access services, instance.
2. Start a new platform with server2.
On "server2" - local graph, access services, instance. 
Both servers are in the same cohort. 
3. Stop both servers.
4. Start "server1"
5. Add a glossary term "businessTerm1" in the local graph of "server1".
6. Stop "server1"
7. stop Kafka
8. start kafka (make sure there is nothing on the cohort topic, you may delete the cohort topic in case there are some events)
9. start "server1", call instance
10. start 'server2", call instance
11. using asset catalog OMAS - search for "businessTerm1" 
12. using Asset Catalog OMAS - get asset details with the GUID of the entity from step 11 
There are no events on the cohort topic.

Test case 2:
Using the GUID from Test 1, step 11 - and the home metadata collection id I've done the call:
{{url-omas}}/servers/{{server-id}}/open-metadata/repository-services/users/{{user-id}}/instances/entities/reference-copy/{{entity-guid}}/refresh?homeMetadataCollectionId={{home-meta-id}}\

I can see on the cohort topic the "REFRESH_ENTITY_REQUEST", but there is nothing else after this event.

**Comment by grahamwallis** [comment]
Thanks @danielaotelea - that was very helpful.

I re-tested the PR and found that although the initial change (so localMetadataCollectionId was set) helped, there were several other changes needed once we got past that point. I have added more changes, mainly to the event processor.

In summary, there are now a number of changes in this PR, to get refresh exchanges to complete:

- The Enterprise Metadata Collection needs to know the localMetadataCollectionId. This was previously always null, so the EMDC was under the impression that there was no local repository. This is fixed by passing the lMDCId into the Enterprise Connector Provider so it can be set on the connector prior to creating the EMDC.

- The saveExchangeRule processing was only looking at LEARNED_TYPES and was not considering processing of the instance event if the exchangeRule was set to ALL or SELECTED_TYPES. This has been modified so that if in LEARNED_TYPES mode the instance type will be added to the selected types list (if not already present). Then processInstanceEvent is to determine whether the instance event satisfies the exchangeRule (whatever mode the rule is set to). Finally, if the instance type is active in the local repository, the refresh is processed.

- Another change is that the metadataCollectionId passed to refreshRetrievedEntity needs to be the homeMetadataCollectionId of the received instance; whereas it was being set to the localMetadataCollectionId.

With these changes in place, I now see the refresh request is sent, and a refreshed response is received.

In my tests, the servers and metadata collections are as follows:

"Metadata_Server" (like "server1" in Daniela's test) is where the entity was created. 
It has metadataCollectionId 71451fa3-6a74-4366-8538-0c57fb39e988

"Metadata_Server2" (like "server2" in Daniela's test) is the server from which the enterprise query was issued.
It has metadataCollectionId fcc0e6d9-3c8a-4135-a5a0-295393e57cb3

The following events are seen on the cohort topic:

{"class":"OMRSEventV1","protocolVersionId":"OMRS V1.0","timestamp":1603368752991,"originator":{"metadataCollectionId":"fcc0e6d9-3c8a-4135-a5a0-295393e57cb3","serverName":"Metadata_Server2","serverType":"Metadata Repository Server"},"eventCategory":"INSTANCE","instanceEventSection":{"eventType":"REFRESH_ENTITY_REQUEST","typeDefGUID":"d8f33bd7-afa9-4a11-a8c7-07dcec83c050","typeDefName":"Process","instanceGUID":"0e7909d4-27a2-4dcf-a8b4-db809f57d816","homeMetadataCollectionId":"71451fa3-6a74-4366-8538-0c57fb39e988"}}


{"class":"OMRSEventV1","protocolVersionId":"OMRS V1.0","timestamp":1603368754058,"originator":{"metadataCollectionId":"71451fa3-6a74-4366-8538-0c57fb39e988","serverName":"Metadata_Server","serverType":"Metadata Repository Server"},"eventCategory":"INSTANCE","instanceEventSection":{"eventType":"REFRESHED_ENTITY_EVENT","typeDefGUID":"d8f33bd7-afa9-4a11-a8c7-07dcec83c050","typeDefName":"Process","instanceGUID":"0e7909d4-27a2-4dcf-a8b4-db809f57d816","entity":{"class":"EntityDetail","headerVersion":0,"type":{"class":"InstanceType","typeDefCategory":"ENTITY_DEF","typeDefGUID":"d8f33bd7-afa9-4a11-a8c7-07dcec83c050","typeDefName":"Process","typeDefVersion":1,"typeDefDescription":"Well-defined sequence of activities performed by people or software components.","typeDefSuperTypes":[{"headerVersion":1,"guid":"896d14c2-7522-4f6c-8519-757711943fe6","name":"Asset","status":"ACTIVE_TYPEDEF"},{"headerVersion":1,"guid":"a32316b8-dc8c-48c5-b12b-71c1b2a080bf","name":"Referenceable","status":"ACTIVE_TYPEDEF"}],"validInstanceProperties":["qualifiedName","additionalProperties","name","description","owner","ownerType","zoneMembership","latestChange","displayName","formula"]},"instanceProvenanceType":"LOCAL_COHORT","metadataCollectionId":"71451fa3-6a74-4366-8538-0c57fb39e988","metadataCollectionName":"Metadata_Server","createdBy":"garygeeke","createTime":1603356387247,"version":1,"guid":"0e7909d4-27a2-4dcf-a8b4-db809f57d816","properties":{"class":"InstanceProperties","instanceProperties":{"name":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING","primitiveValue":"another-process-short-name"},"qualifiedName":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING","primitiveValue":"oh-my-not-another-process-for-enterprise-test"},"displayName":{"class":"PrimitivePropertyValue","instancePropertyCategory":"PRIMITIVE","primitiveDefCategory":"OM_PRIMITIVE_TYPE_STRING","primitiveValue":"another-process-display-name"}},"propertyNames":["qualifiedName","displayName","name"],"propertyCount":3},"status":"DRAFT"}}}
 
@danielaotelea  Can you please re-test and check whether this fixes the problem for you?

@mandy-chessell Can you please review and check that my changes are accurate and complete?

**Comment by danielaotelea** [comment]
Hi @grahamwallis!

It looks fine. I have re-tested it and it works properly after the latest changes from your PR. Thank you!

**Comment by grahamwallis** [comment]
@danielaotelea Thanks for testing it. I have merged the PR and will close this issue as fixed, and we can reopen if needed.
