### ISSUE TITLE
Presentation Server UI has no logout button

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#3719]
If a user logs into the presentation server UI and wishes to switch user, they cannot, as there is no logout button currently

**Comment by davidradl** [comment]
@jmmadsen I remember us talking about this; is this something you are going to look at implementing ?

**Comment by jmmadsen** [comment]
Sure, this sounds like a good next task. Should I pick it up once we move over to the new repository?

**Comment by davidradl** [comment]
@jmmadsen Great. I dont think we need to wait for the repo move, you can start right away. I plan to continue developing on the cra folders, then switch over to the new repo when we do that move.

**Comment by jmmadsen** [comment]
I added a logout button, and it works in the current UI. I believe it meets the current scope of this issue.

However, I do have some concerns about how authentication is currently implemented in the UI. This is something I think we could do better and address in a future PR. This would be a larger change.

**Comment by jmmadsen** [comment]
https://stackoverflow.com/questions/37582444/jwt-vs-cookies-for-token-based-authentication#:~:text=Both%20cookies%20and%20bearer%20tokens,often%20encoded%20as%20a%20JWT.

Basically, we should decide if we want to include a JWT in a bearer token, or a cookie. Currently it looks like we're trying to do a mix of both.

Personally, I prefer setting an http-only cookie with a JWT. JavaScript code is not allowed to access this, and it persists across refreshes until its expired or revoked. The downside to this method is that the client code won't know if we're logged in, so we have to manually enter redirects. We can also include middleware to protect all sensitive routes with the JWT since it will be included on requests automatically as a cookie.

**Comment by davidradl** [comment]
@sarbull @planetf1 @grahamwallis @mandy-chessell any thoughts?

@jmmadsen
I am not an expert at security; so apologies if I have mis-sunderstood. I think that we are using a simple authentication because we are using the simplest authentication with an in memory store from passport. It would be good to know your thinking on whether or not this is sufficient for demos.

For production use cases, we always thought we would support a choice between LDAP and oauth, which passport supports. I see that the jwt bearer authentication can be set up with passport (as can ldap and oauth). [https://www.digitalocean.com/community/tutorials/api-authentication-with-json-web-tokensjwt-and-passport](https://www.digitalocean.com/community/tutorials/api-authentication-with-json-web-tokensjwt-and-passport)

If you like, you could repurpose this issue to implement a more robust authentication mechanism including logout. This authentication mechanism should be pluggable, choosing between the basic login, or ldap or oAuth depending on configuration. Ldap might be a good place to start, as Egeria already supports this in the java code; so there could be a consistent way to authenticate across the Egeria eco-system.

**Comment by sarbull** [comment]
i have used this oauth2 implementation in the past, named [cloudfoundry/uaa](https://github.com/cloudfoundry/uaa), which is a separate module, deployed as a separate entity/application that can authenticate users..

**Comment by jmmadsen** [comment]
@planetf1 Recommend closing this issue as logout button has been merged to Master. Will open a new issue for broader discussions around authentication in the client.
