### ISSUE TITLE
Create Prod Build of CRA UI

### ISSUE THREAD

**Issue by jmmadsen** [odpi/egeria#3885]
Currently, the new CRA UI only works in development mode. We need to make a production build as well. 

@davidradl @grahamwallis Do we want to serve the static files from the same server (CRA-Server), or do we want to use another Nginx server? Serving from the CRA-Server will require installing a proxy router I believe.

**Comment by davidradl** [comment]
@jmmadsen I am not an expert at this. I notice this link https://create-react-app.dev/docs/proxying-api-requests-in-development/ seems to be talking about proxying for development case. I do not understand why we would need to proxy for the production case, where there is no development server, so static resources and the rest endpoints are both on the same server (as they are at the moment). There maybe a need to change the development server endpoints to allow easy proxying, the link suggests prefixing rest call end points with /api/ so the dev server only handlers the static content and rest calls are always sent to the API server. @dkneisly any thoughts?

**Comment by planetf1** [comment]
The UI being developed for ING is also making use of nginx for static content. We're trying to get that working now as a first pass for our automated deployment in #3893

I know that for that work (on ui-server-chassis) a similar change was made to move to /api/ in order to make routing easier -- in that ui's case they are using the netflix zuul proxy.

As to whether it's needed - for high volume sites absolutely. My gut feel says it's more than we need right now, but that doesn't mean it's not a good idea.. (performance, security, seperation of concerns..)
