### ISSUE TITLE
open-metadata-deployment not included in parent pom.xml

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#389]
The pom.xml for open-metadata-resources needs to include the new module open-metadata-deployment so the new module is included in the build.

```xml
<artifactId>open-metadata-resources</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>open-metadata-samples</module>
        <module>open-metadata-demos</module>
        <module>open-metadata-deployment</module>    <=== add this line
    </modules>
```

**Comment by planetf1** [comment]
It's ok to do this (and more consistent I agree). However I hadn't yet added it since it's unclear how we will automatically build the deployment pieces - in particular the docker images.

The docker build currently builds a number of different open source projects, and this can take more than an hour. It also has additional dependencies on docker/containers, the memory footprint, cpu - so my anticipation is that this will need to run as a seperate jenkins job, not by default. This is planned to be discussed with our build experts once the more basic build aspects are resolved (which is the case now). An additional maven profile may make sense.

We also need to host the helm charts. This can be directly in git, but a maven package by itself isn't directly supported - it would have to be published somewhere, which is why that package doesn't yet exist, it has less 'meaning'

None of this precludes this above change, but the pom in deployment currently is sparse, and doesn't directly deliver any value.

**Comment by mandy-chessell** [comment]
Makes sense.  OK to do this as part of another issue.  I would suggest add this module to the build module structure and add the build of the docker images to a specific profile or step in the build so that they are created on the build machine, but do not slow developers down.  When we get really fancy I expect the docker images will be used in an automated system test.

**Comment by planetf1** [comment]
this has been addressed
