### ISSUE TITLE
Supported database and how to configure database with Egeria

### ISSUE THREAD

**Issue by DhruvMevada** [odpi/egeria#4005]
Hi all, I am new to Egeria. having a few questions if anyone guides me on that then it will be a great help.
1. List of databases supported by Egeria
2. How to configure the database with Egeria
2. Does it required the whole database & tables to be store? or only metadata information is enough?

**Comment by mandy-chessell** [comment]
Hello
Egeria uses a data store to store the metadata it is managing and exchanging.  This is a private store.  The type of the data store used for this purpose is configurable for each server so an organization can write their own.  Egeria has an implementation using JanusGraph which can be configured to use Cassandra or BerkleyDB. See https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/user/configuring-the-local-repository.html

Egeria can extract and manage metadata from a database that is being used to store business data.  This is largely information about the database schema, connection and its network address.  This is the first stage to building a data catalog.  The connector to do this is managed by the Database Integrator integration service running in an Integration Daemon server.  See - https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/concepts/integration-daemon.html.   Details of the connector are here: https://egeria.odpi.org/open-metadata-implementation/governance-servers/integration-daemon-services/docs/integration-connector.html.  Through this mechanism is possible to build connectors to any type of database.

Since not everyone is comfortable with building connecotrs, we are also working on prebuild connectors to specific databases.   There is a PostgreSQL connector being developed at the moment and we expect more to follow in the next few months.

**Comment by planetf1** [comment]
Closing this as the question is answered. I recommend watching the https://github.com/odpi/egeria-database-connector repo where @wbittles is working on the postgres connector. This should be the first supported database for egeria.
