### ISSUE TITLE
calling integration services API doesn't return expected data 

### ISSUE THREAD

**Issue by wbittles** [odpi/egeria#4073]
@mandy-chessell  as discussed 

The following curl command , when executed against a vanilla OMAG platform 

 curl -k https://localhost:9443/open-metadata/admin-services/users/garygeeke/servers/myserver/integration-services
returns
{"class":"RegisteredOMAGServicesResponse","relatedHTTPCode":200}

**Comment by mandy-chessell** [comment]
That is the correct response - the call returns the integration services that are configured in the named server.  Since there are no services configured, an empty list is returned.

If you want the list of registered services use the platform service call
curl -k https://localhost:9443/open-metadata/platform-services/users/garygeeke/server-platform/registered-services/integration-services
