### ISSUE TITLE
OpenMetadataRootReferences file

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#4128]
During a local (maven) build I saw a RAT check failure due to the above file not containing a license.

The file is completely empty.
Is it necessary?

**Comment by mandy-chessell** [comment]
Where is this file?

**Comment by planetf1** [comment]
The only place I can see reference to anything similar is in the open types fvt. 
However when I run the fvt within the maven build I do not see this file after a successful run.
Perhaps it gets left behind if the fvt fails
I can't see explicitly where this might created in the code. Maybe @davidradl may know?

**Comment by grahamwallis** [comment]
Apologies - I had tried to respond but never quite got as far as hitting the green comment button! 

Took a bit of finding again, but it is here....

/Users/grahamwallis/dev/egeria/open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/OpenMetadataRoot/OpenMetadataRootReferences.java

**Comment by planetf1** [comment]
I had this again today on 2.5 when doing a 'mvn clean install', which suggests that 'clean' is not fixing this.

One of the issues with the open types fvt is that it is being run in the source tree -- and creating files there -- it should really use something under 'target' to be handled automatically.

That being said we do have a clean entry in the pom for that directory:

```
                  <plugin>
                        <artifactId>maven-clean-plugin</artifactId>
                        <configuration>
                            <filesets>
                                <fileset>
                                    <directory>${basedir}/src/main/java/org/odpi/openmetadata/fvt/opentypes</directory>
                                </fileset>
                                <fileset>
                                    <directory>${basedir}/src/test/java/org/odpi/openmetadata/fvt/opentypes</directory>
                                </fileset>
                            </filesets>
                        </configuration>
                    </plugin>
```
which looks as if it should clean it fine - and gradle isn't yet running these tests (though it is compiling ) ....

Indeed trying to test that cleanup (just building this dir)
```
➜  egeria git:(egeria-release-2.5) touch /data/src/egeria/open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/OpenMetadataRoot/OpenMetadataRootReferences.java
➜  egeria git:(egeria-release-2.5) mvn cl
➜  egeria git:(egeria-release-2.5) pwd
/home/jonesn/src/egeria
➜  egeria git:(egeria-release-2.5) cd  /data/src/egeria/open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test
➜  open-types-test git:(egeria-release-2.5) mvn clean
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.odpi.egeria:open-types-test >-------------------
[INFO] Building Open Types Test execution 2.5
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ open-types-test ---
[INFO] Deleting /data/src/egeria/open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/target
[INFO] Deleting /data/src/egeria/open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes (includes = [], excludes = [])
[INFO] Deleting /data/src/egeria/open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/test/java/org/odpi/openmetadata/fvt/opentypes (includes = [], excludes = [])
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.960 s
[INFO] Finished at: 2020-12-02T15:02:38Z
[INFO] ------------------------------------------------------------------------
➜  open-types-test git:(egeria-release-2.5) ls /data/src/egeria/open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/OpenMetadataRoot/OpenMetadataRootReferences.java
ls: cannot access '/data/src/egeria/open-metadata-test/open-metadata-fvt/open-types-fvt/open-types-test/src/main/java/org/odpi/openmetadata/fvt/opentypes/entities/OpenMetadataRoot/OpenMetadataRootReferences.java': No such file or directory
```
So that seems to confirm clean should work, but perhaps when we build from the root, the RAT check is being done earlier than the clean on the opentypes. This isn't a problem for the other generated files as they are either rat excluded or compliant.

A few options
 * A quick addition to the RAT exclusions would mask the issue...
 * Ensuring any created files are rat compliant would be better
 * debugging to figure out why 'clean' isn't working is perhaps the most useful in case other issues surface
 * refactoring the open types test to adhere to maven conventions more closely is probably the best solution, but notable more work

**Comment by wbittles** [comment]
As mentioned earlier I have also hit this zero length file and it would be nice to not have to do a full maven clean install as a workaround

**Comment by planetf1** [comment]
@davidradl I think this is yours
