### ISSUE TITLE
[connector-configuration-factory] refactor ConnectorConfigurationFactory to remove dependencies on connector providers

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#4327]
The purpose is to eliminate dependencies of connectors to avoid packaging in all.

- eliminate providers compile dependencies
- add unit tests to assert the class still exist (this will keep maven dependencies but test scope) to avoid eventually provider class name  or package refactoring to brake the factory.

**Comment by bogdan-sava** [comment]
This is dependent on having connectors jars in the lib folder on the distributions.
@planetf1 can you please confirm if this is ready?

**Comment by planetf1** [comment]
I do agree we want to move to dynamic loading for connectors. There were some notes also suggesting this in #1607 

At the moment connector jars are present in the assembly build by maven, and they've been build with dependencies. So they should be self-sufficient. Duplication, yes, but should work. That change was made about 1-2 months ago.

Where connectors are fully pluggable, I would not expect us to want/need maven dependencies at all, since it should all be driven by runtime configuration and/or packaging - so for sure, compile time dependencies should be removed, but I don't think we even want runtime dependencies. (It may be useful to retain for test).

We need to make sure that our default/recommended configurations are suitable...

We should ideally also mirror the solution for gradle - though where we have difficulties let's at least raise an issue to track, since the gradle build is still lagging.

We can cut down the dependencies when we build the connectors themselves by declaring some dependencies as 'provided'. This means we can RELY on them being part of 'the platform' . That's going to be a core subset - broadly speaking the things we ALWAYS bring into the server chassis. Since we know they are always there, we can safely skip adding them into the connector jar [ this could be a second phase of refinement for simplicity ]

in terms of scenarios, we need to ensure we can clearly handle
 - users building & running egeria in an IDE. How does what they need to do to run/test differ? How do we explain this [I think it's ok to have some impact/changes needed, we just need to explain what they are]
  - ensure our unit tests (FVTs) still work
   - ensure our docker image still works
   - ensure our helm charts / docker compose still works
   
   
So we definately need to take care and test, but this change IS NEEDED, and is the right way forward.

**Comment by planetf1** [comment]
^^ cc: @mandy-chessell

**Comment by bogdan-sava** [comment]
I moved the dependencies for the moment under full-platform profile.
When the steps are ready, should be removed.
