### ISSUE TITLE
Common Services OpenMetadataAPIGenericHandler obsolete null check

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#4357]
#4342 related

Class
egeria/open-metadata-implementation/common-services/generic-handlers/src/main/java/org/odpi/openmetadata/commonservices/generichandlers/OpenMetadataAPIGenericHandler.java

line 1429

Need to check if the if null checks are obsolete like aslo stated in the comment

```
            while (iterator.moreToReceive())
            {
                Relationship relationship = iterator.getNext();

                /*
                 * This if statement should always be true.
                 */
                if ((relationship != null) && (relationship.getType() != null) &&
                    (relationship.getEntityOneProxy() != null) && (relationship.getEntityTwoProxy() != null))
                {
```

**Comment by mandy-chessell** [comment]
It is worthwhile leaving the check in because the values are coming from externally pluggable components.

In general I do not believe we should be removing checks that prevent NPEs in the server.  At this particularly time the current state of the code may mean that this code is technically not needed, but a future change in another component may cause this to prevent an NPE that is hard to debug.
