### ISSUE TITLE
Glossary Author error handling 

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4541]
*UPDATED 20210202 * The reported issue is resolved - issue being left open to address error handling

Using the coco pharma lab environment, glossary author fails to connect to the server with:

```
Error occurred
Full response: {"class":"SubjectAreaOMASAPIResponse","relatedHTTPCode":400,"exceptionClassName":"org.odpi.openmetadata.viewservices.glossaryauthor.services.GlossaryAuthorViewGlossaryRESTServices","actionDescription":"getConfig","exceptionErrorMessage":"OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.accessservices.subjectarea.server.services.SubjectAreaConfigRESTServices exception was caught by getConfig; error message was OMAG-MULTI-TENANT-404-001 The OMAG Server cocoMDS2 is not available to service a request from user garygeeke","exceptionSystemAction":"The system is unable to process the request.","exceptionUserAction":"Review the error message and other diagnostics created at the same time.","result":[]}
```

**Comment by sarbull** [comment]
I'm getting the same thing

<img width="1295" alt="Screenshot 2021-01-28 at 15 04 13" src="https://user-images.githubusercontent.com/1864112/106143956-2cc6d800-617c-11eb-911b-1a0726b7d4a2.png">

**Comment by mandy-chessell** [comment]
Are there error messages in the View server?  It is suggesting that the view server is connecting to a platform that does not have cocoMDS1 running.  Is the right platform configured in the view server?  Is cocoMDS1 actually running?

**Comment by mandy-chessell** [comment]
In the standard coco landscape the subject area OMAS is not running in cocoMDS1 - it is in cocoMDS2 on the core platform

**Comment by davidradl** [comment]
@planetf1 I would have expected faithbroker to be running the glossary author not garygeek

**Comment by davidradl** [comment]
The Error message is not great :-(

**Comment by planetf1** [comment]
Currently it is configured as:
```
# The governance solution view services currently only consist of glossary author
print ("Configuring the Governance Solution View Services")
remotePlatformURL=dataLakePlatformURL
remoteServerName="cocoMDS4"
viewService="glossary-author"
configureGovernanceSolutionViewService(adminPlatformURL, adminUserId, viewServerName, viewService, remotePlatformURL,remoteServerName)

```
Which suggests to me that view service would use cocoMDS4. Now that isn't going to work well now since I assume it uses subject area OMAS which isn't on cocoMDS4. Sounds like it should be cocoMDS1 (which IS running). 

But... that doesn't explain why an error above reporting an issue with cocoMDS4 which is neither of these...

**Comment by mandy-chessell** [comment]
It should be connecting to cocoMDS2

**Comment by planetf1** [comment]
> It should be connecting to cocoMDS2

sorry reverse my two references -- should be 2, configured as 4, but error is 1...

**Comment by mandy-chessell** [comment]
cocoMDS4 is the data lake user's metadata access point - it is for adhoc access to metadata - not authoring part of the governane program.  cocoMDS2 is the server for the governance team

**Comment by planetf1** [comment]
> @planetf1 I would have expected faithbroker to be running the glossary author not garygeek

Yes agree, though gary tends to have all powers.. and using a different id also is good for testing any error scenarios :-)

**Comment by mandy-chessell** [comment]
Sounds like there is still and inconsistency in the notebooks - would you like me to look at it?

**Comment by planetf1** [comment]
> Sounds like there is still and inconsistency in the notebooks - would you like me to look at it?

May be easiest I do here at least initially (I can check the servers etc) unless you want to also check the presentation server UI

**Comment by planetf1** [comment]
Checking the notebook, it's already coded as  cocoMDS2 originally - as per what we'd expect from the coco org.

In fact the log I posted did indeed refer to cocoMDS2, but we then had @sarbull s error which was for cocoMDS1 ... (which as you say is the wrong server) .......

cocoMDS2 is running subject area

**Comment by mandy-chessell** [comment]
I had a look at the latest server-config python notebook.

Problem I think is that cocoMDS2 runs on the core platform not the data lake platform.  This is why the view server is not able to connect.  

```
# The governance solution view services currently only consist of glossary author
print ("Configuring the Governance Solution View Services")
remotePlatformURL=dataLakePlatformURL
remoteServerName="cocoMDS2"
viewService="glossary-author"
```
I fixed it in PR #4550.  There is a file rename in the commit which will be benign if you want to backport it to r2.6.

**Comment by mandy-chessell** [comment]
> The Error message is not great :-(

@davidradl There are multiple layers involved in handling this error.  The orignal exception says that cocoMDS2 is not available - which is correct.  I have, however, improved the original message's system action and user action since it did not mention that the platform may be wrong.     
```
SERVER_NOT_AVAILABLE(404, "OMAG-MULTI-TENANT-404-001",
            "The OMAG Server {0} is not available to service a request from user {1}",
            "The system is unable to process the request because the server is not running.",
            "Retry the request when the OMAG Server is available."),
```
to
```
    SERVER_NOT_AVAILABLE(404, "OMAG-MULTI-TENANT-404-001",
                         "The OMAG Server {0} is not available to service a request from user {1}",
                         "The system is unable to process the request because the server is not running on the called platform.",
                         "Verify that the correct server is being called on the correct platform and that this server is running. " +
                                 "Retry the request when the server is available."),
```
None of these instructions are valid for the UI user since they can not look at the audit logs or fix server configuration. However, the system operator needs to know this :)

The original exception seems to be wrapped in a SubjectAreaRESTServices exception by the Subject Area OMAS.
This is a strange class name for an exception and it turns out to be an error in the code that populates the response in
SubjectAreaOMASResponse.
```
/**
     * Set a standard exceptional info for the response
     *
     * @param e exception {@link OCFCheckedExceptionBase}
     * @param className name of the class being called.
     **/
    public void setExceptionInfo(OCFCheckedExceptionBase e, String className) {
        super.setRelatedHTTPCode(e.getReportedHTTPCode());
        super.setExceptionClassName(className);
        super.setActionDescription(e.getReportingActionDescription());
        super.setExceptionUserAction(e.getReportedUserAction());
        super.setExceptionErrorMessage(e.getReportedErrorMessage());
        super.setExceptionSystemAction(e.getReportedSystemAction());
        super.setExceptionProperties(e.getRelatedProperties());
    }
```  
The call to setExceptionClassName is passing the name of the calling class rather than the exception class name.
This means that the original exception of InvalidParameterException, which parameter was wrong and its value is now a nested exception and will not leave the server.

The Subject Area client then converts the SubjectAreaConfigRESTServices exception to a PropertyServerErrorException with the `OMAG-COMMON-400-016` message because it uses the FFDC services RESTExceptionHandler.detectAndThrowStandardExceptions() method which does not recognized SubjectAreaConfigRESTServices as one of the standard exceptions - no kidding :) 

I have improved the OMAG-COMMON-400-016 message to direct the reader to the original message's system/user action.
From
```
UNEXPECTED_EXCEPTION(400, "OMAG-COMMON-400-016",
              "An unexpected {0} exception was caught by {1}; error message was {2}",
              "The system is unable to process the request.",
              "Review the error message and other diagnostics created at the same time."),
```
to
```
    UNEXPECTED_EXCEPTION(400, "OMAG-COMMON-400-016",
                         "An unexpected {0} exception was caught by {1}; error message was {2}",
                         "The system is unable to process the request and has returned an exception to the caller.",
                         "Review the error message.  Also look up its full message definition which includes the system action " +
                                 "and user action.  This is most likely to describe the correct action to take to resolve the error.  " +
                                 "If that does not help, look for other diagnostics created at the same time.  Also validate that the " +
                                 "caller is a valid client of this server and is operating correctly."),
```
However, if the original InvalidParameterErrorException had been thrown the original error message and descriptions will make it through to the view service.

The view service does not seem to catch and process the exception from the subject area OMAS client.  It seems to go through to the UI.  The UI user is probably not in a position to look at error logs or correct configuration.  Their user action should probably be to report the problem or wait for it to be resolved.  It may be helpful to point out that further diagnositics are available on the View server's audit log.

How then does the system operator know that there is a problem and what to do?  They rely on the view service logging the error to the audit log.  This means they are informed even if none of the UI users reports the problem.

So the `setExceptionInfo()` method is the root cause of the problem.  However, the view service should probably be wrapping the real exception with something more helpful to the UI user and logging to the problem to the audit log.

It is also considered bad practice to have methods in jackson beans that do anything other than get and set variables since it can cause strange side effects in the marshalling/demarshalling code in Jackson - so `setExceptionInfo()` method  should probably be in the REST service class (or better still use the version in FFDC Services).

**Comment by planetf1** [comment]
Cherry-picking the fix 037256b77b1632f4c91a6bb14d1517c7b4b653cc  causes the error:

Configuring the Governance Solution View Services
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-40-dade5042e344> in <module>
     44 # The governance solution view services currently only consist of glossary author
     45 print ("Configuring the Governance Solution View Services")
---> 46 remotePlatformURL=coreLakePlatformURL
     47 remoteServerName="cocoMDS2"
     48 viewService="glossary-author"

NameError: name 'coreLakePlatformURL' is not defined

Fixed in:
See #4644 (Release 2.6)  and #4644 (master) 

@davidradl once done I think we're good for 2.6 - so you may want to update abstract/reassign to handle any of the error handling points, or harvest observations into new issues?

**Comment by planetf1** [comment]
Tested good in 2.6 - updating/reassigning

**Comment by mandy-chessell** [comment]
This work is not planned
