### ISSUE TITLE
Dino - need a back button when viewing access services

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4641]
Using Dino in 2.6 (though I think this can be addressed in master) i noticed that once I've jumped to looking at
details on an access server there's no navigation back to the previous pane ie:

Firstly click on cocoMDS2

<img width="474" alt="Screenshot 2021-02-01 at 18 25 02" src="https://user-images.githubusercontent.com/7292002/106501370-f90cea80-64ba-11eb-82c3-d99199808b2a.png">

Now access services
<img width="456" alt="Screenshot 2021-02-01 at 18 25 07" src="https://user-images.githubusercontent.com/7292002/106501373-f9a58100-64ba-11eb-9b33-eb08e0263ed6.png">

Now asset catalog
<img width="462" alt="Screenshot 2021-02-01 at 18 25 13" src="https://user-images.githubusercontent.com/7292002/106501374-fa3e1780-64ba-11eb-9229-ea1d9e91218f.png">

No way back?

**Comment by grahamwallis** [comment]
The easiest way 'back' (or to anywhere you want to go) is to click on it in the diagram.
I added 'back' links in Tex for people who are digging in from a type (e.g. an entity type) into a property of that type, and then into the enum definition for the property type - but in that scenario the diagram doesn't provide a way 'back' because that is all detail that is not on the diagram. But in Dino the user is free to click on anything in the diagram and that 'thing' will become the focus (including in most cases getting refreshed from the server).

**Comment by planetf1** [comment]
Ok, closing this since working as designed
