### ISSUE TITLE
Overloaded properties in type definitions

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#4665]
Currently there are some examples (or at least 1) where a given tree of type definitions has the same property defined at multiple levels. One example:

- `SchemaAttribute` defines a property `minimumLength`
- `RelationalColumn` also defines a property `minimumLength`, even though it subtypes `SchemaAttribute`

Aside from the conceptual ambiguity this potentially causes, the tangible impact comes against underlying repositories that are storing these properties: particularly when the property is being stored against a namespace taken from the type definition that defines the property (necessary per discussion in #4647, where the same property could be defined against different type definitions and actually have a different type itself (eg. string vs numeric)). In such cases, particularly in a repository that must handle history (where the typedefs themselves may change over the history of the instances that are stored), having such ambiguity in the model will cause complexity particularly in areas like search: where a request will arrive simply for searching against `minimumLength` and depending on the time period involved we may want to look at only one of these or both.  In addition to the potential for bugs inherent in adding such complexity, there is also likely to be a performance impact associated.

So the question is if there is any reason to retain both properties in such cases?  If not, my proposal would be to retain only the highest-level property (`SchemaAttribute`'s in the example above).  It would therefore still be inherited by and available on `RelationalColumn` but we would resolve any complexity / search performance / ambiguity caused by the overload.

**Comment by cmgrote** [comment]
Stumbled upon further examples (still between `RelationalColumn` and `SchemaAttribute`):

- `length`
- `isNullable`

**Comment by grahamwallis** [comment]
@cmgrote You may want to look at what I do n the graph repo. Just recently I have been trying to wherever possible collapse a search into a single graph traversal, rather than doing multiple and aggregating the results. 

All property names are qualified by the name of the type that introduces them, in the graph as ReferenceablexqualifiedName, for example. Duplication of property names up and down the supertype/subtype hierarchies (which I refer to as vertical duplication) is fairly easy to deal with (the graph repo always uses the highest definition in the tree). Duplication across the tree is harder. This is where two types (or more than two, in quite a few cases!), that are not supertype/subtype related, each independently introduce a property with the same name. In a query that refers to the unqualified name of such a property, that property name can be mapped to multiple qualified property names. If the property types are different (e.g. integer vs string) then they are easily distinguished, but that's not always the case (examples include name and description, which are always strings). I have to be very careful in the multi-mapping case otherwise the graph traversals could relive incorrect results. I came up with 3 strategies, but the most preferred is not possible yet due to a limitation in JG. Of the other two I have implemented the simpler of the two, on the basis that I think the more preferred strategy will become possible in the near future. The associated graph repo issue is #4683.

**Comment by cmgrote** [comment]
Agreed on 18/02 call that we should remove the lower-level property overrides from the type archive where they were introduced (2.1?) -- and then ensure that this does not cause any breakages well in advance of the next release.
