### ISSUE TITLE
omag-server-platform-transport-level-security observations

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#4670]
Looking at file : omag-server-platform-transport-level-security. I notice:
1)
TS=${BUILD}/open-metadata-implementation/server-chassis/server-chassis-spring/src/main/resources/keystore.p12
should it be 
TS=${BUILD}/open-metadata-implementation/server-chassis/server-chassis-spring/src/main/resources/truststore.p12

2) It contains 
VER=2.4-SNAPSHOT
3) I suggest the example launch script be supplied as a separate file rather than embedded in documentation. 
4) I suggest the references to gensamplecerts.sh and the openssl config be links.

**Comment by planetf1** [comment]
Thanks for the feedback
1. Good spot. I'd updated the local file I've used but not the one in the build
2. Will update
3,4. the section on creating certs has a link - but it's to the directory so when rendered goes to a short readme rather than each file, which would definately be easier - but going to the file then causes the browser to download in github pages. will try and figure a better way ... . And may remove the inline code. In fact just removing that readme may help as at least user will see a directory listing

I also noticed that the shipped certs currently are not those generated by this script. This should be corrected across the chassis, spring ui, and react ui.

**Comment by planetf1** [comment]
I've made some updates to the docs & script
I'm also checking in the same certs for now -- until we move out to a new location

Certificate generation is somewhat complex. We need to manage these certs carefully, and in particular the CA needs to be available to all components across repositories for demo use.

**Comment by planetf1** [comment]
Currently .p12 files are found in base egeria at:
```
./truststore.p12
./keystore.p12
./open-metadata-implementation/user-interfaces/ui-chassis/ui-chassis-spring/src/main/resources/truststore.p12
./open-metadata-implementation/user-interfaces/ui-chassis/ui-chassis-spring/src/main/resources/keystore.p12
./open-metadata-implementation/server-chassis/server-chassis-spring/src/main/resources/truststore.p12
./open-metadata-implementation/server-chassis/server-chassis-spring/src/main/resources/keystore.p12
```
In fact all files are the same except truststore.p12, and none are as intended following the model of a clear
 - file containing the relavant CA for verification
 - file containing the relevant cert for sending
 
 ie confused.
 
 Most likely any references to a name 'truststore' means use of the CA, whilst keystore means the use of a key.
 I will update the files with relevant selections from those generated by the updated script, and place the client key in the root as keystore.p12
 I will then test

**Comment by planetf1** [comment]
See #4722 for example certs
