### ISSUE TITLE
FVT Server configuration and data appearing in distribution

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria#4699]
It looks like the files created by the FVTs are being included in the assembly.
<img width="300" alt="Screenshot 2021-02-15 at 20 24 09" src="https://user-images.githubusercontent.com/12354195/107990404-53826c80-6fcc-11eb-9cb1-690e61ec41eb.png">

**Comment by planetf1** [comment]
Good spot. They shouldn't be there.
Could add a simple exclusion, though I would like to change the working directory the FVTs use, to be unique per test (this will also address a problem with the gradle based FVTs which are currently a draft PR)

**Comment by planetf1** [comment]
Currently fixing this by ensuring the working directory for each test is unique.. ie written to the target dir for the test in question. 

This means
 * Test could run in parallel
 * Each test has it's own clean repo/config
 * No contamination in the assembly/distribution directory (it was the latter that was contaminated, the .gz was fine)
 
 In the process observed that the tests depend on multiple sources of data matching
  a) Ports, URL , id etc from the pom.xml (and in future gradle)
  b) Similar within the .groovy file
  c) Java code which was using FVTConstants
  
 In fact c) was one cause of the gradle tests failing (still a PR). 
 
 I propose to modify the test driver code to use parms passed through from the test driver (surefire or gradle) rather than hardcoded values. This can be via properties. However in the case where those properties aren't passed we can use the current FVTConstants as defaults.
 
 This should allow for future parallelism, better isolation, easier modification and should work for maven and gradle.
