### ISSUE TITLE
Error while trying to explore entity using REX in Egeria polymer UI

### ISSUE THREAD

**Issue by lpalashevski** [odpi/egeria#4836]
Entity is present in external repository (IGC) member of the same cohort via repository proxy. 
Enterprise option is selected. Entity found by GUID.

1. Get entity by GUID, click to get entityDetails
```
Mar 02 09:28:49 xxxxxxxxxxxxxxx omp-app[93158]: 2021-03-02 09:28:49.101 DEBUG [http-nio-127.0.0.1-8080-exec-2] [o.o.o.a.r.g.r.GraphOMRSMetadataStore] --- getEntityDetailFromStore found vertex v[6123672]
Mar 02 09:28:49 xxxxxxxxxxxxxxx omp-app[93158]: 2021-03-02 09:28:49.101 DEBUG [http-nio-127.0.0.1-8080-exec-2] [o.o.o.a.r.g.r.GraphOMRSMetadataStore] --- getEntityDetailFromStore found entity vertex v[6123672]
Mar 02 09:28:49 xxxxxxxxxxxxxxx omp-app[93158]: 2021-03-02 09:28:49.101  WARN [http-nio-127.0.0.1-8080-exec-2] [o.o.o.a.r.g.r.GraphOMRSMetadataStore] --- getEntityDetailFromStore found entity but it is only a proxy, guid data_file_field@68e36496-7167-4af7-abdd-a0cd36e24084:b1c497ce.60641b50.5ocn4dlja.uij9v5h.ak48kp.peuvbhdfa41c751pv0e18

```
2. Clicking the Explore option
```
Mar 02 09:28:59 xxxxxxxxxxxxxxx omp-app[93158]: 2021-03-02 09:28:59.219 DEBUG [http-nio-127.0.0.1-8080-exec-4] [o.o.o.a.r.g.r.GraphOMRSMetadataStore] --- getSubGraph entityGUID = data_file_field@68e36496-7167-4af7-abdd-a0cd36e24084:b1c497ce.60641b50.5ocn4dlja.uij9v5h.ak48kp.peuvbhdfa41c751pv0e18, entityTypeGUIDs = null, relationshipTypeGUIDs = null, limitResultsByStatus = null, limitResultsByClassification = null, level = 1
Mar 02 09:28:59 xxxxxxxxxxxxxxx omp-app[93158]: 2021-03-02 09:28:59.220 DEBUG [http-nio-127.0.0.1-8080-exec-4] [o.o.o.a.r.g.r.GraphOMRSMetadataStore] --- getSubGraph found root entity vertex v[6123672]
Mar 02 09:28:59 xxxxxxxxxxxxxxx omp-app[93158]: 2021-03-02 09:28:59.220 ERROR [http-nio-127.0.0.1-8080-exec-4] [o.o.o.a.r.g.r.GraphOMRSEntityMapper] --- mapVertexToEntityDetail an EntityProxy cannot be retrieved as an EntityDetail null
Mar 02 09:28:59 xxxxxxxxxxxxxxx omp-app[93158]: 2021-03-02 09:28:59.220 ERROR [http-nio-127.0.0.1-8080-exec-4] [o.o.o.a.r.g.r.GraphOMRSMetadataStore] --- getSubGraph caught exception whilst trying to map entity with GUID data_file_field@68e36496-7167-4af7-abdd-a0cd36e24084:b1c497ce.60641b50.5ocn4dlja.uij9v5h.ak48kp.peuvbhdfa41c751pv0e18, exception OMRS-GRAPH-REPOSITORY-400-015 The attempt to retrieve an entity with GUID null found an entity proxy in mapVertexToEntityDetail method of class org.odpi.openmetadata.adapters.repositoryservices.graphrepository.repositoryconnector.GraphOMRSEntityMapper to open metadata repository omas-server
Mar 02 09:28:59 xxxxxxxxxxxxxxx omp-app[93158]: 2021-03-02 09:28:59.220 ERROR [http-nio-127.0.0.1-8080-exec-4] [o.o.o.a.r.g.r.GraphOMRSMetadataStore] --- getSubGraph caught entity not known exception from subgraph traversal OMRS-GRAPH-REPOSITORY-400-004 The attempt to retrieve an entity with GUID data_file_field@68e36496-7167-4af7-abdd-a0cd36e24084:b1c497ce.60641b50.5ocn4dlja.uij9v5h.ak48kp.peuvbhdfa41c751pv0e18 failed in getSubGraph method of class org.odpi.openmetadata.adapters.repositoryservices.graphrepository.repositoryconnector.GraphOMRSMetadataStore to open metadata repository omas-server
```

UI messages as result of step 2:

`Error occurred: The UI tried to use an unsupported function`
`Event :pre-traversal-not-loaded from graph-controls`

**Comment by lpalashevski** [comment]
@grahamwallis can you please take a look at the errors and see if you can spot something that will help with troubleshooting further?

**Comment by grahamwallis** [comment]
Sure.

The entity is only present in the graph repo as an EntityProxy. It can't be retrieved as an EntityDetail - this is logged during attempt to getEntity by GUID and in the attempt to getSubGraph. After logging that it "found entity but it is only a proxy..." the Graph Repo will have thrown an EntityProxyInlyException (since it cannot construct an EntityDetail from an EntityProxy because it doesn't have the entity's properties for example. The exception will be captured and passed back to the enterprise connector, which will discount the response from the graph repository - because it is not helpful. Which is why you see the entity returned by the IGC repository proxy.

When you subsequently issue the Traversal operation that too is not possible in the graph repo (because a sub-graph requires a list of EntityDetail instances, so an EntityProy is no use) and it is the response from the IGC repo that you are seeing - which is saying that the IGC repository does not support the graph traversal function.

As discussed on the community call (2nd March 2021), this might be avoidable if replication is used (so the graph repo has a full reference copy) or it could be solvable by an update to Rex to issue getRelationshipsForEntity (instead of getSubGraph).

**Comment by lpalashevski** [comment]
With the latest comments, we can conclude that this expected behaviour with the current implementation. In future if needed we can open new enhancement issue and analyze what it means to update REX and/or the undelraying rest clients used to use getRelationshipsForEntity to achieve similar "Explore" functionallity. Closing this issue.
