### ISSUE TITLE
Add User interface into helm chart for vdc demo

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#508]
Add Any relevant user interfaces into the helm chart for demos

**Comment by planetf1** [comment]
To launch current version:

java -jar open-metadata-implementation/user-interfaces/access-services-user-interface/target/access-services-user-interface-0.3-SNAPSHOT.jar

**Comment by mandy-chessell** [comment]
This is good enough for think - but I will add the client to the open-metadata-assemblies - see #662

**Comment by bogdan-sava** [comment]
Hi Nigel,

I created the PR. 
There are some important properties to be set in order to work.

1. OMAG server where Asset Catalog OMAS is, base URL and server name you configured by admin interface:
```
#asset catalog omas
omas.server.name=omas
omas.server.url=http://localhost:8080
```

2. Authentication still has 2 options switchable by property: in mem h2 db or LDAP
Default is db (suppose to be removed at some point)

```
#Authentication source (posiible values: db,ldap)
authentication.source=db
```
If choose LDAP you have to provide / override:

```
#LDAP authentication
ldap.user.search.base=ou=people,dc=egeria,dc=com
ldap.user.search.filter=uid={0}
ldap.group.search.base=ou=Groups,dc=egeria,dc=com
ldap.group.search.filter=member={0}
ldap.url=ldap://localhost:389
```

**Comment by bogdan-sava** [comment]
Server starts by default on HTTPS on 8443 port, so the url if you are on the same machine, after starts is:

https://localhost:8443
