### ISSUE TITLE
CTS running from notebook showing some issues with retrieving report results

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5085]
In both 2.8 and 2.9 release testing, the CTS notebook has ran tests through to completion. However the last few steps where results have been retrieved have been unreliable.

I have seen hangs for > 20 minutes on the step that retrieves results, and many minutes (still going) when trying to retrieve the report. It took perhaps 5 minutes from a quick check but did finally complete

Doing a REST API call to get the full results ie
```
 http --timeout=600 --pretty=format --verify=no GET https://myctsserver:9443/servers/CTS_Server/open-metadata/conformance-suite/users/garygeeke/report > ~/cts-29mem.txt
 ```
 took around 1m 50s which is typical
 
 This may be down to the revised formatting introduced into the report.
 
 This occurs when running on a well 3 x 16 GB / 4 CPU k8s cluster - though of course the cts is only running in a single pod
 
 This requires more investigation to try to understand the cause - it seems significantly worse then prior to the refactoring

**Comment by cmgrote** [comment]
Just to confirm, we're talking about the `run-conformance-test-suite.ipynb` notebook under `open-metadata-labs/conformance-testing-labs`?

I note that I did migrate this to using the new multiple endpoints rather than the single all-in-one endpoint: I strongly suspect that the piece that is causing the significant delay is the retrieval of the individual test case details.  There are thousands of these (5000), each retrieved from a separate API call, so depending on the overhead of the framework involved in retrieving them and printing out the status of the retrieval (seems far slower in a notebook than elsewhere, for some reason) can indeed take some time...

At the same time, the notebook does not actually make use of the test case details output _at all_...  So I'd be in favour of simply removing the retrieval of the information (it's unnecessary for the notebook) (?)  We could leave the method that does the retrieval there if someone ends up wanting to use it, but there's no real reason to retrieve all of that detail as part of the notebook itself -- just causes such significant delays.

(In fact the same applies to the profile details: these aren't currently used for anything in the notebook either, but at least there are only 16 of those so their retrieval should be relatively quick...)

So we could just comment out / remove all of these lines (in the penultimate code cell):

```python
    profiles = retrieveProfileNames(ctsServerName, ctsPlatformURL)
    profileDetailsDir = cwd + os.path.sep + profileDir
    os.makedirs(profileDetailsDir, exist_ok=True)
    print("Retrieving details for each profile...")
    for profile in profiles['profileNames']:
        profile_details = retrieveProfileDetails(ctsServerName, ctsPlatformURL, profile)
        with open(profileDetailsDir + os.path.sep + profile.replace(" ", "_") + ".json", 'w') as outfile:
            json.dump(profile_details, outfile)
    test_cases = retrieveTestCaseIds(ctsServerName, ctsPlatformURL)
    testCaseDetailsDir = cwd + os.path.sep + testCaseDir
    os.makedirs(testCaseDetailsDir, exist_ok=True)
    print("Retrieving details for each test case...")
    for test_case in test_cases['testCaseIds']:
        test_case_details = retrieveTestCaseDetails(ctsServerName, ctsPlatformURL, test_case)
        with open(testCaseDetailsDir + os.path.sep + test_case + ".json", 'w') as outfile:
            json.dump(test_case_details, outfile)
```

But at a minimum I would recommend we get rid of the following:

```python
    test_cases = retrieveTestCaseIds(ctsServerName, ctsPlatformURL)
    testCaseDetailsDir = cwd + os.path.sep + testCaseDir
    os.makedirs(testCaseDetailsDir, exist_ok=True)
    print("Retrieving details for each test case...")
    for test_case in test_cases['testCaseIds']:
        test_case_details = retrieveTestCaseDetails(ctsServerName, ctsPlatformURL, test_case)
        with open(testCaseDetailsDir + os.path.sep + test_case + ".json", 'w') as outfile:
            json.dump(test_case_details, outfile)
```

**Comment by cmgrote** [comment]
Or if we really want to keep it in the notebook as an example, at the bare minimum we should probably move the lines above to a new code cell at the _very end_ -- after printing out the overall CTS summary. Then at least we have the summary output immediately, rather than waiting 10+ minutes for unnecessary processing to complete when the summary is already available (?)

**Comment by planetf1** [comment]
I think both are needed
 - Show the results that can be obtained quickly first (with appropriate explanation)
 - show the examples of getting the finer grained details since the notebook is meant to help/guide the person using the cts ?
 
 I pull the full details in any case when testing a release - yesterday this took 1:50 which is pretty typical for a single request. It's longer than many may expect, though there's a reference to that in the notebook.
 
 I'm not typically using (nor have tested) the cts client code
