### ISSUE TITLE
RELEASE 2.9 - CTS failures with graph repo (retrievable via GUID)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5086]
Running CTS against the graph repo on a k8s cluster (4x16GB, 4 cpu, openshift) when testing release 2.9 in #5075 resulted
in many failures: (Inmemory did not show these issues)
```
       "testCaseCount": 5017,
        "testFailedCount": 442,
        "testPassCount": 4575,
```

The full report is at https://ibm.box.com/s/gavxl77rfblfmrkdu9pts0cm7bzjm91c

Some of the examples of failures include:
```
                            "repository-relationship-reidentify-06: GroupedMedia relationship retrievable by new GUID."
```
In the cases I've looked at so far the issues appear to relate to GUIDs

**Comment by cmgrote** [comment]
I've had a look at the code, but am not completely certain I understand where the problem is occurring.

From what I can see:

- The call to `reIdentifyEntity` does not throw any exceptions, and it returns the re-identified EntityDetail
- Inside this method are basically these steps:
   1. Retrieve the existing entity (works, or there would be an EntityNotKnownException which would cause an exception to be thrown out of the CTS itself)
   2. Creates an object representing the delete for the entity being re-identified
   3. Creates an object representing the updated entity, with the new GUID that was provided
   4. Creates an entity proxy representation of this updated entity
   5. Searches for all relationships linked to the original entity and points them to the updated proxy (in the graph)
   6. Persists the deleted entity in the graph (original GUID)
   7. Persists the updated entity in the graph (new GUID)

Could it be that there is some deep graph error that isn't being propagated outwards at step (vii), since the deleted entity (original GUID) and the new entity (with the new GUID) will actually have the same `qualifiedName`?  (Raises another question, assuming this is the problem: is this truly an invalid scenario (strictly unique constraint), or actually valid, since one instance is actually deleted? Maybe less of a concern for a repo that doesn't support history, but I would imagine a repo that _does_ support history needs to be able to store the same `qualifiedName` against the same entity type + metadata collection ID but different GUIDs in cases where there were deletions -- further that there could even be multiple deleted instances with the same `qualifiedName` and different GUIDs over time (?))

Perhaps for repositories with no history (like the graph store) we should not do a soft-delete of the original entity but actually do a full purge (?)

It would also appear to me that there is no surrounding transaction / commit-point to all of these various steps. I don't know enough about the repository to know if there is some potential problem or race condition if e.g. the relationships are pointed at a proxy representation (v) that has not actually been persisted in the graph yet (vii). (I'm not sure if there is any sort of constraint check at persistence time, or if this is only resolved at read-time?)

I'll leave aside for the moment the potential issue that without a wrapped transaction around all of these operations, this has the risky potential of corrupting the persisted metadata anyway -- since we could be in a state where some of the relationships are re-pointed but some other exception or error occurs that means the entity with the updated GUID (to which these relationships now point) does not end up being persisted... (Which given the failed CTS test case is precisely what appears to be happening, presumably without any audit logged error or exception message anywhere in the log?)

**Comment by planetf1** [comment]
I've added the full output log from the platform running both the CTS and SUT servers. Same folder.

**Comment by planetf1** [comment]
The only stacktraces appear to be from removing a non-existant classification. This probably doesn't represent an error in the SUT - though it may be arguable whether there should be a stacktrace logged. 

@mandy-chessell @cmgrote I'll try and run a second time (same infra) but will leave the existing environment in place in case you need more info/logs/REST api queries to be done.

**Comment by cmgrote** [comment]
It looks like a pretty consistent error, so I would expect it is reproduced...  could you run this next one with more verbose logging (debug level on at least the graph repo packages)?  It looks like there are various debug log statements in there which could be useful to see...

**Comment by planetf1** [comment]
I've already kicked it off the same way first - I agree I think it's looking repeatable but will be an extra check,
The issue with debug level could be the performance impact but can try later 
We may also need to figure out running a subset of the tests so that we can get feedback much more quickly

**Comment by planetf1** [comment]
As a slight aside - @mandy-chessell the graph repo is reporting many of these (see full log)
```
Mon Apr 26 17:06:20 GMT 2021 CTS_Server Exception OMRS-AUDIT-9011 Supplementary information: log record id 9ceb95e9-3437-4871-9c1c-447a5b922089 org.odpi.openmetadata.repositoryservices.ffdc.exception.TypeErrorException returned message of OMRS-REPOSITORY-400-048 A purgeClassificationReferenceCopy request has been made to repository CTS_Server to remove a non existent classification CloudTenant from entity 6483612e-1c7e-4a12-afe1-c073701c0eb0 and stacktrace of
```
which the inmem repo does not
As a purge this does not look like the cause of the failure to me, but I did note a change in this area in https://github.com/odpi/egeria/commit/52e088bd4734b53c8a57dd33a1dadf43869e6325#diff-2f1f656975d9e860f500b614fcffc14868ec1631b705dc0d5e95f5dac7909fa4

**Comment by cmgrote** [comment]
I have been seeing those `purgeClassificationReferenceCopy` stacktraces since 2.8 across CTS in both Graph and Crux connectors (had assumed it would be the same in-mem but didn't test it).  They don't seem to impact the CTS so I was assuming they were "expected" exceptions -- not an actual error themselves, but probably something that shouldn't be printed out in a stacktrace (?)

**Comment by cmgrote** [comment]
In regards to restricting the tests, the CTS tests should be fairly self-contained (creating the objects they need and deleting and purging them afterwards) -- so to just re-test these problematic ones, you would probably want to run the entire `Reidentify instance` profile (since the problem seems to be for both entities and relationships).

**Comment by planetf1** [comment]
A second test run ended with the same failures.

**Comment by mandy-chessell** [comment]
I can not access the box note to see the test case report or the console.  The fragment of the report show does not include the test caseId so there is not much I can do at this point.

**Comment by mandy-chessell** [comment]
I can not do anything with the report of message `OMRS-AUDIT-9011` because the stack trace is missing from the message.
Also it is important to include the message that preceeds it because `OMRS-AUDIT-9011` is the supplementary information for the previous message.

**Comment by cmgrote** [comment]
So to the CTS failure itself, I've run locally with debug-logging turned on and it would appear that the failing assertion is most likely the assertion in the CTS that the re-identified object returned by the call to `reIdentify[Entity|Relationship]` does not equal the entity pulled back from the repository by a call to `getEntityDetail` with its new GUID.

I suspect this is because we've introduced the new `reIdentifiedFromGUID` property on the `InstanceHeader`, which I am only now seeing that the graph repository does not appear to map dynamically (only the `InstanceProperties` appear to be dynamically mapped for persistence).

I therefore suspect that the inequality is because the `EntityDetail` that is being returned from the `reIdentifyEntity` method _has_ its `reIdentifiedFromGUID` populated, while the one retrieved back from the graph (persistence) does _not_ have this property since it has not been explicitly mapped as part of the graph repository's non-InstanceProperties mappings.

Looking at correcting that now to re-test...

**Comment by cmgrote** [comment]
Have corrected in the following locations, re-building and then re-testing:

- GraphOMRSConstants - adding constants for the property name and persistence-layer keys
- GraphOMRSGraphFactory::initialize - building indexes for both entities and relationships on this new property
- GraphOMRSEntityMapper - mapping the new property to and from persistence in Janus (for entities)
- GraphOMRSRelationshipMapper - mapping the new property to and from persistence in Janus (for relationships)

**Comment by planetf1** [comment]
Yes - if that works I can cherry pick and retest on master. Thanks for the update
Was taking me a while to work my way around the code, figure out running a subset of tests,and local machine really struggles with resources

**Comment by cmgrote** [comment]
Meh, it was kind of cold in my house today anyway, so my 🔥 machine is helping keep me warm 😉  I'm running a full CTS just to confirm, but the reidentify test cases seem to be succeeding now where they were previously failing, so 🤞

**Comment by planetf1** [comment]
Can you post back (and/or merge) once you're happy the full CTS runs to completion, then I will merge the release fix
(I'll do the cherry-pick shortly and add/redo if new commits needed)
Thanks!

**Comment by cmgrote** [comment]
Looks like it works now (tested with the changes in #5095 directly in the `egeria-release-2.9` branch, locally):

```
=======================================
 Open Metadata Conformance Test Report
=======================================
Contacting conformance suite server: cts (https://localhost:9443)

Saving full profile details into 'profile-details' directory...
Summary of profile results:
... Metadata sharing: CONFORMANT_FULL_SUPPORT
... Reference copies: CONFORMANT_FULL_SUPPORT
... Metadata maintenance: CONFORMANT_FULL_SUPPORT
... Dynamic types: UNKNOWN_STATUS
... Graph queries: CONFORMANT_FULL_SUPPORT
... Historical search: CONFORMANT_NO_SUPPORT
... Entity proxies: CONFORMANT_FULL_SUPPORT
... Soft-delete and restore: CONFORMANT_FULL_SUPPORT
... Undo an update: CONFORMANT_NO_SUPPORT
... Reidentify instance: CONFORMANT_FULL_SUPPORT
... Retype instance: CONFORMANT_FULL_SUPPORT
... Rehome instance: CONFORMANT_FULL_SUPPORT
... Entity search: CONFORMANT_FULL_SUPPORT
... Relationship search: CONFORMANT_FULL_SUPPORT
... Entity advanced search: CONFORMANT_FULL_SUPPORT
... Relationship advanced search: CONFORMANT_FULL_SUPPORT
Saving full test case details into 'test-case-details' directory (can take 1-2 minutes)...
Summary:
... number of tests: 5017
... number of tests passed: 5017
... number of tests failed: 0
... number of tests skipped: 0

Congratulations, technology under test is conformant
```
