### ISSUE TITLE
How to form a search query correctly? 

### ISSUE THREAD

**Issue by Inventoroz** [odpi/egeria#5239]
There is such an object 
[response_1622193633037.txt](https://github.com/odpi/egeria/files/6559929/response_1622193633037.txt)

I am creating a search request
https://localhost:9443/servers/uad1/open-metadata/repository-services/users/admin/instances/entities/
body:
```
{
  "class": "EntityFindRequest",
  "offset": 0,
  "pageSize": 0,
  "matchProperties": {
    "conditions": [
      {
        "property": "type",
        "operator": "EQ",
        "value": {
          "class": "StructPropertyValue",
          "instancePropertyCategory": "STRUCT",
          "attributes": {
            "class": "InstanceProperties",
            "instanceProperties": {
              "typeDefName": {
                "class": "PrimitivePropertyValue",
                "instancePropertyCategory": "PRIMITIVE",
                "typeGUID": "b34a64b9-554a-42b1-8f8a-7d5c2339f9c4",
                "typeName": "string",
                "primitiveDefCategory": "OM_PRIMITIVE_TYPE_STRING",
                "primitiveValue": "UAD_required_fields"
              }
            },
            "propertyCount": 1,
            "propertyNames": [
              "typeDefName"
            ]
          }
        }
      }
    ],
    "matchCriteria": "ALL"
  }
}
```
Response:
```
{
  "class" : "EntityListResponse",
  "relatedHTTPCode" : 200,
  "offset" : 0,
  "pageSize" : 0
}
```

Tell me what is wrong with the request?

**Comment by cmgrote** [comment]
Hi @Inventoroz -- can I clarify the intent of your search?  For example, are you trying to find all entities of the type `UAD_required_fields`?

To do that, you should be able to run a search like the following -- this says "find me all entities of the type `uad00000-0000-0000-0000-reqfields000`", which I note from your provided payload is a custom-defined type that extends `GlossaryTerm`.):

```
{
  "class": "EntityFindRequest",
  "typeGUID": "uad00000-0000-0000-0000-reqfields000"
}
```

**Comment by Inventoroz** [comment]
Hi @cmgrote 
I need to find all entities whose typeDefName is equal to UAD_required_fields.
In the file, I have attached an object that is definitely there. But when I make a search query, with the settings I indicated above, it is not found

**Comment by cmgrote** [comment]
Does the payload I put in above work for you?  This uses the GUID of the type, rather than its name -- but is the request we would expect for such a search.

This is because the type of a metadata instance (its typeDefGUID, typeDefName) are actually header information for the metadata instance -- not instance properties. We therefore do not expose search against them through conditions (property / operator / value combinations), but only filtering against them based on the typeDefGUID.

Note that you have further options than just searching for a single typeDef as well. For example, this query:

```
{
  "class": "EntityFindRequest",
  "typeGUID": "0db3e6ec-f5ef-4d75-ae38-b7ee6fd6ec0a"
}
```

Will search for all entities whose type (or supertype) is `GlossaryTerm` (typeDefGUID: `0db3e6ec-f5ef-4d75-ae38-b7ee6fd6ec0a`): this would include both entities of your custom `UAD_required_fields` type as well as native Egeria `GlossaryTerm` entities.

This query would search for any entities that are either your custom `UAD_required_fields` type (typeDefGUID: `uad00000-0000-0000-0000-reqfields000`), or an Egeria native `Database` type (typeDefGUID: `0921c83f-b2db-4086-a52c-0d10e52ca078`).

```
{
  "class": "EntityFindRequest",
  "typeGUID": "a32316b8-dc8c-48c5-b12b-71c1b2a080bf",
  "subtypeGUIDs": [ "uad00000-0000-0000-0000-reqfields000", "0921c83f-b2db-4086-a52c-0d10e52ca078" ]
}
```

... because it is stating that the search should be for all `Referenceable`s (`"typeGUID": "a32316b8-dc8c-48c5-b12b-71c1b2a080bf"), but limited only to the `UAD_required_fields` and `Database` subtypes of `Referenceable`.

**Comment by Inventoroz** [comment]
And if I just do not know these guides, but I only know the name typeDefName. Do I understand correctly that it will not work to implement the search in this way?
And you can even then say, but how then to understand what are the attributes and they will be searched for, and what will not be?

**Comment by cmgrote** [comment]
> Do I understand correctly that it will not work to implement the search in this way?

Yes, that is correct: the search interface currently only works based on the GUIDs and not the names of TypeDefs.

The specific properties that can be included in the search depend on the type(s) being searched: whoever / whatever is running the search will need to be sufficiently familiar with the type(s) being searched to know what properties are of interest to search, or to use the ...ByPropertyValue methods which will search all string properties on the type(s) being searched.

This all relates to the base MetadataCollection search interfaces -- at the lower OMRS level.  If your scenario is to generally search against a specific area (like glossary information), you may want to investigate whether there are alternative search interfaces at the OMAS level that simplify this for you.

**Comment by Inventoroz** [comment]
thanks for the clarifications
