### ISSUE TITLE
Swap the isatypeof type ends around 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#5305]
The isatypeof relationship type has the ends the wrong way round. The direction of relationship should point from end1 to end2. So in this inheritance case the UML arrow should point from the child to parent.

Currently TermISATypeOFRelationship is defined with end1 as supertypes and end2 as subtypes.

It should be the other way round. 

we are also assessing whether we need ISA as well as TermISATypeOFRelationship

**Comment by davidradl** [comment]
@cmgrote If we were to change this would this cause an issue for any code you are aware of? 
@mandy-chessell as discussed

Any concerns?
@planetf1 
@CDaRip2U 
@lpalashevski 

If not we may need to deprecate and introduce a newly named relationship with the ends thew other way round

Issue https://github.com/odpi/egeria/issues/5304 sets the spine object classifications appropriately when the relationship is created. We are holding off from implementing this for isatypeof until this issue is resolved one way or another

**Comment by cmgrote** [comment]
Are you talking about changing the UML diagram or the relationship itself?

If the latter, is there a way to do this via a TypeDefPatch?

If not, wouldn't this be a breaking change to the types (not backwards compatible, so any existing repository with such relationships will be broken), and therefore is not a permitted change to the type?

**Comment by davidradl** [comment]
@cmgrote thanks for your feedback and questions.

 yes the relationship itself
yes this would be via a TypeDefPatch
yes it would be a breaking change - if anyone is using it / be impacted by it. Pragmatically if It is not being used then we could update it in a TypeDefPatch . I was hoping to assess the impact by tagging everyone.   

If we see there is an impact then this would be a breaking change, so we would deprecate and create a newly named type - maybe isatype.

**Comment by cmgrote** [comment]
I am surprised we are considering a breaking change to the types -- it seems to me that there are countless previous examples where we wanted to make a breaking change to a type to "fix" one oversight or another, but did not explicitly because we cannot be sure we have visibility over all users that might already be using the type.  So I don't see how this situation is different (?)

Changing code in connectors or proxies is easy enough, but this doesn't address the migration of existing content in a repository.  We'd need upgrade utilities in all the persistent repos (Graph, Crux, etc) to apply such breaking changes, and would presumably need a major release to be able to switch all OMASes that interact with the type to only use the newer version of it (not have to handle previous versions), or what would happen in a cohort that had different repositories some of which have the old relationship going in the opposite direction and others in the new direction (?)

**Comment by davidradl** [comment]
@cmgrote as per todays call - I will deprecate the existing relationship and introduce a new one with a new name with the ends the other way round.

**Comment by davidradl** [comment]
I am coding this fix up. I am deprecating IsATypeOf and introducing a new Relationship, which also needs unique end names or it will clash with isatypeof.

I propose a new relationship name of ObjectInheritanceRelationship with ends of 

End1
            final String                     end1AttributeName            = "Inherited";
            final String                     end1AttributeDescription     = "Inherited (Subtypes) for this object.";
            final String                     end1AttributeDescriptionGUID = null;
 End2
            final String                     end2AttributeName            = "InheritedFrom";
            final String                     end2AttributeDescription     = "Inherited from type (Supertypes) for this object.";


Any better suggestions or are we ok with this? @cmgrote @mandy-chessell @planetf1 @lpalashevski . I will not merge this until after the semantic workgroup meets; to check there are no concerns.
