### ISSUE TITLE
Doc update: max page size

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#5373]
**max-page-size**

When testing I created a server from scratch in postman.

As per https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/user/configuring-omag-server-basic-properties.html I tried to set the page size:
```
POST https://7ca4c237-eu-gb.lb.appdomain.cloud:9443/open-metadata/admin-services/users/garygeeke/servers/integration/max-page-size?limit=%22100%22
```
Note the '%22' because I had specified the request as:
```
{{baseURL}}/open-metadata/admin-services/users/{{userId}}/servers/{{integrationservername}}/max-page-size?limit="{{maxpagesize}}"
```

The result is this confusing message (as often the case when using jackson:
```
{
    "timestamp": "2021-06-16T12:36:48.088+00:00",
    "status": 400,
    "error": "Bad Request",
    "path": "/open-metadata/admin-services/users/garygeeke/servers/integration/max-page-size"
}
```

The reason was in fact the use of " around the number - this is wrong, and so the doc should be updated to give the example as:
```
POST {platformURLRoot}/open-metadata/admin-services/users/{adminUserId}/servers/{serverName}/max-page-size?limit={maxPageSize}
```

**server-url_root, event-bus**

The page at https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/user/configuring-local-server-url.html does not give a REST example for configuring server root, which would be useful

Additionally the server-root & event bus configuration at https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/user/configuring-event-bus.html is needed for an integration server - but this is not clear in the documentation which suggests it's only for repositories. In fact the event bus and cohort membership is of course crucial for an integration server to participate in an egeria ecosystem

**Comment by planetf1** [comment]
Note that the quotes do work for string values - but not numeric

**Comment by mandy-chessell** [comment]
What do you mean by an integration server?

The integration daemon does not need the event bus, nor the  server root url
The engine host does not need them either.

Are the admin services insisting on it?

**Comment by mandy-chessell** [comment]
Agree that the quotes need to be removed from the max page size on this page:

https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/user/configuring-omag-server-basic-properties.html

The event bus issue is curious because the event bus is not configured for the integration daemon nor the engine host in the lab notebooks - it was one if the things I checked.  So I do not understand how this is working in the notebooks and not via postman.  If it insists on the event bus config for the integration daemon and engine host then we have a bug since it gets all of its event bus config from the connected metadata server.

I will investigate.

So assuming we fix the code, the doc change seems to required that the event bus configuration needs to be moved to the second list `Specialist configuration for specific types of OMAG Servers` and should only be set for cohort members, OLS and Data Engine Proxy.

-----
I was looking on the integration daemon configuration page - https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/concepts/integration-daemon.html
and it does not require the event bus.

Both the Engine Host - https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/concepts/engine-host.html -
and View Server - https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/concepts/view-server.html
are OK too.

The documentation for the Data Engine Proxy - https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/concepts/open-lineage-server.html and
Open Lineage Server - https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/concepts/open-lineage-server.html is limited and needs improving.

**Comment by mandy-chessell** [comment]
There is a description of the Data Engine Proxy configuration on this page https://egeria.odpi.org/open-metadata-implementation/governance-servers/data-engine-proxy-services/

Does not appear to need the event bus.

Similarly, there is configuration description for the OLS here:
https://egeria.odpi.org/open-metadata-implementation/governance-servers/open-lineage-services/docs/configuration/

And no event bus is needed.

**Comment by planetf1** [comment]
I've repeated again and what I find is
 - Just configuring the integration - fails with `OMAG-ADMIN-400-010 The OMAG server integration has been passed a configuration document with no open metadata repository services configuration`
  - noting the extra detail on the user action - `"exceptionUserAction": "Use the administration services to add the repository services configuration.  At a minimum, configure the audit log.  If this server is to be a cohort member, then there are choices to also configure the local repository, enterprise repository services and the cohort services."`
  - Configure the audit log
  - server will start
  
  Before I did the other requests which had the *side-effect* of configuring the audit log, which is why the integration daemon could then start
  
  As I initially suspected the root cause is the clarification needed on the docs in terms of what is mandatory/optional for each type of server

**Comment by planetf1** [comment]
One other question is whether there is an inconsistency here in requiring the audit log setting for the integration daemon, but it not being needed for cohort members (though I can see why it is done under the covers).

**Comment by mandy-chessell** [comment]
That is correct - it is necessary to configure the audit log for all server types.

**Comment by mandy-chessell** [comment]
Actually the default audit log is set up when any part of the repository services is set up.  If you were setting up a server properly - you would probably set multiple audit log destinations.

**Comment by mandy-chessell** [comment]
I can not recreate the problem where the integration daemon needs the event bus configured. I have just created a server with the default audit log and the database integrator OMIS enabled and it starts ok.  What am I missing?

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/java -Dserver.port=9443 -Dloader.path=lib -Dfile.encoding=UTF-8 -jar /Users/mandy-chessell/CloudStation/Drive/Code/ODPi/egeria-code/egeria/open-metadata-distribution/open-metadata-assemblies/target/egeria-2.11-SNAPSHOT-distribution/egeria-omag-2.11-SNAPSHOT/server/server-chassis-spring-2.11-SNAPSHOT.jar
 Project Egeria - Open Metadata and Governance
    ____   __  ___ ___    ______   _____                                 ____   _         _     ___
   / __ \ /  |/  //   |  / ____/  / ___/ ___   ____ _   __ ___   ____   / _  \ / / __    / /  / _ /__   ____ _  _
  / / / // /|_/ // /| | / / __    \__ \ / _ \ / __/| | / // _ \ / __/  / /_/ // //   |  / _\ / /_ /  | /  _// || |
 / /_/ // /  / // ___ |/ /_/ /   ___/ //  __// /   | |/ //  __// /    /  __ // // /  \ / /_ /  _// / // /  / / / /
 \____//_/  /_//_/  |_|\____/   /____/ \___//_/    |___/ \___//_/    /_/    /_/ \__/\//___//_/   \__//_/  /_/ /_/

 :: Powered by Spring Boot (v2.5.0) ::

2021-06-22 18:08:20.928  INFO 23165 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9443 (https)
2021-06-22 18:08:26.852  INFO 23165 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 9443 (https) with context path ''

Tue Jun 22 18:08:22 BST 2021 No OMAG servers listed in startup configuration
Tue Jun 22 18:08:26 BST 2021 OMAG server platform ready for more configuration
Tue Jun 22 18:11:59 BST 2021 cocoMDS9 Startup OMRS-AUDIT-0064 The Open Metadata Repository Services (OMRS) has initialized the audit log for the Integration Daemon called cocoMDS9
Tue Jun 22 18:11:59 BST 2021 cocoMDS9 Startup OMAG-ADMIN-0001 The cocoMDS9 server is configured with a max page size of 1000
Tue Jun 22 18:11:59 BST 2021 cocoMDS9 Startup OMRS-AUDIT-0001 The Open Metadata Repository Services (OMRS) is initializing the subsystems to support a new server
Tue Jun 22 18:11:59 BST 2021 cocoMDS9 Startup OMRS-AUDIT-0007 The Open Metadata Repository Services (OMRS) has initialized
Tue Jun 22 18:11:59 BST 2021 cocoMDS9 Startup OMAG-ADMIN-0100 The governance services subsystem for the Integration Daemon called cocoMDS9 is about to start
Tue Jun 22 18:11:59 BST 2021 cocoMDS9 Startup INTEGRATION-DAEMON-SERVICES-0001 The integration daemon services are initializing in server cocoMDS9
Tue Jun 22 18:11:59 BST 2021 cocoMDS9 Startup OMIS-DATABASE-INTEGRATOR-0001 The database integrator context manager is being initialized for calls to server myMetadataServer on platform https://localhost:9443
Tue Jun 22 18:11:59 BST 2021 cocoMDS9 Error INTEGRATION-DAEMON-SERVICES-0007 The Database Integrator OMIS integration service is configured without any integration connectors
Tue Jun 22 18:11:59 BST 2021 cocoMDS9 Startup INTEGRATION-DAEMON-SERVICES-0040 The integration daemon thread for integration daemon cocoMDS9 has started
Tue Jun 22 18:11:59 BST 2021 cocoMDS9 Startup INTEGRATION-DAEMON-SERVICES-0013 The integration daemon cocoMDS9 has initialized
Tue Jun 22 18:11:59 BST 2021 cocoMDS9 Startup OMAG-ADMIN-0101 The governance services subsystem for the Integration Daemon called cocoMDS9 has completed start up
Tue Jun 22 18:11:59 BST 2021 cocoMDS9 Startup OMAG-ADMIN-0004 The cocoMDS9 server has successfully completed start up.  The following services are running: [Open Metadata Repository Services (OMRS), Database Integrator OMIS, Integration Daemon Services]

```

**Comment by planetf1** [comment]
The scenario is
* Install the 'egeria-base' chart (this basically just deploys one server called 'mds' running all OMASs) but using the custom image from egeria-database-connectors (which just adds the postgres connector into server/lib)
* Config the integration daemon with:

```
{{baseURL}}/open-metadata/admin-services/users/{{userId}}/servers/{{integrationservername}}/integration-services/database-integrator
```
using a body of:
```
{
    "class": "IntegrationServiceRequestBody",
    "omagserverPlatformRootURL": "{{baseURL}}",
    "omagserverName": "{{serverName}}",
    "integrationConnectorConfigs" : 
    [ 
        {
            "class": "IntegrationConnectorConfig",
            "connectorName" : "connectorInstanceName",             
            "connectorUserId" : "{{userId}}",
            "connection" : 
            { 
                "class" : "Connection",
                "userId" : "{{postgresuserid}}",
                "clearPassword":"{{postgrespassword}}",
                "connectorType" : 
                {
                    "class" : "ConnectorType",
                    "connectorProviderClassName" : "org.odpi.openmetadata.adapters.connectors.integration.postgres.PostgresDatabaseProvider"
                },
                "recognizedConfigurationProperties": 
                [
                    "url",
                    "ssl"
                ],
                "configurationProperties":
                {
                    "url": "{{postgresjdbcurl}}",
                    "ssl" : "false"
                }
            },
            "metadataSourceQualifiedName" : "PostgresHostServer",
            "refreshTimeInterval" : "3456", 
            "usesBlockingCalls" : "false",
            "permittedSynchronization" : "FROM_THIRD_PARTY"
        } 
    ] 
 }

```

Start the integration daemon with:
```
{{baseURL}}/open-metadata/admin-services/users/{{userId}}/servers/{{integrationservername}}/instance
```

As mentioned above, the issue here was that the audit log was not **explicitly** setup, whilst when configuring the server as a member of a cohort it IS **implicitly** setup - hence the confusion over the reason, but the root cause remains just clarification needed in the doc as to what is required for an integration server.

**Comment by mandy-chessell** [comment]
This issue has a number of "problems" described and the conversation is getting confused.  This is a summary.

The first problem reported was that the integration daemon required the event bus to be configured.  This should not be the case unless the event audit log destination is required.  **I can not recreate this problem and need further description on how to do this.**

In terms of improving the documentation, I originally thought that the link to configuring the event bus on this page -  https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/user/configuring-an-omag-server.html - should move to the optional list.  However I realize this page is correct since the event bus may be needed if the event audit log destination is used.  Since setting up the event bus has no effect on servers that do not need it, the best option is to improve the description of the event bus configuration page to allow people to make a better decision on whether they need to fill it in or not.

The second problem reported is that if the audit log is not configured, a server does not start.  This is intended design.  There is a clear error message shown explaining the problem and the description of every type of server configuration includes a link to configuring audit log.  **I need more explicit information on how to change the documentation because it seems there is no problem there.**

Although every server type needs the audit log to be configured, there is a difference between the servers that just use the repository services for the audit log (view servers and governance servers) and the cohort members that also may set up local repositories and access to cohorts in that the default repository services configuration sets up the audit log.  This means that when configuring the local repository or the cohort, the default audit log destination is added automatically.   This gives the impression that the audit log does not need to be configured.  However, the default audit log is only the console and suitable only for dev/test.  This is why the metadata server, metadata access point and repository proxy all include links to setting up the audit log in their configuration descriptions in the admin guide.

If we wanted to make this consistent, it is possible to either:
* Remove the setting up of the default audit log when any part of the repository services is configured so that it must be set up explicitly for all server types.
* Automatically set the default audit log in any server

The first option is the most correct since we want administrators to think about the audit log destinations.  However, it may create a regression in existing operations.

The second option makes all server types consistent, which has some value, but reinforces the belief that the audit log can be ignored which in unfortunate.

**Comment by planetf1** [comment]
> The first problem reported was that the integration daemon required the event bus to be configured. This should not be the case unless the event audit log destination is required. 

Agreed, I think we've described the scenario, confusion, and expected behaviour above.

> The second problem reported is that if the audit log is not configured, a server does not start. This is intended design. 
This was never a problem as such. I did fall into this trap first time I tried to configure the server, but immediately referred back to the documentation which is what then led to the first issue mentioned. I summarised this to explain how a user may have got into this situation, as I did, so we can understand where the problem originates and how to ensure they understand the intended design.

The root cause is confusion from the docs which is why the issue is prefixed Doc Update. After clarifications, I do not have concerns about the behaviour here.

Whilst the behaviour of the setting of the audit log differs, I would suggest not changing it to potentially affect existing users, but rather to note it's behaviour in the documentation including the caveat you mentioned.

Though it's more verbose/repetitive, I wonder if the simplest approach here is to explicitly list the steps at https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/user/configuring-an-omag-server.html independently for each server type in text

As an alternative we could create a TABLE with a matrix of steps vs server type.

In both cases the step remains a common link (with those pages already existing) so there's no duplication of the detailed content. In those detailed pages, optionally we could include 

Needed-by: Metadata server, Integration Daemon

or similar, which would provide additional clarity. Not essential though

We could add a footnote to clarify the audit log configuration when a cohort membership is defined

Finally we need to do the quote removal on page size.

I am happy to make these changes and propose a PR if that's easiest.

**Comment by mandy-chessell** [comment]
> Though it's more verbose/repetitive, I wonder if the simplest approach here is to explicitly list the steps at https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/user/configuring-an-omag-server.html independently for each server type in text

I do not think this is a good idea - there is already a page for each type of server that lists the configuration steps - I would prefer to remove the list of configuration steps from https://egeria.odpi.org/open-metadata-implementation/admin-services/docs/user/configuring-an-omag-server.html since it is not helping.  I will replace the list with a list of server types to force people to the right pages.

**Comment by planetf1** [comment]
I think the updates to the docs now make it much clearer to see what needs to be configured for what, and the issue with pageSize is fixed.
As such, closing
