### ISSUE TITLE
Ensure `findEntitiesBy...` methods walk the type hierarchy

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria#546]
To track the assurance that our `findEntitiesBy...` methods walk the the type hierarchy when searching, so if a request is made for eg. `Asset` we also search across all sub-types of `Asset` as well.

@mandy-chessell did you mentioned there were some "helpers" available / in the works for this?

**Comment by cmgrote** [comment]
@grahamwallis can you update this issue when you've updated your "managed fork"?  That'll be my trigger to have a look at how you're handling the walking, so I can follow the same approach on the IGC side =)

**Comment by grahamwallis** [comment]
Managed fork code is updated to include subtypes on all of:
fndEntitiesByProperty
fndEntitiesByPropertyValue
fndEntitiesByPropertyByClassification
The approach I have used is to check whether a typeGUID is specified. If no type is specified we will search all types, so there is no sub-type analysis to perform. If a typeGUID is specified, then  check each known type to see if it is 'aTypeOf' the expected (specified) type. I issue searches across the matching sub-types and aggregate the results into a single result set. 
For example, suppose you asked to findEntities specifying the typeGUID for 'Asset', the connector code will find all the subtypes of Asset (e.g. Process is one) and will issue type-specific searches for Asset, Process and any other subtypes of Asset. 
Why have I done it that way? Because I do not want all the types present in an Atlas repository to show up - only the Egeria (open) types; and because by performing the sub-type aggregation in the connector the code is portable across repositories that might or might not support sub-type searches. (Atlas does have an option for including sub-types, but not all repos do).
Hope that helps - if anything is not clear let me know - happy to help!
Cheers
  Graham

**Comment by mandy-chessell** [comment]
I wonder if we should cache subtype lists for each typedef?

**Comment by grahamwallis** [comment]
That would potentially be useful - although see issue #573 in which the superType lists don't appear to be working correctly. I think that attempts to do something similar but the lists are not complete. I haven't had time to investigate why yet.
