### ISSUE TITLE
Why does Digital Architecture OMAS not validate name uniqueness when updating validvalue? 

### ISSUE THREAD

**Issue by Inventoroz** [odpi/egeria#5475]
There are 2 entities, where initially each has its own unique name 
[set1.json.txt](https://github.com/odpi/egeria/files/6789234/set1.json.txt)
[set2.json.txt](https://github.com/odpi/egeria/files/6789233/set2.json.txt)

Then I execute a name update request on entity 2 and specify the name as for entity 1 
```
POST https://172.22.100.227:9443/servers/uad1/open-metadata/access-services/digital-architecture/users/admin/valid-values/61f5eda9-aa77-4261-888f-9848b4024caa/update
{
  "class" : "ValidValueProperties",
  "qualifiedName" : "this unique name1",
  "isDeprecated" : false
}
200 OK 
{
  "class" : "VoidResponse",
  "relatedHTTPCode" : 200
}
```
The request was successful, and 2 entities now have the same name as 1 
[set2_after_update.json.txt](https://github.com/odpi/egeria/files/6789268/set2_after_update.json.txt)

**Comment by mandy-chessell** [comment]
Its a very good question - it should do - it is a bug.  And a generic one that impacts many OMASs.  The problem is in the generic handlers.  They validate the unique properties on create but not on update.  The updateBeanInRepository() is the root of the problem.  It needs to check for changes to the entity's unique properties and verify the new values are still unique.

**Comment by mandy-chessell** [comment]
@cmgrote - I thought you would like this one :)
