### ISSUE TITLE
Add asset indexed search in Egeria

### ISSUE THREAD

**Issue by bogdan-sava** [odpi/egeria#5482]
### Scope
The scope is to provide indexed search results and statistics of asset related metadata. The index will be built and maintained by AssetCatalog according to settings regarding zones and supported types.

### Diagram

![EgeriaIndexing](https://user-images.githubusercontent.com/40362260/125442941-9334ff14-7ba2-436c-9d7e-2dee7bc62504.png)

### Usecases

1.  **Initial indexing / reindex** Create/Update and saves documents into search engine for all entities of supported types in the zone membership of AssetCatalog OMAS
2.  **Update index** Based on OM events, asset catalog will publish indexing events on AssetCatalog out topic for maintaining the search indexes up to date.

**Comment by davidradl** [comment]
@bogdan-sava the picture looks good. A couple of suggestions:
- I would change the OM indexing events to OMAS events. I assume these events are not restricted to being used for  indexing.
- it is worth highlighting in the picture the general indexing connector (like the event bus is the general version and the Kafka connector is the implementation) so we can easily add other indexing implementations (e.g.lucene solr etc).

**Comment by mandy-chessell** [comment]
Agree - good picture - in addition, the UI Server Chassis should connect to Elastic search via the connector so it is independent of the search technology.  In fact - the UI Server Chassis could also be the server that listens to the Asset Catalog OutTopic and writes to the search technology through the connector as well.

**Comment by bogdan-sava** [comment]
Indeed, not only indexing events, but diagram is scoped for the indexing flow.
I agree that  ui-chassis-spring should be independent of search technology, but I don't think it should handle indexing process.

**Comment by bogdan-sava** [comment]
From zoning perspective might be a problem if the indexing is done by OAMS.
If supportedZones configuration of omas changes, index is not updated for zones are not supported anymore.

Indexing outside OMAS and having zoneMembersip in the search index and filter results by zone, looks better to me from this perspective.

**Comment by davidradl** [comment]
Assuming we are indexing the zones that he omas supports. If the supported zones for the omas change - then this should invalidate all or parts of the index. It seems to me that this could be a benefit, as it then means that index will need to be changed to use the new indexes. The transition would need to be managed;  but we would have the indexes using the correct zones before and then after the transition we would have an index for the new supported zones. The alternative is we index content associated with zones that might be used by the omas  in the future - which seems of no immediate benefit; but would impact performance by bloating out indexes with content that will not ever be used - apart from the unlikely event that the OMAS supported zones change.

**Comment by bogdan-sava** [comment]
There is no "invalidate" operation for index.
Why not having zones indexed and return results according to zones ?

**Comment by davidradl** [comment]
These are my perceived pros and cons of the 2 options.
 
**1) have the omas index and do the zone processing.** 
**+ves**
 callers can only see what they are allowed to. 
 zone logic is not exposed to the user and happens inside the omas.   
 simpler queries
**-ves** 
concern if the supported zones changes
**2) expose the zones in queries**
**+ve** 
more flexibility
**-ves**
 zone logic needs to  be duplicated
 zone knowledge is exposed on the omas API
 queries would need to include a zone parameter so it effects the index
 potentially index unnecessary things ( zones that are not being used currently) that could effect performance.

Maybe some example payloads, indexes and queries would help us decide.

**Comment by mandy-chessell** [comment]
The events are all coming out of one OMAS so the supportedZones is controlled by that OMAS.  This can be set to all zones of course, but this affects all users.

A request from F was that the supportedZones for the calling user can be changed via the server security connector.
This means that the user Id of the local server could be programatically set to all zones so assets from all zones are set to the indexer while all other users have a more restricted zone list.

The supportedZones can change on the OMAS - but it is a very rare event.  To allow the index to be updated the OMAS could sent an event detailing the current supportedZones to get the index to purge anything that should not be there.
Obviously if new zones are added, the assets from the new zones will not be in the index initially.

If the indexer is not hosted in the Egeria UI Platform then it needs to be part of a governance server - this sounds like a new governance server or an integration connector running in the integration daemon.  I would favour the integration connector approach because a new type of server is a lot of work.  The integration connector would probably sit in the Catalog Integrator OMIS and so would use the Asset Manager OMAS rather than the Asset Catalog OMAS.

If the connector that retrieves the metadata information from the index is responsible for enforcing supportedZones then it, or its caller needs to devise how this is managed per user in a consistent way to the rest of Egeria.  This is both a security and a usability requirement since the zones filter a lot of irrelevant assets for the users.

**Comment by Surajdivate** [comment]
Agree - good picture - in addition, the UI Server Chassis should connect to Elastic search via the connector so it is independent of the search technology. In fact - the UI Server Chassis could also be the server that listens to the Asset Catalog OutTopic and writes to the search technology through the connector as well.
