### ISSUE TITLE
Subject-Area error in processing the formation of a search request 

### ISSUE THREAD

**Issue by Inventoroz** [odpi/egeria#5501]
![Снимок](https://user-images.githubusercontent.com/12466406/126772365-ee8bfb8d-64e9-498a-9592-d7e79d4a494e.PNG)

The line of code that generates the error 
![Снимок2](https://user-images.githubusercontent.com/12466406/126772623-ef92af54-3c3e-4ebd-a7e7-572ea6eb0fbd.PNG)

**Comment by planetf1** [comment]
FYI @davidradl

**Comment by davidradl** [comment]
@Inventoroz I have totally changed the way subject area handles searches. Prior to the change, it would accept any regex expression (of which you give an example) . This was flagged as a security concern (denial of service) , because it is possible to send in a regex expression that for certain data can cause a loop. To avoid this issue, I changed to search capability so that it was a literal search, with 2 flags to change the nature of the search, one for mixed case and one for an exact search.  A search criteria of .*[n\N].* would now be treated as a literal string - i.e. match a string with the first character '.' the second character '*' etc . Interestingly internally,  we have a method that for the 'contains' semantic, we could add a flag to the API to drive that code. So for your case searching for 's' with mixed case and the contains flag set would result in the search criteria you supplied in your test.       

fyi The method for contains is : String getContainsRegex(String searchString); OMRSRepositoryHelper, with the implementation in OMRSRepositoryContentHelper.

If you need this this change raise an issue (or repurpose this one) and submit a pull request or let me know and I could put it in when I get to it.

**Comment by davidradl** [comment]
I intend to close this issue (or if you want to repurpose it)  - but would like to hear your response first.

**Comment by Inventoroz** [comment]
@davidradl, I correctly understood your answer that you have already made some changes to the code and the translated string is recognized as just a string, not a regular expression?

**Comment by davidradl** [comment]
@Inventoroz Yes that is right. closing the issue - please re open if there is more to discuss on this .
