### ISSUE TITLE
The uniqueness of the relationship

### ISSUE THREAD

**Issue by Inventoroz** [odpi/egeria#5589]
```
POST https://172.22.100.227:9443/servers/uad1/open-metadata/access-services/digital-architecture/users/admin/valid-values/1b2dedcb-35ff-4cb0-982e-1c6968f5e05f/consumers/f5523673-e148-4c33-ab0a-89d5d6f5590c
{
  "strictRequirement" : true
}
200 OK 
{
  "class" : "VoidResponse",
  "relatedHTTPCode" : 200
}
```

If you use the same request to create a relationship between entity1 and entity2 2 times, then 2 identical relationships will be created.
This can be seen from this request. 
[request.txt](https://github.com/odpi/egeria/files/6969288/request.txt)

The question is: how to make sure that the same relationship is not created?

**Comment by Inventoroz** [comment]
Is there a relationship that would allow one-to-one relationship between entities?

**Comment by mandy-chessell** [comment]
If you want to - it does depend on the type of relationship as to whether it is meaningful.  For example, there may be a relationship between a person and an asset that means that the person reviews/approves the asset.  They might create a new relationship each month when they do a review.

In the case of ValidValuesAssignment multiple relationships is unlikely to be useful, which is why updating this particular call to replace an existing relationship is a possibe approach.  Another is to throw an exception when the second relationship is created, or to rely on the caller to check if the relationship already exists befor adding it.

Personally I favour the first option.

**Comment by Inventoroz** [comment]
I think that it would be better if in the properties of the relationship there was a setting with at least 2 options:
1. Between 2 entities there can be any number of relationships of the same type
2. There can be only 1 relationship of the same type between 2 entities

And when creating a relationship, this property was checked, and if there was 1 option, then a new relationship was simply created, and if there was 2 option, then if the relationship is, an error was returned informing that the relationship already exists

**Comment by mandy-chessell** [comment]
Are you suggesting a change to the type definition or something that the caller can set on the API?

**Comment by Arturkad** [comment]
looks like the first approach would be useful for all the users. 
 In the case of ValidValuesAssignment, multiple relationships are unlikely to be useful, which is why updating this particular call to replace an existing relationship is a possible approach. 
 Can it be implemented in the call?

**Comment by mandy-chessell** [comment]
Yes it can - I can make the second call to add the relationship update any existing relationship rather than create a new one.

We had a discussion about this topic on the developer call today.  There are some additional complications in that two relationships would be possible if they had different effectivity dates.  For example, it may be that the strictRequirement property on the relationship should be set to false before September 2021 and be set to true from October 2021.  We would store that as two relationships with different effectivity dates.  The request to retrieve the relationship would return the one that is currently effective.

Currently Digital Architecture OMAS does not allow you to set up the effectivity dates.  Do you think that is something that you would need in the future?
