### ISSUE TITLE
[BUG] snyk failures during builds

### ISSUE THREAD

**Issue by alexandra-bucur** [odpi/egeria#6118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The security/snyk build check fails on all current PRs. Based on a chat with @planetf1, we might have reached the capacity for a free account.

### Expected Behavior

The check fails no more if it's not intended to notify something critical that we really need to fix asap.

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by planetf1** [comment]
<img width="1276" alt="Screenshot 2022-01-11 at 14 40 47" src="https://user-images.githubusercontent.com/7292002/148963471-73c43770-e80e-4753-b412-8bdc90335f4e.png">

**Comment by planetf1** [comment]
Snyk plan details are documented at https://snyk.io/plans/?utm_medium=Paid-Search&utm_source=google&utm_campaign=GS_SN:_Brand&utm_content=BR_BMM&utm_term=%2Bsnyk&gclid=Cj0KCQiA8vSOBhCkARIsAGdp6RRlOWkTdz7SfHg3lJnGxixyFkMrNzuZ6Ysm0grKEszAVvZ4mstpdRwaAlYLEALw_wcB

We are on the free plan

The limit is 200 tests - and each PR build will count as a test.

* We've seen the docker scan fail recently - unknown reason
* We-re hitting limits on tests
* We have other tools : codeQL, lift
* Support by linux security project is anticipated in future, which is based upon snyk, but fully licensed
* Different tools & errors impact developers. 'noise'.

Proposal: disable snyk tests.

@mandy-chessell @lpalashevski are you ok if I switch off the snyk tests due to the above.

**Comment by planetf1** [comment]
Due to the bad status marks on the PRs causing confusin, I have disabled the snyk scan for new PRs
(via snyk website)

I've not deleted the data at this point, so can be reenabled at any time.

**Comment by planetf1** [comment]
No further comments so I am going to leave snyk disabled, cleanup & close
