### ISSUE TITLE
Change Egeria docker build approach for helm charts

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#620]
Currently the egeria docker image is built from source - ie by checking out egeria from git, and building.

Instead we should be able to create the image from maven artifacts which would speed the time to build the image, and reduce the footprint of the image

**Comment by cmgrote** [comment]
Image size shouldn't be much of a factor anymore, as multi-stage build only keeps the artifacts needed (same as it would retrieve from Maven)...  I think instead we should look at releasing some auto-built images into public Docker hub under ODPi banner for people to use directly -- no need to build image at all if you're using a release that you would have gotten from Maven anyway (?)

For developers, still worth building rather than going to Maven, as Maven presumably won't have the latest changes you're in the process of developing (?)

**Comment by planetf1** [comment]
Sourcing maven artifacts for a build is technically possible, though doesn't appear to be a common pattern. It does rely on maven artifacts being 'complete'.

In terms of objective for the builds I think there's two main use cases

a) People external to the dev team who just want to pick up and run with the latest image -- dockerhub is ideal for this (I need to continue working with the lf build team on that - but something like a maven initiated build may help - which is already in place)

b) Those of us working on the images, where we want to build as quick as possible, and ideally from latest source not just from master. For that a build that takes artifacts directly from the build tree may be preferable rather than build/extract from git. One concern though is then we have two different build processes, which i;m a little uncomfortable with. Need to think about this some more.

**Comment by planetf1** [comment]
This is best covered in #821 so closing here as dup
