### ISSUE TITLE
Refactor k8s initialization scripts (igc, atlas, egeria etc)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#627]
Currently these components use a simple shell script to wait for things to be ready and then configure their co-located component.

There are common capabilities across all these scripts
 - check a REST endpoint is alive
 - Send a REST call & check results
 - check kafka is alive
 - retry loop

These scripts could a) be refactored internally b) use shared components and possibly c) be rewritten in python or another more appropriate language if not needed.

Not an immediate issue to resolve

**Comment by cmgrote** [comment]
I'll have a deeper look once I've done the initial change for postgres, but I think I have a pattern that should work for all of these configuration bits:

- a single (small) image that can be re-used for all of them
- dynamically fed its script for what to check (what makes each existing image "unique") as part of the Helm chart
- deployed as either `initContainers` so that they block deployment of main container, or `Job`s that execute immediately upon main container being available and then go away without retaining any resources, namespace, etc

**Comment by planetf1** [comment]
Sounds interesting - the first two were the kind of thing I was considering. I hadn't considered jobs, but that's an interesting idea.
