### ISSUE TITLE
[BUG] Allow Native repositories to be configured with an event mapper.

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you try to associate an event mapper with a native repository, using admin command /local-repository/event-mapper-connection, then the request is rejected as we are not a repository proxy. Further more the event mapper is not initialised unless for native repositories.

The reason an event mapper is useful along side a native repository - is that it can feed content from a 3rd party repository directly into the native repository. 

### Expected Behavior

loosen the logic to allow native repositories to be configured and started with an event mapper 

### Steps To Reproduce

Configure an in memory repository and issue a post " /local-repository/event-mapper-connection". It will be rejected

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

**Comment by mandy-chessell** [comment]
I suggest you use the RepositoryProxyConfigurationClient for configuring the repository proxy since it limits the api to the methods that are valid for the repository proxy.   See https://egeria-project.org/services/admin-services/overview/

Using the

**Comment by mandy-chessell** [comment]
You can update the local repository mode in the configuration document to switch it to a repository proxy to allow the event mapper to be set up.

**Comment by mandy-chessell** [comment]
I recommend that this issue is closed since:
* It is possible to configure a native repository in a repository proxy - it just needs the correct commands to be issued.
* Configuring an event mapper in a metadata access store is invalid and so the error message and exception is correct.

It is important that the correct commands are issued so that the local repository mode is set up correctly - otherwise the OMRS does not initialise correctly.  For example, it only sets up an event mapper if the local repository mode says it is a repository proxy.  The admin commands are set up to guide the administrator to use the right commands for the right purposes and provide helper classes to simplfy the configuration for common cases.

For example, the in-memory admin command is a helper command that sets the in-memory repository up in a metadata access store.  It is more than just setting up the in-memory repository connection.  To this end it is documented in the pages that describe setting up a metadata access store and not in the documentation for a repository proxy.

It has taken a lot of work to get the design to this point where there is clarity of what to configure for each type of server.  There is also flexibility in being able to used the repository connectors in different types of server.  There is no need to muddy the API in this way.

If you want to persist in this design change then it needs to be reviewed by the community and it needs to include all of the documentation updates to people can assess the impact of this change on consumability.
