### ISSUE TITLE
Consider switching to adoptopenjdk/alpine base images for java apps in charts

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#670]
See https://hub.docker.com/u/adoptopenjdk & https://developers.redhat.com/blog/2017/03/14/java-inside-docker/

Currently the Egeria vdc docker images are based on standard ubuntu & the ubuntu distributed openjdk & generally work.

However the images above may provide a better base environment that is more container aware in terms of resource limits within the container.

**Comment by cmgrote** [comment]
Started on this for Egeria itself with #741 -- think we need to do the same for other images as well.

**Comment by cmgrote** [comment]
Since I closed the PR to cater for a variety of approaches, adding discussion back here:

> I've tried to add containerization based issues into https://github.com/odpi/egeria/projects/8
#670 refers to wanting to switch to alpine to make the images smaller, but there are also images from AdoptOpenJDK which I haven't looked at yet.

The approach I took was to use OpenJDK's official image, one of which uses Alpine as its own base (so it's likely as minimal yet still "official" as they'll come).  This resulted in an Egeria OMAG Server Platform image at 130MB, same for the Egeria UI image, and an Apache Atlas image from Graham's managed fork (including embedded HBase and Solr) at approximately 1.3GB.  (That's down from 2.56GB and 10.3GB respectively -- so 10x+ reduction...)

> For the images themselves, as well as the base image to draw from there is refactoring needed in the scripts -- but I still have a few components to go, so will review based on that experience.

I think it makes sense to break the whole process down into different steps, like:

1. Build the component (Egeria, Apache Atlas, Apache Ranger, etc) as vanilla -- granted this could be just taking a release from Maven
1. Package the runtime into an image (without all the build toolchain, so 10x+ reduction in size)
1. (Use this runtime image (only) in all subsequent steps)
1. Define the composition of these runtime images (eg. via Helm charts).
1. Orchestrate the configuration of those runtime images (this bit I'm less opinionated on so far, as haven't seen a great approach for this yet; but the method at the moment of embedded init containers seems messy and high maintenance to me?)

> On the build - no question. But we need ODPi engagement to get the generic id and build support. Some could be built within the build, though a seperate process is better. Versioning will need to be automatic and that needs to extend to the helm chart definitions tool We will need to push to a public repo which may or may be be dockerhub (it was a tactical option to get something working quickly)

👍 

> It's also worth considering how we build the images.

> For egeria, from source seems a good option - though we also need images from other projects where we either have source or don't. This could be at docker build time, or for more flexibilityt at deployment time - but that is awkward if the build time is extensive.

I thought the target was everything open source -- for which projects do we not have the source (ie. is the source not in a public repository like GitHub), or we don't already have an image that fulfils step (2) / (3) above?

The great thing with `source-to-image` is that you can pull directly from a public source repository (not necessarily one that we own / manage) and build the image from it -- so as long as it's git-cloneable it's easy (no Dockerfile needed). For projects that already have "official" images, let's just start at step (3) above and not re-invent the wheel with (1) and (2) (?)

> Use of the maven artifacts is my favoured mechanism - as I originally tried with IGC, but it didn't quite work. That could _optionally_ allow the image to self-update at deployment time IF THE USER WISHED - most likely for the development use case.

👍 for the general case; for development, always needing to update (in-image) might be a bit cumbersome -- for the development use case it's probably simplest to just use a build image directly (not a multi-step process that results in a slimmed-down image).

> My hope was to learn a little more at think, and then us do some research on the different possibilities, frameworks. IBM has microclimate for example -- but something open is needed (or there needs to be multiple options)

My hope is to avoid re-inventing the wheel, and indeed to keep it open!

**Comment by planetf1** [comment]
One observation in terms of image size reduction -- 

 - use of a multistage docker build - step one is creating the right artifacts in the container (like a maven build, or could be retrieval of artifacts), the second is use of the right runtime . For an example see https://stackoverflow.com/questions/27767264/how-to-dockerize-maven-project-and-how-many-ways-to-accomplish-it

**Comment by cmgrote** [comment]
Working on a simple multi-stage build approach using native docker commands rather than any external tools...
