### ISSUE TITLE
[Enhancement] Introduce a repository proxy embedded repository connector

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#6998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Please describe the new behavior that that will improve Egeria

[A repository proxy can have an ](https://egeria-project.org/connectors/repository/repository-connector-intro/?h=adapter) shows that a repository proxy can have a third party repository proxy and an optional event mapper.

Repository proxies like [https://github.com/odpi/egeria-connector-hivemetastore](https://github.com/odpi/egeria-connector-hivemetastore) and https://github.com/odpi/egeria-connector-repository-file-sample, use a different pattern where the event mapper polls for the 3rd party metadata content and writes it to an omrs repository proxy connector that caches the metadata in an embedded Egeria repository. For this pattern it would be good if there was a repository proxy embedded repository connector in the base Egeria repository that could be used by OMRS connectors that want to use this pattern.  

 

this connector could be used by an repository proxy that is looking to use an embedded repository.  

### Alternatives

Each connector could have their own caching connector. Potentially leading to divergent implementations

### Any Further Information?
I will document this connector under issue [https://github.com/odpi/egeria-docs/issues/533](https://github.com/odpi/egeria-docs/issues/533)

### Would you be prepared to be assigned this issue to work on?

- [X] I can work on this

**Comment by davidradl** [comment]
I am thinking of putting this under open-metadata-collection-store-connectors

**Comment by planetf1** [comment]
I think it's excellent that we'll have a good starting point for more connectors following this pattern.

If we think this implementation/abstract classes are core, and a solid base, I think it's good to have in base egeria. If it's more of a sample, then we should probably have in a specific sample/template, rather than core egeria...... 

In general I think we should avoid clutter, connectors in the core, but this is verging on framework....? so probably should be?
