### ISSUE TITLE
[BUG] Data Manager OMAS and Asset Manager OMAS handle displayName and description differently

### ISSUE THREAD

**Issue by juergenhemelt** [odpi/egeria#7230]
### Current Behavior

When creating assets with the Data Manager OMAS (e. g. from within a TopicIntegrationConnector) puts the displayName and description in the according properties of the metadata element. 

On the other hand the Asset Manager OMAS create for the same properties glossary terms which are linked by the "SupplementaryProperties"-relationship to the metadata element.

This behaviour is inconsistent and can make problems when maintaining the same metadata elements with different OMASes from different connectors.

### Expected Behavior

Either the Data Manager OMAS should be extended to work similar to the Asset Manager OMAS or vice versa.

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

### Any Further Information?

@mandy-chessell any comments on this?
@davidradl fyi

**Comment by mandy-chessell** [comment]
Each OMAS is intended for a different audience and they are designed for that audience.   It is acceptable for them to be different in the way they abstract the stored open metadata.  For example, they may have course-grained or fine-grained objects passed on the interface.  

The interface does not have to use the same property names on its API as the attribute name used in the open metadata store.  For example, Asset does not support an attribute called `displayName` (see https://egeria-project.org/types/0/0010-Base-Model/) but GlossaryTerm does (see https://egeria-project.org/types/3/0330-Terms/).

* Data Manager OMAS maps Asset's `name` attribute to both `name` and `displayName` on its API.  (It supports set/getDisplayName() on its API only for backward compatibility - the aim is to remove it longer term so the Data Manager OMAS is more closely mapped to the open metadata type).
* Asset Manager OMAS maps Asset's `name` attribute to `technicalName` on its API.

When you use an OMAS API, the documentation describes the mapping.  This is an extract of technicalName from Asset Manager OMAS's javadoc.

```
    /**
     * Returns the stored name property for the asset.  This is the technical name of the asset rather than the name
     * that it is commonly known as.  If no technical name is available then null is returned.
     *
     * @return String name
     */
    public String getTechnicalName()
    {
        return technicalName;
    }


    /**
     * Set up the stored name property for the asset. This is the technical name of the asset rather than the name
     * that it is commonly known as.
     *
     * @param technicalName String name
     */
    public void setTechnicalName(String technicalName)
    {
        this.technicalName = technicalName;
    }

```
So the way to think about it is that the open metadata types are the canonical definitions and each OMAS provides their own proprietary mapping for their particualr users.  When you use an OMAS, it is necessary to use its documentation to understand ita API, not the documentation from a different OMAS.

Data Manager OMAS provides services to extract technical metadata from third party technologies.  It does not support supplementary properties because this type of information is not available in technical metadata.  Supplementary properties are typically added by an owner/steward.  Because they are added later, it may be added to a different metadata collection - therefore it is in a different entity.

Asset Manager OMAS is exchanging metadata with more sophisitcated tools/catalog that may allow augmentation of technical metadata by stewards/owners.  Therefore Asset Manager OMAS does support supplementary properties.  It is not the only OMAS to do this.  Governance Program OMAS and Stewarship Action OMAS also supports supplementary properties.  I also plan to add support for them to Asset Owner OMAS and the Connected Asset Services.

The OMASs that support supplementary properties use a GlossaryTerm to store the values.  They work consistently to build a glossary of business descriptions of assets that have be augmented with supplementary properties.  Although it is not required in our coding standards, the names used on the OMAS APIs supporting supplementary properties map 1-1 with the names of the attributes in the GlossaryTerm type.

**Comment by davidradl** [comment]
@mandy-chessell  As you are aware for the sample lineage integration connector, we drive the asset manager. You say " Supplementary properties are typically added by an owner/steward. Because they are added later, it may be added to a different metadata collection - therefore it is in a different entity.". In the use case we are dealing with this is not the case, we have the name and description associated with the asset and there is no current intent for this to be amended by the steward / owner outside of this connector interaction. So, as far as I can see in this use case,  the short name and a description are technical metadata for this asset. For this use case there is no need for the supplementary properties. I wonder what you think of:
1- amending the lineageIntegrator connector and the omas to have an option to not use supplementary properties, so if there is a name and description is could be stored in the asset. 
2- amending the Strimzi and event schema integration connector to use the asset manager omas - so everything is consistent. This does not seem desirable , as it does not need the supplementary properties. 
3- a new omas that does the same as the asset manager omas but does not create supplementary properties.

I am thinking option 1, could work. I drew a picture to try to describe what you said:

<img width="645" alt="Screenshot 2022-12-07 at 10 11 29" src="https://user-images.githubusercontent.com/39792797/206154812-9ad36954-2cf6-4377-989c-ef29640b070b.png">

 @juergenhemelt

**Comment by davidradl** [comment]
@mandy-chessell I have just seen your comment on  [https://github.com/odpi/egeria/issues/7226](https://github.com/odpi/egeria/issues/7226) I will test using the technicalName and technicalDescription.

**Comment by davidradl** [comment]
From my It looks like using technicalName and technicalDescription works for assets :-) .

For schema attributes and schema attribute, technicalName and technicalDescription did not work the same as assets.  The code updates if I use displayName and description which updates the attribute or schema element itself and the associated glossary term.

**Comment by davidradl** [comment]
@juergenhemelt using technicalName and technicalDescription works for assets and using displayName and description does what you want for EventType an Attributes.

@mandy-chessell It seems that SchemaTypes and SchemaAttributes also gain supplementary properties. These types differ from Asset as SchemaElements have a displayName not a name. To be consistent, should we deprecate displayName, add name attribute into SchemaElement, then amend the logic in the Asset Manager OMAS to honour the technicalName and technicalDescription for SchemaElements?

**Comment by mandy-chessell** [comment]
These comments appear to imply that an OMAS *must* follow the naming from the open metadata types and the naming and abstraction of the beans *must* be the same in each OMAS.  This is not the case ... please refer to the first line of my previous comment. https://github.com/odpi/egeria/issues/7230#issuecomment-1339681797.  Our OMASs are designed for their caller and need only to be self-consistent.

Suggestions of changing names in the open metadata types or APIs just so that they are consistent with one another is not valid.  Fundamentally the sample described above is not coded correctly for the interface it is using.  Claiming that the interface should be changed to make the sample correct seems the wrong way around.

Looking at the options in comment https://github.com/odpi/egeria/issues/7230#issuecomment-1340724890

* Option 1 - this currently supported because GlossaryTerm and SupplementaryProperties relationship are only set up if the supplementary properties are populated by the connector.  If the connector is correctly coded for the API it is using, the desired effect is achieved.
* Option 2 - your choice - I do not think this is particularly helpful.  The only connector that is incorrectly coded is the sample lineage connector.
* Option 3 - this is crazy since the supplementary properties are only used if the connector sets them.  Since this behaviour is entirely optional then no need for a new OMAS.

This diagram above is not correct either.  I have redrawn it ...

![image](https://user-images.githubusercontent.com/12354195/206215175-2f692393-86c0-407b-ba94-18410fd484df.png)

On the comment that in your particular use case, the supplementary properties are not abailable because theree is no support for stewardship intervention from the lineage source is ok - if you leave the supplementary properties blank they are not set up.

**Comment by davidradl** [comment]
hi Mandy, I think you were responding to my [comment](https://github.com/odpi/egeria/issues/7230#issuecomment-1340724890) above -  have the asset side of things working using the technical name and technical description. Apologies- I think our comments crossed. I now have the schema type and schema attributes working [comment](https://github.com/odpi/egeria/issues/7230#issuecomment-1341041664)  but not consistently with the way that asset is working .

**Comment by mandy-chessell** [comment]
That is curious since the design is the same.  Are you saying that setting `technicalName` and `technicalDescription`  in SchemaProperties does not update the schema element?  Which properties are updated?

**Comment by mandy-chessell** [comment]
At last! - that looks like a bug - I have checked the code and can see where it is going wrong.

The use of 'name' verses 'displayName' in our open metadata types comes from our initial use of the Atlas types but we currently have a convention that `name` is used for a description of physical thing -  Asset, Endpoint, ActorProfile and SoftwareCapability are examples - to allow for the displayName as augmentation.  Changing SchemaElement to use `name` rather than `displayName` would break that naming convention and would cause a lot of breakage in the existing code/stored metadata so I would not recommend it.

Given that, I have decided to remove the use of supplementary properties from SchemaElement in Asset Manager OMAS and Stewardship Action OMAS.  I am still in the middle of writing them so change should be expected.  The reason for this is that the names used in the SchemaElements are the choice of the programmer - not bound by a physical name.  So an organization would be using their own naming conventions for the schema elements and the supplementary properties are not needed.

This would leave supplementary properties used for the Assets (both data assets and IT infrastructure assets), Endpoint and SoftwareCapability.
