### ISSUE TITLE
question about data model and ontology

### ISSUE THREAD

**Issue by PeterChenTian** [odpi/egeria#7407]
![model](https://user-images.githubusercontent.com/19702268/218408570-86e95ab3-838b-48f9-a20c-7e19d390c66b.png)

In the picture, glossaries guide data model,  golossaries generate ontology

my question: 
1. Does this data model in picture means conceptual model, and is there some tools to build this model?
2. There are few materials about ontology, what is ontology, is there any reference material to learn?

**Comment by mandy-chessell** [comment]
Hello @PeterChenTian 

Data models can be at any level of abstraction from conceptual models to physical data models.  They are typically modelled using Entity-Relationship modelling tools such as ERWIN.  Database tools often have E-R modelling tools but they focus on the physical data modelling that is 1-1 with a database schema.

Ontologies are models of a knowledge domain.  The most popular modelling language for an ontology is OWL (https://cambridgesemantics.com/blog/semantic-university/learn-owl-rdfs/owl-101/). With an ontology, it is possible to reason about data.  It has more semantics that just a glossary and includes instances as well as "classes".  It is then possible to reason about the instances.

Connecting to glossary terms to ontologies shows the equivalence of concepts.  It is possible to generate a simple ontology from an Egeria glossary.

There is a lot more detail in this book: https://www.oreilly.com/library/view/common-information-models/9780133366358/

It is also potentially useful to load the data models and ontologies into the open metadata ecosystem to link then to generate physical schemas and link to consuming assets.

The type system in Egeria has an abstract notion of a "Design Model Element"(https://egeria-project.org/types/5/0565-Design-Model-Elements/) to cover elements loaded from ontologies and data models.

So far, I have created sub types for concept models (https://egeria-project.org/types/5/0571-Concept-Models/) and I have the design for types for logical and physical data models, but not added them to Egeria yet because no-one has asked for them.

I can soon add them if you need them.  Also if you need types for ontologies I can create them too.

**Comment by PeterChenTian** [comment]
> Hello @PeterChenTian
> 
> Data models can be at any level of abstraction from conceptual models to physical data models. They are typically modelled using Entity-Relationship modelling tools such as ERWIN. Database tools often have E-R modelling tools but they focus on the physical data modelling that is 1-1 with a database schema.
> 
> Ontologies are models of a knowledge domain. The most popular modelling language for an ontology is OWL (https://cambridgesemantics.com/blog/semantic-university/learn-owl-rdfs/owl-101/). With an ontology, it is possible to reason about data. It has more semantics that just a glossary and includes instances as well as "classes". It is then possible to reason about the instances.
> 
> Connecting to glossary terms to ontologies shows the equivalence of concepts. It is possible to generate a simple ontology from an Egeria glossary.
> 
> There is a lot more detail in this book: https://www.oreilly.com/library/view/common-information-models/9780133366358/
> 
> It is also potentially useful to load the data models and ontologies into the open metadata ecosystem to link then to generate physical schemas and link to consuming assets.
> 
> The type system in Egeria has an abstract notion of a "Design Model Element"(https://egeria-project.org/types/5/0565-Design-Model-Elements/) to cover elements loaded from ontologies and data models.
> 
> So far, I have created sub types for concept models (https://egeria-project.org/types/5/0571-Concept-Models/) and I have the design for types for logical and physical data models, but not added them to Egeria yet because no-one has asked for them.
> 
> I can soon add them if you need them. Also if you need types for ontologies I can create them too.

hi，Mandy，thanks for your reply，whether data model or ontology, they have instances and relationships. In open metadata system, if  dataset is used to describe the data model or ontology, then some of the previously defined relationships cannot be used, such as the leader relationship between employees and leaders or the employment relationship between employees and the company, etc.  But with egeria type, (such as the facilities type in coco), it is easy to realize these relationships, and these instances will be stored in the metadata repository instead of the previous business tables.  I really want to define the type in egeria, but I feel that I still have to use dataset to describe it, for using dataset cannot inherit the previous relationship. I don't know if my understanding is correct.

**Comment by mandy-chessell** [comment]
DataSet entities are for digital resources (such as database views)

For the models, each your will create entities that inherit from DesignModelElement.  There is an Asset entity of type called DesignModel (https://egeria-project.org/types/5/0566-Design-Model-Organization/) for the whole model.

**Comment by PeterChenTian** [comment]
OK，thank you very much，I will take a closer look
