### ISSUE TITLE
[BUG] EgeriaSampleOntologyArchive.json import error

### ISSUE THREAD

**Issue by PeterChenTian** [odpi/egeria#7419]
### Current Behavior

1. run glossary-canonical-model project using the test json file - EgeriaSampleOntology.json
2. get the result file EgeriaSampleOntologyArchive.json
3. POST EgeriaSampleOntologyArchive.json to [{{baseURL}}/open-metadata/admin-services/users/{{user}}/servers/{{server}}/instance/open-metadata-archives/file](url)
4. the "owl:DatatypeProperty" term get error below:

OCFCheckedExceptionBase{reportedHTTPCode=400, reportingClassName='org.odpi.openmetadata.repositoryservices.localrepository.repositorycontentmanager.OMRSRepositoryContentHelper', reportingActionDescription='classifyEntity (Detailed)', reportedErrorMessage='OMRS-REPOSITORY-400-081 A classifyEntity (Detailed) request has been made to repository cocoMDS1 to add a classification Anchors to entity dc5cbfaa-bf7b-4aa2-a52f-e047ed440c50 when this entity is already classified', reportedErrorMessageId='OMRS-REPOSITORY-400-081', reportedErrorMessageParameters=[classifyEntity (Detailed), cocoMDS1, Anchors, dc5cbfaa-bf7b-4aa2-a52f-e047ed440c50], reportedSystemAction='The system is unable to perform the request as only one classification of a specific type is permitted.', reportedUserAction='Use the updateClassificationProperties to make changed to an existing classification.', reportedCaughtException=null, reportedCaughtExceptionClassName='null', relatedProperties=null}

### Expected Behavior

generate DatatypeProperty normally

### Environment

```markdown
- Egeria: 3.12
- OS: centos7
- Java: 11
- Browser (for UI issues): chrome
- Additional connectors and integration:
```

**Comment by mandy-chessell** [comment]
From the error message, it looks like the anchors classification is being added by the archive as a separate classification rather than as part of the entity.  

When the entity is added and if the anchors classification is missing, Egeria automatically adds the anchors classification.  If the archive then tries to add the classification itself then the clash occurs.

There are two lines of investigation:
* ensure the archive is only adding the anchors classification once
* improve the error handling in the archive loading so if the Anchors classification is added automatically before the archive has completed loading, it only throws an error if the new classification from the archive requests a different anchor than the one automatically assigned.

**Comment by PeterChenTian** [comment]
OK, thanks  I got it
