### ISSUE TITLE
[Enhancement] Early prototype of cloud native application

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria#7512]
### Please describe the new behavior that that will improve Egeria

This is a to produce an application that could be used more naturally with Cloud native

### Alternatives

use the existing platform 

### Any Further Information?

https://github.com/odpi/egeria/discussions/categories/cloud-native

**Comment by mandy-chessell** [comment]
Since this is a prototype, this work should not be changing core modules (admin services) in the main repository.  Cloud native operation is building an alternative way of deploying - not replacing the dynamic platform.  It is important that the dynamic platform is not broken in the process.

It would be better if you are building a new "chassis" to give it a different name - such as OMAGCloudNativeServer - rather than use the term "platform" since it is clearly not a platform.  It will also be easier to distinguish between having a dynamic platform and using cloud native services in the docs.

The new chassis should have its own operational services to bring up the server in the new chassis (it is ok to use the existing admin services for building the config doc).  This will create a better basis for moving forward with additional cloud native operation.

**Comment by planetf1** [comment]
I think that for an earlier prototype it may be best to keep this in a distinct repository

Since the objective is to reuse existing components for the actual services, that new project could consume egeria core as dependencies

A repository can be moved from a personal one to belong to an organization, and also subtrees can be merged retaining history, so there are lots of options for proposing clean PRs later, if indeed it were appropriate (it may also be that prototypes are disposed of)

Longer term, maybe it does become the same as core egeria - I don't think we know enough yet to decide

I agree with the comment above on name - this is very different to a chassis, maybe even something like OMAGServerLauncher . Also worth noting that a standalone server driver doesn't have to be used in cloud, could also be of use in on-prem, locally installed environments as it's closer to a simple process launch model. (but the complexity comes in then managing those, which is why either one might use k8s to do this, or why in fact we have the actual chassis!)

**Comment by lpalashevski** [comment]
New PR for reference: https://github.com/odpi/egeria/pull/7769
