### ISSUE TITLE
Restart of OMRS stack - not rejoining cohort

### ISSUE THREAD

**Issue by grahamwallis** [odpi/egeria#753]
Hi,
I can bring up the OMRS stack in a repository server and the repository connector registers with the cohort. If I then deactivate the OMRS stack in that server, adjust the configuration (e.g. specify a different topic root) and restart the OMRS stack, it is not allowed to re-register.

I get the following audit message:

myserver OMRS-AUDIT-0006 Configuration error detected while connecting to cohort CoCoCohort1, error message was: OMRS-COHORT-REGISTRY-400-002 The Open Metadata Repository Cohort CoCoCohort1 is not available to server myserver because the local metadata collection id has been changed from 7c4166a1-1135-4ac1-ab21-090d34e68fdb to e97f61f6-475c-47ab-957a-340401bf450f since this server registered with the cohort. (OMRSAuditLogDestination:94)

My question is this: if the above is a valid scenario (i.e. deactivate, adjust config and reactivate) then am I doing something wrong that is causing the change of metadata collection Id? Should I be preserving the same id across the restarts?

Thanks!

**Comment by mandy-chessell** [comment]
It is valid to be able to disconnect from a cohort, update cohort configuration and reconnect.  However, it needs to be done in a coherent manner.  This error message suggests that the update to the configuration changed the local metadata collection id.  This is not valid if the repository disconnected temporarily (ie permanent=false).

The local metadata collection id is the identifier of the metadata stored in the local repository.  It is assigned when the local repository is first configured and is used in remote repositories to identify the master repository of any reference copies they have stored.  If a repository changes its local metadata collection id in an ad hoc manner then the instances stored in other repositories now have the wrong metadata collection Id stored in their reference copies.   Subsequent updates to these instances will appear to come from a different metadata repository than the master repository which suggests conflicting guids, or some other sort of protocol violation.

This is why the OMRS validates that the local metadata collection id does not change between restarts of the server.   However, all other aspects of the configuration may change between server restarts, including server name.   This is because the repository issues a re-registration request when it reconnects to the cohort.  This allows all of the information about the repository to change except the local metadata collection id since that is the repository's unique identifier in the cohort.

When a repository disconnects permanently, it is saying that the other repositories are no longer going to receive any more metadata from this metadata collection id - the remote repositories get an unregistration event to remove the configuration about the metadata collection from their records.  The other members may choose to leave the reference copies from this metadata collection id in their local repositories or purge them.  The current OMRS behaviour is to leave the reference copies, and let an administrator purge them if requried.

The OMRS logs the local metadata collection id on the audit log on start up.  It is also stored in the local repository's cohort registry store (which is how the OMRS detects an invalid change in local metadata collection id and outputs that audit event reported at the start of this issue).

**Comment by grahamwallis** [comment]
Many thanks.

I think I must have reset the repository mode by mistake when I tested this before. I checked through the local repository config handling in the initialisation code and have re-tested an activate, deactivate, reactivate sequence, which is working as expected. The metdataCollectionId is maintained between first activation and reactivation, and the repository is functioning correctly following the reactivation. 

When the repository rejoined the cohort, there was a REFRESH_REGISTRATION_REQUEST event followed by a RE_REGISTRATION_EVENT from the other server on the cohort.

**Comment by planetf1** [comment]
There's some interesting implications here that I should account for in the k8s setup

* if a pod is restarted - this is often because of a temporary failure/crash -- so the server (atlas or egeria) should come up with the same metadata id. 
* if I have multiple servers they each need their own unique id. I assume this is automatically allocated on initial configuration
* I assume the mcid is stored in the *config file - and so this needs to be made persistant in a k8s environment

Finally a question - if it valid to have multiple instances of the omag server with the same mcid. For example if both were referring to the same metadata collection, through for example, using the same backend graph or rdbms store? (this would be the case if one wanted to scale for throughput/redundancy at the omag server level)

**Comment by mandy-chessell** [comment]
The metadata collection id is stored in both the config file and the cohort registry store.  The have to match on rejoining the cohort.  So both the config and the registry store need to be persisted.  Otherwise the other members of the cohort will think this is a new repository and will report logic errors if it sends out updates to instances with a different home id.

**Comment by planetf1** [comment]
Thanks. Will bear that in mind when I add persistence #766
