### ISSUE TITLE
VDC chart does not allow pulling of latest container images

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#801]
The vdc chart is not pulling the latest container images - this problem has surfaced since retagging all images with a fixed '1.1-SNAPSHOT' to reflect the egeria release, rather than a manually set incrementing version.

For end-user use (ie on released code) a default of ifNotPresent works best, but since these charts are currently fairly fluid, and work in progress, the intent was to make them default to Always.

In either case it's possible to override the default

However I realised via 'helm get deploy xxx' that the imagePullPolicy was not being set correctly.

The reason was that I had incorrectly capatalized the word as ImagePullPolicy - which is not valid and fails silently ....

Correcting!

**Comment by planetf1** [comment]
Verified. images now correctly pulled. creating pr

**Comment by cmgrote** [comment]
Actually this is precisely what you would use the `latest` tag for -- when k8s sees the tag `latest` it ignores the `imagePullPolicy` and automatically acts as if it were set to `Always`. It seems to me that for development builds we should therefore be using (defaulting to) `latest`, with an `imagePullPolicy` of `IfNotPresent` -- and then if people want to override to a specific tag they can do so without needing to change the `imagePullPolicy` (and while still benefiting from caching of layers that are already there rather than *always* pulling, even when not necessary) (?)

> The reason was that I had incorrectly capatalized the word as ImagePullPolicy - which is not valid and fails silently ....

This is one of the downsides of Helm -- it hides this sort of thing...  It might be good for us to run:

- `helm template vdc > testing.yaml` to get the template-rendered output into a file, and then 
- `kubectl apply -f testing.yaml` this to k8s directly

Then we'll see these kinds of warnings / errors, rather than them being hidden away.

**Comment by planetf1** [comment]
There are a few subtle implications with latest also -- specifically the way the image is built. The docs in each README cover a scenario that builds without a tag, then tags later (the result is this is the image that will be resolved by latest). The current maven (spotify) docker plugin doesn't do this, so I think images aren't seen as latest. We could though address this.

For anyone just wanting to take our charts and use, a specific version probably works best, but the current 1.1-SNAPSHOT probably isn't fine enough, as I think we'll update quicker than the code release cycle. Manual change is tedious. 

The end result is that probably, despite the caveats, making latest work probably is the simplest path (and retailing ifNotPresent)

++ on the helm steps. May be useful to doc i agree albeit targetted at the dev/debugger. Actually it's how I determined my error in this case.. using the template.

**Comment by cmgrote** [comment]
> The end result is that probably, despite the caveats, making latest work probably is the simplest path (and retailing ifNotPresent)

I'll make this change as part of #739 ...
