### ISSUE TITLE
OutOfMemory errors caused by accumulation of incoming Kafka messages

### ISSUE THREAD

**Issue by dkantor** [odpi/egeria#861]
We have seen OutOfMemory errors with the following stack trace.  Analysis of heap dump showed there was a backlog of 53,079 unprocessed kafka messages in `KafkaOpenMetadataTopicConnector`, taking 412 MB of heap space.
```
java.lang.OutOfMemoryError: Java heap space
    at java.lang.StringBuilder.ensureCapacityImpl(Unknown Source)
    at java.lang.StringBuilder.append(Unknown Source)
    at java.lang.StringBuilder.append(Unknown Source)
    at java.util.AbstractCollection.toString(Unknown Source)
    at java.util.Collections$SynchronizedCollection.toString(Unknown Source)
    at java.lang.String.valueOf(Unknown Source)
    at java.lang.StringBuilder.append(Unknown Source)
    at org.odpi.openmetadata.adapters.eventbus.topic.kafka.KafkaOpenMetadataTopicConnector.checkForEvents(KafkaOpenMetadataTopicConnector.java:246)
    at org.odpi.openmetadata.repositoryservices.connectors.openmetadatatopic.OpenMetadataTopicConnector.run(OpenMetadataTopicConnector.java:96)
    at java.lang.Thread.run(Unknown Source)
```
Please see [Jeff Hagelberg's comment about Kafka polling](https://github.com/odpi/egeria/issues/860#issuecomment-473388268).

> The issue is that you can see in `KafkaOpenMetadataEventConsumer` that the code polls Kafka once every second and adds what it finds to a list. `KafkaOpenMetadataEventConsumer.run()` needs to be changed to check the size of the kafka message backlog before polling kafka, and poll only if the number of queued events is small. That should be done as part of this issue. It is really the root cause of the issue. Once that is done, fixing the logging becomes less important (although it does need to be done as well)

**Comment by jnhagelberg** [comment]
The easiest way to fix this would be to add a method to `KafkaOpenMetadataTopicConnector` to get the current size of `incomingEventsList`, such as `getIncomingEventListSize()`.  Then, you would update the code in `KafkaOpenMetadataEventConsumer.run()` to make the Kafka polling conditional.  Something like:
```

        while (isRunning())
        {
            try
            {
                if (connector.getIncomingEventListSize() > 100 ) {
                    continue;
                }
                ConsumerRecords<String, String> records = consumer.poll(defaultPollTimeout);
                log.debug("Found records: " + records.count());
                for (ConsumerRecord<String, String> record : records)
                {
                    String json = record.value();
                    log.debug("Received message: " + json);

                    if (! localServerId.equals(record.key()))
                    {
                        try
                        {
                            connector.distributeToListeners(json);
                        }

```

**Comment by mandy-chessell** [comment]
Looks a good fix - feel free to add PR.

Why are the messages backing up?  Has there been another failure in the consumption side?

**Comment by jnhagelberg** [comment]
@mandy-chessell I think it was mostly because messages were coming in much faster than we could consume this.  This was seen during testfest.  Some of the bigger imports generate a huge number of messages.  Between that and the large amount of activity going on concurrently, we just got overwhelmed with messages.

**Comment by mandy-chessell** [comment]
Great to see that you are doing these load tests to help flush out these type of issues - thank you :)

**Comment by jnhagelberg** [comment]
@mandy-chessell I've created https://github.com/odpi/egeria/pull/862 to get this into the 1.0 release.

**Comment by planetf1** [comment]
Additional thought:
 - By default it would seem offsets are being committed automatically, probably every 1s.
 - since any buffered inbound events have been read from kafka, the offset will be set later
 - in the event of failure we are exposed by the max batch size (before up to mem limit and beyond, now 100) ?
  - a correct assessment?
 - if so we may want to ensure the value can be configured even lower for those who need to minimize exposure at the expense of async.
 - or we may want to look at manually commiting offset - after event processed.
