### ISSUE TITLE
Need option to allow committing the offset of kafka messages after processing 

### ISSUE THREAD

**Issue by hjv333** [odpi/egeria#863]
Currently, for omrs sync operations, kafka consumer enable.auto.commit is being used to commit messages.

There should be an option to allow committing a kafka message only after the repository connector has processed the message.

As seen in https://github.com/odpi/egeria/issues/861 , if the application running the omrs server instance needs to be restarted due to out-of-memory or other issues, it is possible to "lose" all of the kafka messages that have been queued to be processed (and where the consumer partition offsets have been auto-committed), but the repository connector has not processed the messages yet.

**Comment by planetf1** [comment]
!!! Just read this after posting the same question to the original issue.
I agree entirely... as we are exposed by the batch size, default for us is commiting after 1s, probably need to explicitly commit.

**Comment by mandy-chessell** [comment]
So how would you like this to work?  Such things are always a compromise.  The buffering was done because one product needed Egeria to feed them events as fast as possible.  In fact I have an enhancement request to parallelise this inbound processing further.

There are 20+ consumers on the kafka topic within a typical server.  They are processing inbound events at different speeds.  Do we commit when the first one is complete - or when all are complete?  What if the 5th one fails?  There is no rollback.   So this suggest each consumer gets one shot at processing the event?   Or are they allowed to prevent the commit of the event receipt indefinately?

If we assume that it is bad to loose messages then we could (1) minimize the buffering in memory and (2) commit when all consumers withing the server have processed the event.  This means that consumers will need to be prepared to receive the same event many times in the event of multiple perpetual failures.

One other thought - the inbound processing is through 2 connectors.   The event bus connector is specific to the event bus technology (eg Kafka, RabbitMQ, ...).  It is wrapped by a connector specific to the type of consumer.  The purpose of this is to ensure Egeria can run in a highly heterogenous environment.  Your design need to respect this plugability.

**Comment by cmgrote** [comment]
> There are 20+ consumers on the kafka topic within a typical server. They are processing inbound events at different speeds. Do we commit when the first one is complete - or when all are complete? What if the 5th one fails? There is no rollback. So this suggest each consumer gets one shot at processing the event? Or are they allowed to prevent the commit of the event receipt indefinately?

Kafka manages commits by consumer, so we should be able to keep the offsets (and commits) distinct by consumer -- at least when using Kafka as the bus...

**Comment by planetf1** [comment]
^^ As above - committed offset is by consumer group. For each type of consumer that would be unique, but where we have multiple instances of a consumer to scale (for example multiple OMASs across systems?) we would keep the consumer group the same

https://dzone.com/articles/kafka-consumer-architecture-consumer-groups-and-su

**Comment by planetf1** [comment]
To maximise throughput we should also consider (and I know this needs more investigation/research)
 - having multiple consumers on multiple 'machines'/containers supporting a partitioned topic
 - buffering a small number but committing once processed - and accepting we may get dups, but probably safer than losing messages (though that would need more work to totally eliminate I'd guess)
 - ensuring the behaviour is configurable given the likelyhood of different requirements
 - depending on kafka settings as much as possible (and provide recommendations where known) - and similar for other providers, so that experts in those technologies can do the minimum egeria specific requirements to meet their standards
 - generalising as Mandy said for different providers --- though I suspect most pub/sub mechanisms have similar function and would work in a similar way?? That being said rabbitmq looks as if it might effectively commit the offset on read -- so if a deployment needs more safety, the batch count would need to be set to 1 

Other interesting articles
 - exactly once in kafka - https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/ (

**Comment by mandy-chessell** [comment]
This can not just be designed for Kafka - there are aspects that the kafka connector can do - but the overall system has to allow the event bus to change.

**Comment by mandy-chessell** [comment]
My current view is that we should leave the buffering to the event bus and just pull events as we can consume them but happy to be persuaded otherwise.

**Comment by mandy-chessell** [comment]
There was some concern about this change during the design meeting last week.  It is a pattern that causes messages to back up in the messaging system if one of the consumers is running very slowly or stopped.

It was agreed to hold off of the commit until all of the calls to the listeners have returned.  However waiting for an asynchronous response (presumably from a remote server) was not agreed.

Could you provide more information as to why thie IGC repository connector can not manage a cache for the event if it is slow in processing events?  Is it calling remote processes (ie in a different JVM) or is the event being lost within the repository connector's JVM.  What is causing this?

**Comment by jnhagelberg** [comment]
@mandy-chessell Thanks for looking at this.  Sorry for the delayed response.  I had to take some unexpected time off for personal reasons and just got back.

First, let me clarify, we're not waiting for an asynchronous response from a remote server, at least in our case.  The processing is done on the same server, just in a different thread from a thread pool.  The way I've implemented this in the POC as that there are no api changes at all.  The implementation in the MetadataConnector has the option of associating a Future with its processing.  This call is made on a thread local processing context.  This avoids the need to have API changes.  It will be more clear when you see the code :-).  If we don't have this async mechanism, the code changes in egeria will not help for us, since all of our messages processing is asynchronous.  The mechanism is strictly opt-in.

The problem we are facing is that the pod is being unexpectedly restarted by kubernetes because the processing is consuming so many resources that the application is unable to consistently respond to the heartbeat api.  When that happens, kubernetes automatically restarts the pod, and all messages that had been fetched from kafka but not completely processed are lost.  In our performance testing, there are 1000s of messages that need to be processed.  We have put in changes to minimize the frequency of the restarts, but we cannot prevent them entirely.  There are also many other scenarios that could cause a pod to terminate unexpectedly and cause message loss.  Missing just one message can make the difference between an asset being synced and not beeing synced.  

In my current POC, the message is only treated as being consumed when all of the consumers of the message finish processing it.  Right now there is not a time out, but that would not be difficult to add.  I should have code available to review fairly soon.  I have finished the POC and am in thee process of doing testing to make sure it behaves the way I expect.  Once that is done, I'll create a PR and submit the code for review.

**Comment by jnhagelberg** [comment]
@mandy-chessell To answer your other question, I guess theoretically we could have CAMS keep a queue of unprocessed messages and have that be used for the asynchronous processing.  However, that adds a lot of complexity on our side.  We'd need to store the messages in some external distributed cache, like redis.  We would then need to add logic for managing the lifecycle of the messages, much like what kafka already does.  As other consumers move to asynchronous processing for better performance like we did, they will need similar logic.  It seems a lot simpler to have logic for handling this in OMRS, where all of the implementations can make use of it and where we can still leverage the built-in kafka mechanism for managing messages rather than inventing our own.

**Comment by jnhagelberg** [comment]
One thing I just thought of, though. is that making a chance like that on our side would allow us to distribute the message processing across the pods even though we just have one kafka consumer.  It may end up being worth the added complexity for us since we might be able to get an additional performance boost.  I'll discuss this with the team.

**Comment by planetf1** [comment]
I'm not familar enough with your work in cams so apologies in advance, but I would expect any processing to be done 'quickly' before returning -- and then at that point we commit. This should be the contract - the point at which we hand over responsibility. If the component in question (the cams connector?) needs longer then it should take responsible for putting an appropriate asynchronous mechanism in use for managing it's workload - be it using a distributed cache, or indeed requeuing onto a private kafka topic - something persistant enough to survive restarts (a valid point in a k8s environment where pods being restarted and moving is BAU). My concern with the proposed mechanism is that it adds significant complexity to egeria core  - keeping the concerns isolated would be better IMO.

**Comment by jnhagelberg** [comment]
Hi Nigel,

Thanks for your response.  First, I want to clarify that that the mean reason we are processing the messages asynchronously is due to the sheer volume of messages we have to process.  The individual messages process fairly quickly, but when you do a performance test that tries to sync 1000 tables, that is a minumum of 3000 messages just for the basic table information plus 4 messages for every column.  So for 1000 tables with 10 columns each, that is about 43,000 messages that we need to process.  In practice, now many of them are packaged together in batches, but we still need to process them one at a time.  

We just cannot scale if we process one message at a time, so we have been forced to process the messages in parallel.

I agree that allowing the async processing does add some complexity, but it is not actually not as much as you think.  Take a look at my PR https://github.com/jnhagelberg/egeria/pull/1, where I have a POC for this mechanism.  The main changes are in open-metadata-implementation/adapters/open-connectors/event-bus-connectors/open-metadata-topic-connectors/kafka-open-metadata-topic-connector/src/main/java/org/odpi/openmetadata/adapters/eventbus/topic/kafka/KafkaOpenMetadataEventConsumer.java, to add background checking for what indices are ready to be committed.  The changes add about 20 lines to the file.  The rest of the PR is mostly plumbing and a few utilities.

The other point I want to make is that this is not a problem that is unique to us.  Processing one message at a time really does not scale.  It seems like it would be better to have a mechanism for doing asynchronous processing built into egeria so that everyone does not need to invent their own thing.  I also think that the changes in the egeria are much less complex than the changes we would need to put on our side to handle asynchronous processing.  Egeria can leverage the built-in kafka commit mechanism to handle this.  We would need to implement an entirely new mechanism to store messages in etcd as we receive them, maintain the state of the message so that we only remove messages from the queue when they are processed, and have a background thread to read from the queue.  With the changes in egeria, we get the same thing, but with much less effort since kafka handles it.  And on top of that, the logic is available for other implementation to use with very minimal effort.

**Comment by jnhagelberg** [comment]
@planetf1 ^^

**Comment by cmgrote** [comment]
I think we have the baseline code resolving this issue merged already?  Can we close this issue to track any further revisions through more specific issues?

**Comment by jnhagelberg** [comment]
@cmgrote Yes, this can be closed.
