### ISSUE TITLE
RDBMS connections

### ISSUE THREAD

**Issue by wiktorof** [odpi/egeria#938]
is there any tutorial or explanation how to connect existing systems, e.g. relation databases to egeria to share technical metadata? or it's not really an egeria goal to provide this type of functionality?

**Comment by mandy-chessell** [comment]
Short answer is that is this a valid use case for Egeria, but the implementation is not quite there yet which is why you are not finding the tutorials.

This is a bit more explanation on how this will work...

The Egeria open connector framework (OCF) will support connectors to RDBMS.  This will allow a consumer of data to issue queries on the data and also request comprehensive metadata (technical, business, governance, ...) about the database.  Today we have one OCF JDBC connector that is linking the Apache Derby database driver.  This needs to be made more general so we can support JDBC to many databases.

The Asset Owner OMAS will provide APIs to manually add a basic catalog entry for a database to the metadata repository. (The Asset Owner OMAS is under development.)

Adding the catalog entry can trigger a discovery engine to connect to the RDBMS and extract the schema and profile the content.  The profiling can be re-run periodically.  (Discovery is under development at the moment.)

The data platform bridge (a governance server) is able to periodically validate that the schemas in an active RDBMS match those in the metadata repository. (This is a future work item)

The outlook for the Asset Owner OMAS and Discovery Server is about 3 weeks.

**Comment by fpompermaier** [comment]
Any progress on this? It would be very useful to attach Egeria to an existing RDBMS

**Comment by mandy-chessell** [comment]
Hi - it ids work in progress for our next release (1.5) which is slated for end of Feb.  We will test with Postgres as it is open source.  If you are using another DB then it would be helpful if you could test it for us

**Comment by fpompermaier** [comment]
Ok, I could give it a try with MySQL, H2 or Oracle

**Comment by grahamwallis** [comment]
Still needed
